name = "GreedyCraft2"
author = "mc_Edwin"
version = "2.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58a9b827c959eb549b6da550d55c7b1ca5cbe8cb060e0ee2bb1e46340afd94d2"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
quilt = "0.17.0"
