name = "GreedyCraft2"
author = "mc_Edwin"
version = "2.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11ebec840952e47c43cbb4656534fbaf884f871eb0776c09a50e113c640b7f4e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
quilt = "0.17.0"
