name = "GreedyCraft2"
author = "mc_Edwin"
version = "2.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bc6b5a27d88f237eeea35aa9ddbbc56c9bd72e4c28bc3ffb5ad13f75b272bd1"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
quilt = "0.17.0"
