name = "GreedyCraft2"
author = "mc_Edwin"
version = "2.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29dc790eeb22978b3ecc71c4186917d77c43e9f723889a9020fb74eff9382071"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
quilt = "0.17.0"
