name = "GreedyCraft2"
author = "mc_Edwin"
version = "2.7.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5ace64f69eb66914f1117952bfd5cdde6317e1f4dcea386624c10965c476cac"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
quilt = "0.17.0"
