name = "GreedyCraft2"
author = "mc_Edwin"
version = "2.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ed336166438b0f9b5293d00e4473acf8a3088411957b2aab8b671fbe2393f45"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
quilt = "0.17.0"
