/*
 * This script is created for the GreedyCraft modpack by TCreopargh.
 * You may NOT use this script in any other publicly distributed modpack without my permission.
 */

#priority 800

import crafttweaker.game.IGame;

import scripts.util.lang as LangUtil;

val localizationMap as string[string][string] = {
    zh_cn: {
        "dragon.minion": "龙之侍从",
        "dragon.larva": "龙之幼体",
        "wither.minion": "凋灵侍从",
        "material.adamant.name": "精金",
        "tile.adamant_block.name": "精金块",
        "tile.adamant_ore.name": "精金矿石",
        "item.adamant_nugget.name": "精金粒",
        "item.adamant_dust.name": "精金粉",
        "item.adamant_ingot.name": "精金锭",
        "fluid.tconstruct.adamant_fluid.name": "熔融精金",
        "item.itemcraftingcomponent.reso_gem.name": "共振海蓝宝石",
        "tile.thaumadditions:adaminite_smelter.name": "铿金源质冶炼厂",
        "tile.thaumadditions:jar_adaminite.name": "铿金源质罐子",
        "tile.thaumadditions:adaminite_block.name": "铿金块",
        "item.thaumadditions:adaminite_nugget.name": "铿金粒",
        "item.thaumadditions:adaminite_ingot.name": "铿金锭",
        "item.thaumadditions:adaminite_plate.name": "铿金板",
        "item.thaumadditions:adaminite_nugget.name": "铿金粒",
        "item.thaumadditions:adaminite_fabric.name": "铿金布匹",
        "item.thaumadditions:adaminite_sword.name": "铿金剑",
        "item.thaumadditions:adaminite_hood.name": "铿金神秘使兜帽",
        "item.thaumadditions:adaminite_robe.name": "铿金神秘使法袍",
        "item.thaumadditions:adaminite_belt.name": "铿金神秘使腰带",
        "item.thaumadditions:adaminite_boots.name": "铿金神秘使靴子",
        "research_name.thaumadditions:adaminite": "铿金金属",
        "research_stage.thaumadditions:adaminite.2": "我的实验已大获成功！书中它这种新造物称之为“铿金”。我都要疯了！我听说过灵液，神之血，但我认为这金属要远比灵液好，尽管它存在于这世上的任何地方。",
        "research_name.thaumadditions:adaminite_smelter": "铿金源质冶炼厂",
        "research_stage.thaumadditions:adaminite_smelter.2": "好啊！铿金似乎更好更高效！铿金源质冶炼厂现在能多产生 20% 源质。这意味着我可以更少的冶炼源质了。",
        "research_stage.thaumadditions:mithminite_smelter.1": "我想要改进铿金源质冶炼厂的质量并让它更快并且经常产生额外的源质。我知道秘金应该能有所帮助，并且我需要一点实验来确认我的想法是正确的。",
        "research_name.thaumadditions:adaminite_smelter": "铿金源质冶炼厂",
        "research_name.thaumadditions:adaminite_jar": "铿金源质罐子",
        "research_stage.thaumadditions:mithminite_jar.2": "我的结论是正确的，铿金罐子可以被秘金合金用一中复杂的注魔来觉醒, 这种新的（我希望是最终的）罐子可以装 4000 点源质，是铿金源质罐子的两倍。 我同时也注意到这罐子能销毁流入的多余源质，这可能对我的那些旧的虚空罐子是应该很不错的升级，而且这也不会因为源质溢出而爆炸。",
        "research_stage.thaumadditions:adaminite_jar.2": "铿金非常独特！我认为这个罐子可以容纳 2000 点源质，这使得它内部空间的源质十分稠密。",
        "research_stage.thaumadditions:adaminite_jar.3": "铿金非常独特！我认为这个罐子可以容纳 2000 点源质，这使得它内部空间的源质十分稠密。我听到一个叫泽尔西伦的人的声音，他是其中一位创世者，曾创造了这个世界。他轻声低语道：“这个罐子密度太大了，也许在某些特定的情况下会不稳定。我不认为把它完全装满源质是一个好主意...”。我从他的话语中也听出他非常惊讶于我所完成的这一艰难的挑战。",
        "research_stage.thaumadditions:mithminite_jar.1": "既然已我知晓了用秘银和一些水银可能可以觉醒铿金，我只需知道我能否负担得起这些秘金源质罐子。",
        "modifier.moretcon.corroding.name": "氧化",
        "modifier.gritty.name": "残痕",
        "modifier.fracture.name": "碎灭",
        "modifier.splinters.name": "断裂",
        "modifier.mutate.name": "突变",
        "modifier.mutate.desc": "似乎有什么在变化？",
        "modifier.tconevo.opportunist.name": "机会主义",
        "material.prometheum.name": "普罗姆",
        "tile.prometheum_block.name": "普罗姆块",
        "tile.prometheum_ore.name": "普罗姆矿石",
        "item.prometheum_nugget.name": "普罗姆粒",
        "item.prometheum_dust.name": "普罗姆粉",
        "item.prometheum_ingot.name": "普罗姆锭",
        "fluid.tconstruct.prometheum_fluid.name": "熔融普罗姆",
        "tile.altar.name": "铸造祭坛",
        "material.duranite.name": "耐力金属",
        "tile.duranite_block.name": "耐力金属块",
        "tile.duranite_ore.name": "耐力金属矿石",
        "item.duranite_nugget.name": "耐力金属粒",
        "item.duranite_dust.name": "耐力金属粉",
        "item.duranite_ingot.name": "耐力金属锭",
        "fluid.tconstruct.duranite_fluid.name": "熔融耐力金属",
        "material.niob.name": "尼博",
        "tile.niob_block.name": "尼博块",
        "item.niob_nugget.name": "尼博粒",
        "item.niob_dust.name": "尼博粉",
        "item.niob_ingot.name": "尼博锭",
        "fluid.tconstruct.niob_fluid.name": "熔融尼博",
        "jaopca.entry.Ambrosium": "神能晶",
        "modifier.curvature.name": "曲度",
        "tile.mist.niobium_ore": "铌矿石",
        "tile.mist.gold_ore": "朦胧金矿石",
        "tile.mist.iron_ore": "朦胧铁矿石",
        "tile.mist.sulfur_ore": "朦胧硫磺矿石",
        "tile.mist.saltpeter_ore": "朦胧硝石矿石",
        "tile.mist.r_tree_trunk": "橡胶树原木",
        "tile.mist.r_tree_leaves": "橡胶树树叶",
        "thaumicaugmentation.text.entered_void": "你拜访了无尽的虚空。",
        "thaumicaugmentation.text.mountain": "你拜访了一座高山。",
        "thaumicaugmentation.text.desert": "你拜访了一片荒漠。",
        "thaumicaugmentation.text.ocean": "你拜访了一片大海。",
        "thaumicaugmentation.text.forest": "你拜访了一片森林。",
        "thaumicaugmentation.text.impetus_damage": "你感受到了冲力带来的震撼。",
        "thaumicaugmentation.text.long_time_in_water": "你逐渐地适应了深水的压力。",
        "thaumicaugmentation.text.entered_spire": "你发现了%s。",
        "thaumicaugmentation.text.boss_room_spire": "你发现了尖塔的核心。",
        "death.attack.cinderSpark": "%s被%s的火球烧成了灰烬。",
        "botania_tweaks.entrodupe.nicetry": "TNT复制机？给爷爪巴。爷不吃这套。",
        "item.withered_nether_star.name": "暗黑下界之星",
        "fluid.fusion_matrix": "熔融聚合矩阵",
        "fluid.insanium": "熔融究极精华",
        "jaopca.entry.Infernium": "永燃",
        "jaopca.entry.Titanium": "钛",
        "jaopca.entry.LiquifiedCoralium": "精炼珊瑚",
        "fluid.cryonium": "熔融极寒",
        "jaopca.entry.Cryonium": "极寒",
        "jaopca.entry.Experience": "知识精华",
        "fluid.ethaxium": "熔融伊桑斯",
        "jaopca.entry.Cytosinite": "胞嘧",
        "jaopca.entry.Umbrium": "影素",
        "jaopca.entry.Hephaestite": "赫菲斯辛",
        "jaopca.entry.Scarlite": "绯红宝石",
        "jaopca.entry.Chromium": "铬",
        "jaopca.entry.Aqualite": "水华",
        "fluid.mithrillium": "熔融秘银",
        "fluid.adaminite": "熔融铿金",
        "fluid.mithminite": "熔融秘金",
        "fluid.ravaging": "毁灭流质",
        "fluid.gaia": "熔融盖亚魂锭",
        "fluid.terra_alloy": "熔融大地合金",
        "fluid.cosmilite": "寰宇超流体",
        "fluid.astral_metal": "星辰涌流",
        "fluid.orichalcos": "熔融奥利哈刚",
        "fluid.netherite": "熔融下界合金",
        "fluid.ancient_debris": "熔融远古残骸",
        "fluid.scorched": "熔融高炉砖",
        "fluid.organic_fluid": "有机液",
        "fluid.poison": "毒液",
        "fluid.modularium": "熔融模块化合金",
        "fluid.meteor": "熔融陨星",
        "fluid.stainless_steel": "熔融不锈钢",
        "fluid.protonium": "极密质子流体",
        "fluid.electronium": "粘性电子流质",
        "fluid.crimsonite": "猩红浆液",
        "fluid.manganese_steel": "熔融锰钢",
        "fluid.durasteel": "熔融耐钢",
        "fluid.aeonsteel": "熔融恒钢",
        "fluid.chromasteel": "熔融炫钢",
        "fluid.spectre": "灵魂之泉",
        "fluid.gaiasteel": "熔融盖亚钢",
        "fluid.blackiron": "熔融黑铁",
        "fluid.heavenite": "熔融穹金",
        "fluid.ghostite": "熔融鬼金",
        "fluid.waringlium": "熔融瓦伦格尔",
        "fluid.tierite": "熔融缠绕合金",
        "fluid.cheatieum": "熔融诡术合金",
        "fluid.idiessite": "熔融伊迪斯",
        "fluid.cthughate": "燋燎之火焰",
        "fluid.ranglium": "熔融峦金",
        "fluid.godiarite": "熔融天佑合金",
        "fluid.rainite": "熔融暴雨合金",
        "fluid.panloeseum": "熔融潘洛斯",
        "fluid.husturite": "无名之疾风",
        "fluid.fallenium": "熔融落金",
        "fluid.phoenixite": "熔融凤凰合金",
        "fluid.depthite": "熔融深邃合金",
        "fluid.lovaquite": "熔融洛瓦克",
        "fluid.rangolarite": "熔融朗格拉",
        "fluid.clearite": "熔融晴天合金",
        "fluid.wefenium": "熔融尖晶",
        "fluid.errorite": "熔融错误合金",
        "fluid.numbereum": "熔融数字合金",
        "fluid.treasurite": "熔融宝金",
        "fluid.leadite": "熔融导金",
        "fluid.martisite": "熔融战神合金",
        "fluid.flashite": "熔融闪金",
        "fluid.overlaite": "熔融叠金",
        "fluid.rupee": "熔融卢比",
        "fluid.realmite": "熔融诺米特",
        "fluid.arlemite": "熔融阿勒米特",
        "fluid.shadow_bar": "熔融阴影",
        "fluid.hellstone": "熔融罪恶",
        "fluid.lava_solid": "熔融固态岩浆",
        "fluid.aquatic": "熔融海洋结晶",
        "fluid.balancite": "熔融守恒合金",
        "fluid.glowing_signalum": "熔融荧光信素",
        "fluid.fallen_metal": "堕落聚合物",
        "fluid.relifed_metal": "重生聚合物",
        "fluid.stormy_metal": "风暴解构质",
        "fluid.ordered_metal": "秩序超流质",
        "fluid.finallium": "终焉灵体液",
        "fluid.eden": "熔融伊甸",
        "fluid.wildwood": "熔融原始",
        "fluid.apalachia": "熔融阿帕拉契亚",
        "fluid.skythern": "熔融冰刺",
        "fluid.mortum": "熔融黑金",
        "fluid.twilight_crystal": "熔融暮光结晶",
        "fluid.hellcrust":"熔融焦岩",
        "fluid.umbra":"熔融本影",
        "fluid.crystalline":"熔融月凝晶",
        "fluid.aurorianite":"熔融极光",
        "fluid.niobium":"熔融铌",
        "fluid.horizonite":"熔融炎铁",
        "fluid.falsite":"熔融伪匿",
        "fluid.ventium":"熔融风腾",
        "fluid.apocalypsium": "熔融天启",
        "fluid.sanite": "熔融灵神钢",
        "fluid.harcadium": "熔融末晶",
        "fluid.void_essence": "熔融虚空精华",
        "fluid.adamantium": "熔融艾德曼合金",
        "fluid.hellite": "熔融炼狱金属",
        "fluid.blackhole_alloy": "熔融黑洞合金",
        "fluid.creative_alloy": "熔融创世合金",
        "fluid.ruthenium": "熔融钌",
        "fluid.rhodium": "熔融铑",
        "fluid.porpezite": "熔融钯金",
        "fluid.raisium": "熔融扬升合金",
        "fluid.astronicium": "熔融太空合金",
        "fluid.compressite": "熔融极密合金",
        "fluid.dullium": "熔融沉黯",
        "fluid.daynight": "熔融昼夜合金",
        "fluid.mythsteel": "熔融神话钢",
        "fluid.cthulhurite": "深海之呼吸",
        "fluid.elfsteel": "熔融精灵钢",
        "fluid.chillinium": "熔融寒心铁",
        "fluid.iciricium": "熔融冰纹金",
        "fluid.moltenium": "熔融炎熔晶",
        "fluid.typhoonite": "熔融飓风合金",
        "fluid.thermallite": "极致炽热流体",
        "fluid.photonium": "光子纠缠流质",
        "fluid.mercury": "液汞",
        "fluid.enderiron": "熔融末影镀层铁",
        "fluid.enderironex": "熔融增强末影",
        "fluid.crystaltine": "稳定水晶流体",
        "fluid.azathothium": "痴愚之狂乱",
        "fluid.nyarlathotepium": "伏行之混沌",
        "fluid.yogsothothium": "归一之时空",
        "fluid.shubniggurathium": "孕育之黑暗",
        "fluid.rubidium": "熔融铷",
        "fluid.caesium": "熔融铯",
        "fluid.francium": "熔融钫",
        "fluid.zodiacite": "星灵拟态流质",
        "fluid.pe": "液体位能",
        "fluid.nasalum": "熔融星空",
        "fluid.lunarine": "熔融月华",
        "fluid.wigthium": "阴魂浆液",
        "fluid.darkest": "至暗浆液",
        "fluid.murderite": "血渊浆液",
        "fluid.ghost_metal": "熔融恶灵金属",
        "fluid.impetusite": "熔融元动金属",
        "fluid.eldritch_steel": "熔融邪术钢",
        "fluid.corruptium": "熔融腐化金属",
        "fluid.cursium": "熔融咒缚",
        "fluid.botanical": "熔融植物魂",
        "fluid.botanical_awakened": "熔融觉醒植物魂",
        "fluid.rosium": "熔融血玫瑰",
        "fluid.chrysanthemium": "熔融金雏菊",
        "fluid.dandelionium": "熔融蒲公英",
        "fluid.myosotisium": "熔融勿忘我",
        "fluid.begonium": "熔融秋海棠",
        "fluid.carnationium": "熔融康乃馨",
        "fluid.star_alloy": "共晶星链物质",
        "fluid.resonant_debris": "熔融共鸣残骸",
        "fluid.enderite": "熔融末影合金",
        "fluid.frostburn_metal": "霜炙化合物",
        "fluid.eucite": "熔融桉金",
        "fluid.corbite": "熔融尘金",
        "fluid.disaster_metal": "天灾共聚物",
        "fluid.scientificite": "科幻悬浊液",
        "fluid.abyssine": "深渊污浊流质",
        "fluid.wolframium": "熔融钨",
        "fluid.phosphorus": "磷蒸气",
        "fluid.clock_alloy": "熔融时钟合金",
        "fluid.twilit_alloy": "熔融黄昏合金",
        "fluid.mist_alloy": "熔融迷踪合金",
        "fluid.sharpen_alloy": "熔融锐化合金",
        "fluid.killer_alloy": "熔融杀戮合金",
        "fluid.curse_alloy": "熔融灾祸合金",
        "fluid.legendite": "熔融荣耀合金",
        "fluid.holysteel": "熔融神圣钢",
        "fluid.earth": "熔融大地",
        "fluid.aurune": "熔融灵蕴金属",
        "fluid.sorrowium": "殇魂流质",
        "fluid.undead": "不死流质",
        "fluid.darkice": "灼热黑冰",
        "fluid.calcium": "熔融钙",
        "fluid.strontium": "熔融锶",
        "fluid.barium": "熔融钡",
        "fluid.radium": "熔融镭",
        "fluid.plutonium": "熔融钚",
        "fluid.endusium": "熔融聚影铁",
        "fluid.holium": "熔融圣金",
        "fluid.apollonium": "熔融太阳神",
        "fluid.uracilite": "熔融尿嘧",
        "fluid.germanium": "熔融锗",
        "fluid.silicon": "熔融硅",
        "fluid.carbon": "熔融碳",
        "fluid.flamium": "熔融炎心铁",
        "fluid.eugardite": "熔融神光合金",
        "fluid.neptunium": "熔融镎",
        "fluid.bismuth": "熔融铋",
        "fluid.gravity_debris": "熔融重力残骸",
        "fluid.aetherite": "熔融天境合金",
        "fluid.flux": "拟态通量流质",
        "fluid.unshapable_liquid": "不定形流质",
        "fluid.pruified_liquid": "纯净流质",
        "fluid.pruified": "熔融纯净",
        "fluid.endest_steel": "熔融终影钢",
        "fluid.fracturite": "熔融解构金属",
        //化工相关液体
        "fluid.liquid_air": "液态空气",
        "fluid.hydrochloric_acid": "盐酸",
        "fluid.nitric_acid": "硝酸",
        "fluid.bromine": "液溴",
        "fluid.bromine_gas": "溴蒸气",
        "fluid.rich_brine": "富集盐水",
        "fluid.poor_brine": "乏盐水",
        "fluid.halogen_brine": "卤水",
        "fluid.iodine_solution": "碘水",
        "fluid.carbon_tetrachloride": "四氯化碳",
        "fluid.trichloromethane": "三氯甲烷",
        "fluid.dichloromethane": "二氯甲烷",
        "fluid.chloromethane": "氯甲烷",
        "fluid.methane": "甲烷",
        "fluid.ethylene": "乙炔",
        "fluid.mixed_hydrocarbon": "混合烃",
        "fluid.hydrogen_fluoride": "氟化氢",
        "fluid.iodine_carbon_tetrachloride_solution": "碘-四氯化碳溶液",
        "fluid.nitrogen_oxide": "一氧化氮",
        "fluid.nitrogen_dioxide": "二氧化氮",
        "fluid.hydrogen_sulfide": "硫化氢",
        "fluid.chloroplatinic_acid_solution": "氯铂酸",
        "fluid.sodium_chloroplatinate_solution": "氯铂酸钠溶液",
        "fluid.calcium_chloride_solution": "氯化钙溶液",
        "fluid.calcium_hydroxide_solution": "氢氧化钙溶液",
        "fluid.strontium_chloride_solution": "氯化锶溶液",
        "fluid.strontium_sulfide_solution": "硫化锶溶液",
        "fluid.barium_chloride_solution": "氯化钡溶液",
        "fluid.barium_sulfide_solution": "硫化钡溶液",
        "fluid.sodium_chloride": "熔融氯化钠",
        "fluid.potassium_chloride": "熔融氯化钾",
        "fluid.rubidium_chloride": "熔融氯化铷",
        "fluid.cesium_chloride": "熔融氯化铯",
        "fluid.platinum_chloride": "熔融氯化铂",
        "fluid.calcium_chloride": "熔融氯化钙",
        "fluid.strontium_chloride": "熔融氯化锶",
        "fluid.barium_chloride": "熔融氯化钡",
        "fluid.liquid_hydrogen": "液氢",
        "fluid.liquid_nitrogen": "液氮",
        "fluid.liquid_oxygen": "液氧",
        "fluid.liquid_fluorine": "液氟",
        "fluid.liquid_neon": "液氖",
        "fluid.liquid_chlorine": "液氯",
        "fluid.liquid_argon": "液氩",
        "fluid.liquid_krypton": "液氪",
        "fluid.liquid_xenon": "液氙",
        "fluid.liquid_radon": "液氡",
        "fluid.oxygen": "氧",
        "fluid.nitrogen": "氮",
        "fluid.neon": "氖",
        "fluid.argon": "氩",
        "fluid.krypton": "氪",
        "fluid.xenon": "氙",
        "fluid.radon": "氡",
        "fluid.hecryo_liquid": "§c凛冰-液氦溶液",
        "fluid.liquidgoldenamber": "熔融金琥珀",
        //
        "fluid.liquidlegend": "荣耀浆液",
        //
        "jaopca.entry.Fracturite": "解构金属",
        "jaopca.entry.Barite": "重晶石",
        "jaopca.entry.Zodiacite": "星灵",
        "jaopca.entry.Enderiron": "末影镀层铁",
        "jaopca.entry.Enderironex": "增强末影",
        "jaopca.entry.Cerulean": "晶蓝",
        "jaopca.entry.Dilithium": "双锂",
        "jaopca.entry.Asgardium": "神金",
        "jaopca.entry.Shadowium": "暗影",
        "jaopca.entry.Aeroite": "云浮",
        "jaopca.entry.AncientDebris": "远古残骸",
        "jaopca.entry.Meteor": "陨星",
        "jaopca.entry.Manganese": "锰",
        "jaopca.entry.Aetherium": "以太",
        "jaopca.entry.Canopium": "苍穹",
        "jaopca.entry.Mistium": "缥缈",
        "jaopca.entry.Thyminite": "胸腺嘧",
        "jaopca.entry.Lavarite": "熔浆",
        "jaopca.entry.Plasmarite": "等离子",
        "jaopca.entry.Bnightium": "夜明",
        "jaopca.entry.Guaninite": "鸟嘌呤晶",
        "jaopca.entry.Snowingium": "碎雪",
        "jaopca.entry.Freezite": "封晶",
        "jaopca.entry.Oceanium": "浩瀚",
        "jaopca.entry.Adeninite": "腺嘌呤晶",
        "jaopca.entry.Harcadium": "末晶",
        "jaopca.entry.VoidEssence": "虚空精华",
        "jaopca.entry.Adamantium": "艾德曼合金",
        "jaopca.entry.Abyssalnite": "渊素",
        "jaopca.entry.Swinium": "辉铜",
        "jaopca.entry.Manarium": "蓝焰金属",
        "jaopca.entry.Lighteum": "明铁",
        "jaopca.entry.Stripium": "纹金",
        "jaopca.entry.Dimesium": "维度金属",
        "jaopca.entry.Cloudite": "云银",
        "jaopca.entry.Mangisite": "曼切斯特",
        "jaopca.entry.Soilium": "索里姆",
        "jaopca.entry.Vanadium": "钒",
        "jaopca.entry.Oneo": "壹素",
        "jaopca.entry.Togrium": "托格姆",
        "jaopca.entry.Yoggleseum": "约格斯",
        "jaopca.entry.Breakium": "断金",
        "jaopca.entry.Molybdenum": "钼",
        "jaopca.entry.Gallium": "镓",
        "jaopca.entry.Dawnium": "陨灵金",
        "jaopca.entry.Fenzium": "丰金",
        "jaopca.entry.Xenidium": "玄银",
        "jaopca.entry.Sissidium": "希斯蒂姆",
        "jaopca.entry.Ttwo": "贰素",
        "jaopca.entry.Losessium": "残念金属",
        "jaopca.entry.Indium": "铟",
        "jaopca.entry.Technetium": "锝",
        "jaopca.entry.Antimony": "锑",
        "jaopca.entry.Rubidium": "铷",
        "jaopca.entry.Rapesesium": "拉普西斯",
        "jaopca.entry.Circlium": "环金",
        "jaopca.entry.Caesium": "铯",
        "jaopca.entry.Francium": "钫",
        "jaopca.entry.Fierymetal": "炽铁",
        "jaopca.entry.Knightmetal": "骑士金属",
        "jaopca.entry.Arlemite": "阿勒米特",
        "jaopca.entry.Rupee": "卢比",
        "jaopca.entry.Realmite": "诺米特",
        "jaopca.entry.LavaSolid": "熔岩",
        "jaopca.entry.Durasteel": "耐钢",
        "jaopca.entry.Aeonsteel": "恒钢",
        "jaopca.entry.Chromasteel": "炫钢",
        "jaopca.entry.Cosmilite": "寰宇",
        "jaopca.entry.Manasteel": "魔力钢",
        "jaopca.entry.ManaDiamond": "魔力钻石",
        "jaopca.entry.ManaLapis": "魔力青金石",
        "jaopca.entry.ManaQuartz": "魔力石英",
        "jaopca.entry.Elementium": "源质钢",
        "jaopca.entry.Terrasteel": "泰拉钢",
        "jaopca.entry.Gaiasteel": "盖亚钢",
        "jaopca.entry.Orichalcos": "奥利哈刚",
        "jaopca.entry.Osgloglas": "锇荧黑曜合金",
        "jaopca.entry.Alumite": "耐酸铝",
        "jaopca.entry.Osmiridium": "铱锇合金",
        "jaopca.entry.Mirion": "蕴魔结晶",
        "jaopca.entry.Sodium": "钠",
        "jaopca.entry.Potassium": "钾",
        "jaopca.entry.Iciricium": "冰纹金",
        "jaopca.entry.Elfsteel": "精灵钢",
        "jaopca.entry.Chillinium": "寒心铁",
        "jaopca.entry.Aurorianite": "极光",
        "jaopca.entry.Crystalline": "月凝晶",
        "jaopca.entry.Umbra": "本影",
        "jaopca.entry.StainlessSteel": "不锈钢",
        "jaopca.entry.Niobium": "铌",
        "jaopca.entry.Manyullyn": "玛玉灵",
        "jaopca.entry.ShadowBar": "阴影",
        "jaopca.entry.Eden": "伊甸",
        "jaopca.entry.Wildwood": "原始",
        "jaopca.entry.Apalachia": "阿帕拉契亚",
        "jaopca.entry.Skythern": "冰刺",
        "jaopca.entry.Mortum": "黑金",
        "jaopca.entry.Prudentium": "初级精华",
        "jaopca.entry.Intermedium": "中级精华",
        "jaopca.entry.Superium": "高级精华",
        "jaopca.entry.Supremium": "终极精华",
        "jaopca.entry.Insanium": "究极精华",
        "jaopca.entry.Witherium": "凋灵",
        "jaopca.entry.Dreadium": "惧质",
        "jaopca.entry.Moltendreadium": "惧质",
        "jaopca.entry.Ethaxium": "伊桑斯",
        "jaopca.entry.Sanite": "灵神钢",
        "jaopca.entry.Cthulhurite": "克苏鲁",
        "jaopca.entry.FusionMatrix": "聚合矩阵",
        "jaopca.entry.DraconiumAwakened": "觉醒龙",
        "jaopca.entry.Crimsonite": "猩红",
        "jaopca.entry.Mythsteel": "神话钢",
        "jaopca.entry.Falsite": "伪匿",
        "jaopca.entry.Ventium": "风腾",
        "jaopca.entry.Horizonite": "炎铁",
        "jaopca.entry.Cestium": "塞斯提",
        "jaopca.entry.Rubium": "深红金属",
        "jaopca.entry.Fraxinium": "弗拉克",
        "jaopca.entry.Dullium": "沉黯",
        "jaopca.entry.Oraclium": "神谕钢",
        "jaopca.entry.Polarium": "勾陈",
        "jaopca.entry.Altairium": "河鼓",
        "jaopca.entry.Hothium": "霍斯",
        "jaopca.entry.Halleium": "哈雷",
        "jaopca.entry.Tonium": "钝金",
        "jaopca.entry.Stellarium": "恒星金属",
        "jaopca.entry.Steamium": "气钢",
        "jaopca.entry.Imitatium": "拟素",
        "jaopca.entry.Magiga": "伽钢",
        "jaopca.entry.Tanatonium": "塔拉特妮姆",
        "jaopca.entry.SilverImmersed": "沉银",
        "jaopca.entry.Raisium": "扬升合金",
        "jaopca.entry.Astronicium": "太空合金",
        "jaopca.entry.Compressite": "极密合金",
        "jaopca.entry.Ruthenium": "钌",
        "jaopca.entry.Rhodium": "铑",
        "jaopca.entry.Porpezite": "钯金",
        "jaopca.entry.Lunium": "錀",
        "jaopca.entry.Shadium": "阴祟",
        "jaopca.entry.Bloodcrust": "狱石",
        "jaopca.entry.Hellite": "炼狱金属",
        "jaopca.entry.BlackholeAlloy": "黑洞合金",
        "jaopca.entry.CreativeAlloy": "创世合金",
        "jaopca.entry.Eucite": "桉金",
        "jaopca.entry.Corbite": "尘金",
        "jaopca.entry.Decurrium": "深流钢",
        "jaopca.entry.Chloroplast": "叶绿",
        "jaopca.entry.Irisia": "艾瑞西亚",
        "jaopca.entry.Celestium": "天青石",
        "jaopca.entry.Korite": "蓝曜",
        "jaopca.entry.Mekyum": "紫云母",
        "jaopca.entry.Storon": "天金",
        "jaopca.entry.Flairium": "暗金",
        "jaopca.entry.Orbadite": "磷铁",
        "jaopca.entry.Des": "靛钢",
        "jaopca.entry.Finallium": "§f终§7焉§8",
        "jaopca.entry.Heavenite": "穹金",
        "jaopca.entry.Ghostite": "鬼金",
        "jaopca.entry.Waringlium": "瓦伦格尔",
        "jaopca.entry.Tierite": "缠绕合金",
        "jaopca.entry.Cheatieum": "诡术合金",
        "jaopca.entry.Idiessite": "伊迪斯",
        "jaopca.entry.Moltenium": "炎熔晶",
        "jaopca.entry.Ranglium": "峦金",
        "jaopca.entry.Godiarite": "天佑合金",
        "jaopca.entry.Rainite": "暴雨合金",
        "jaopca.entry.Panloeseum": "潘洛斯",
        "jaopca.entry.Typhoonite": "飓风合金",
        "jaopca.entry.Fallenium": "落金",
        "jaopca.entry.Phoenixite": "凤凰合金",
        "jaopca.entry.Depthite": "深邃合金",
        "jaopca.entry.Lovaquite": "洛瓦克",
        "jaopca.entry.Rangolarite": "朗格拉",
        "jaopca.entry.Clearite": "晴天合金",
        "jaopca.entry.Wefenium": "尖晶",
        "jaopca.entry.Errorite": "错误合金",
        "jaopca.entry.Numbereum": "数字合金",
        "jaopca.entry.Treasurite": "宝金",
        "jaopca.entry.Leadite": "导金",
        "jaopca.entry.Martisite": "战神合金",
        "jaopca.entry.Flashite": "闪金",
        "jaopca.entry.Overlaite": "叠金",
        "jaopca.entry.Scientificite": "科幻",
        "jaopca.entry.Protonium": "质子",
        "jaopca.entry.Neutronium": "中子素",
        "jaopca.entry.Electronium": "电子",
        "jaopca.entry.Legendite": "荣耀合金",
        "jaopca.entry.Blackiron": "黑铁",
        "jaopca.entry.Thermallite": "热极金属",
        "jaopca.entry.Twilit": "暮晶",
        "jaopca.entry.Eugardite": "神光合金",
        "jaopca.entry.Photonium": "光子",
        "jaopca.entry.Soularium": "魂金",
        "jaopca.entry.Solita": "坚金",
        "jaopca.entry.Gaia": "盖亚魂",
        "jaopca.entry.Mercury": "汞",
        "jaopca.entry.Silicon": "硅",
        "jaopca.entry.Carbon": "碳",
        "jaopca.entry.Mana": "固态魔力",
        "jaopca.entry.Enderiron": "末影镀层铁",
        "jaopca.entry.Enderironex": "增强末影",
        "jaopca.entry.Crystaltine": "晶素",
        "jaopca.entry.Azathothium": "阿撒托斯",
        "jaopca.entry.Nyarlathotepium": "奈亚拉托提普",
        "jaopca.entry.Yogsothothium": "犹格·索托斯",
        "jaopca.entry.Shubniggurathium": "莎布·尼古拉丝",
        "jaopca.entry.Nasalum": "星空",
        "jaopca.entry.Lunarine": "月华",
        "jaopca.entry.AstralMetal": "星辰",
        "jaopca.entry.Flamium": "炎心铁",
        "jaopca.entry.Wigthium": "阴魂",
        "jaopca.entry.Darkest": "至暗",
        "jaopca.entry.Murderite": "血渊",
        "jaopca.entry.Cthughate": "克图格亚",
        "jaopca.entry.Husturite": "哈斯塔",
        "jaopca.entry.GhostMetal": "恶灵",
        "jaopca.entry.Betwnite": "交错钢",
        "jaopca.entry.Pe": "固化位能",
        "jaopca.entry.Abyssine": "渊晶",
        "jaopca.entry.Impetusite": "元动金属",
        "jaopca.entry.EldritchSteel": "邪术钢",
        "jaopca.entry.Corruptium": "腐化金属",
        "jaopca.entry.Cursium": "咒缚",
        "jaopca.entry.Botanical": "植物魂",
        "jaopca.entry.Rosium": "血玫瑰",
        "jaopca.entry.Chrysanthemium": "金雏菊",
        "jaopca.entry.Dandelionium": "蒲公英",
        "jaopca.entry.Myosotisium": "勿忘我",
        "jaopca.entry.Begonium": "秋海棠",
        "jaopca.entry.Carnationium": "康乃馨",
        "jaopca.entry.BotanicalAwakened": "觉醒植物魂",
        "jaopca.entry.LifeCrystal": "生命水晶",
        "jaopca.entry.Scabyst": "痂壳晶",
        "jaopca.entry.Daynight": "昼夜合金",
        "jaopca.entry.StarAlloy": "星链合金",
        "jaopca.entry.Tiberium": "泰伯利亚",
        "jaopca.entry.Aurorium": "极光金属",
        "jaopca.entry.Prometheum": "普罗姆",
        "jaopca.entry.Duranite": "杜兰特",
        "jaopca.entry.Valyrium": "瓦雷利亚",
        "jaopca.entry.Vibranium": "振金",
        "jaopca.entry.Karmesine": "绯红铁",
        "jaopca.entry.Ovium": "欧维姆",
        "jaopca.entry.Jauxum": "若氏铁",
        "jaopca.entry.Terrax": "地母",
        "jaopca.entry.Uru": "雾金",
        "jaopca.entry.Osram": "熔晶",
        "jaopca.entry.Abyssum": "深渊金属",
        "jaopca.entry.Eezo": "零素",
        "jaopca.entry.Triberium": "泰伯利安",
        "jaopca.entry.Fractum": "碎金",
        "jaopca.entry.Violium": "瑟蓝",
        "jaopca.entry.Proxii": "普罗克希",
        "jaopca.entry.Tritonite": "漩金",
        "jaopca.entry.Ignitz": "焰晶",
        "jaopca.entry.Imperomite": "帝金",
        "jaopca.entry.Solarium": "阳光合金",
        "jaopca.entry.Nihilite": "虚金",
        "jaopca.entry.Adamant": "精金",
        "jaopca.entry.Dyonite": "烈金",
        "jaopca.entry.Nucleum": "辐光合金",
        "jaopca.entry.Lumix": "流光合金",
        "jaopca.entry.Seismum": "地动合金",
        "jaopca.entry.Astrium": "曜金",
        "jaopca.entry.Niob": "尼博",
        "jaopca.entry.Yrdeen": "原金",
        "jaopca.entry.Iox": "离金",
        "jaopca.entry.Meteorite": "陨铁",
        "jaopca.entry.Obsidiorite": "黑陨铁",
        "jaopca.entry.Chocolate": "巧克力",
        "jaopca.entry.CocoaButter": "可可脂",
        "jaopca.entry.DarkChocolate": "黑巧克力",
        "jaopca.entry.Extreme": "极限合金",
        "jaopca.entry.HSLASteel": "高强度低合金钢",
        "jaopca.entry.Kianate": "律者精华",
        "jaopca.entry.LeadPlatinum": "铅铂合金",
        "jaopca.entry.Marshmallow": "棉花糖",
        "jaopca.entry.PrimordialExtended": "增强元金",
        "jaopca.entry.Pruified": "纯净",
        "jaopca.entry.PyrolyticCarbon": "热解碳",
        "jaopca.entry.RadiationMatrix": "放射矩阵",
        "jaopca.entry.Radium": "镭",
        "jaopca.entry.Ravaging": "毁灭",
        "jaopca.entry.Rhenium": "铼",
        "jaopca.entry.Scandium": "钪",
        "jaopca.entry.Shibuichi": "胧银合金",
        "jaopca.entry.SiCSiCCMC": "碳化硅复合材料",
        "jaopca.entry.SiliconCarbide": "碳化硅",
        "jaopca.entry.Thermoconducting": "热引合金",
        "jaopca.entry.TinSilver": "锡银合金",
        "jaopca.entry.TwilightCrystal": "暮光结晶",
        "jaopca.entry.Unstable": "不稳定金属",
        "jaopca.entry.UnsweetenedChocolate": "无糖巧克力",
        "jaopca.entry.ZirconiumMolybdenum": "锆钼合金",
        "jaopca.entry.Balancite": "守恒合金",
        "jaopca.entry.IceDragonsteel": "龙霜钢",
        "jaopca.entry.FireDragonsteel": "龙炎钢",
        "jaopca.entry.AuraIron": "灌注铁",
        "jaopca.entry.Sky": "天空",
        "jaopca.entry.Holium": "圣金",
        "jaopca.entry.Undead": "不死",
        "jaopca.entry.Sorrowium": "殇魂",
        "jaopca.entry.Netherite": "下界合金",
        "jaopca.entry.Enderite": "末影合金",
        "jaopca.entry.ClockAlloy": "时钟合金",
        "jaopca.entry.TwilitAlloy": "黄昏合金",
        "jaopca.entry.MistAlloy" : "迷踪合金",
        "jaopca.entry.SharpenAlloy" : "锐化合金",
        "jaopca.entry.KillerAlloy" : "杀戮合金",
        "jaopca.entry.CurseAlloy" : "灾祸合金",
        "jaopca.entry.Octine" : "炽炎铁",
        "jaopca.entry.Syrmorite" : "赛摩铜",
        "jaopca.entry.Valonite" : "法罗钠",
        "jaopca.entry.FrostburnMetal" : "霜炙金属",
        "jaopca.entry.CrimsonMiddleGem" : "猩红元素宝石",
        "jaopca.entry.GreenMiddleGem" : "翠绿元素宝石",
        "jaopca.entry.AquaMiddleGem" : "水蓝元素宝石",
        "jaopca.entry.Adaminite" : "铿金",
        "jaopca.entry.BlackIron" : "黑铁",
        "jaopca.entry.BoundMetal" : "束缚金属",
        "jaopca.entry.ChaoticMetal" : "混沌金属",
        "jaopca.entry.ConstructionAlloy" : "铁合金",
        "jaopca.entry.CrudeSteel" : "粗钢",
        "jaopca.entry.CrystallineAlloy" : "晶化合金",
        "jaopca.entry.CrystallinePinkSlime" : "晶化粉红粘液",
        "jaopca.entry.CrystalMatrix" : "水晶矩阵",
        "jaopca.entry.Dawnstone" : "黎明石",
        "jaopca.entry.DraconicAlloy" : "神龙金属",
        "jaopca.entry.EnergeticSilver" : "充能银",
        "jaopca.entry.Hafnium" : "铪",
        "jaopca.entry.GelidEnderium" : "极寒末影",
        "jaopca.entry.Darkice" : "黑冰",
        "jaopca.entry.Mithminite" : "秘金",
        "jaopca.entry.Primordial" : "元金",
        "jaopca.entry.Mithrillium" : "秘银",
        "jaopca.entry.Mithril" : "蕴魔秘银",
        "jaopca.entry.Uracilite" : "尿嘧",        
        "jaopca.entry.Endusium" : "聚影铁",
        "jaopca.entry.Fluorite" : "氟石",
        "jaopca.entry.QuartzBlack" : "焦黑石英",
        "jaopca.entry.Basalt" : "玄武岩",
        "jaopca.entry.Ichorium" : "灵宝",
        "jaopca.entry.Infinity" : "§c无尽",
        "jaopca.entry.ManganeseSteel" : "锰钢",
        "jaopca.entry.MelodicAlloy" : "旋律合金",
        "jaopca.entry.OrichalcosReversed" : "反相奥利哈刚",
        "jaopca.entry.RefinedGlowstone" : "强化荧石",
        "jaopca.entry.RefinedObsidian" : "强化黑曜石",
        "jaopca.entry.TerraAlloy" : "大地合金",
        "jaopca.entry.StellarAlloy" : "恒星合金",
        "jaopca.entry.Ultimate" : "终极",
        "jaopca.entry.Valkyrie" : "女武神金属",
        "jaopca.entry.VividAlloy" : "生动合金",
        "jaopca.entry.Zircaloy" : "锆锡合金",
        "jaopca.entry.Calcium" : "钙",
        "jaopca.entry.Strontium" : "锶",
        "jaopca.entry.Barium" : "钡",
        "jaopca.entry.Apollonium" : "太阳神",
        "jaopca.entry.Arimite": "冠晶",
        "jaopca.entry.Earth": "大地",
        "jaopca.entry.Holysteel": "神圣钢",
        "jaopca.entry.Aurune": "灵蕴金属",
        "jaopca.entry.Tungsten": "钨",
        "jaopca.entry.Endorium": "终末",
        "jaopca.entry.EndestSteel": "终影钢",
        "jaopca.entry.Limonite": "褐铁",
        "jaopca.entry.Rosite": "玫石",
        "jaopca.entry.Emberstone": "余烬石",
        "jaopca.entry.Ascensionite": "虚无合金",
        "jaopca.entry.BalancedMatrix": "平衡矩阵",
        "jaopca.entry.Hydrogen": "氢",
        "jaopca.entry.Helium": "氦",
        "jaopca.entry.Nitrogen": "氮",
        "jaopca.entry.Oxygen": "氧",
        "jaopca.entry.Fluorine": "氟",
        "jaopca.entry.Neon": "氖",
        "jaopca.entry.Chlorine": "氯",
        "jaopca.entry.Argon": "氩",
        "jaopca.entry.Krypton": "氪",
        "jaopca.entry.Xenon": "氙",
        "jaopca.entry.Radon": "氡",
        "jaopca.entry.Bromine": "溴",
        "jaopca.entry.Aetherite": "天境合金",
        "jaopca.entry.Flux": "§c拟态通量",
        "jaopca.entry.Ivorium": "象牙",

        "jaopca.entry.Phosphorus": "磷",
        "jaopca.entry.Germanium": "锗",
        "jaopca.entry.Arsenic": "砷",
        "jaopca.entry.Selenium": "硒",
        "jaopca.entry.Yttrium": "钇",
        "jaopca.entry.Cadmium": "镉",
        "jaopca.entry.Tellurium": "碲",
        "jaopca.entry.Iodine": "碘",
        "jaopca.entry.Lanthanum": "镧",
        "jaopca.entry.Cerium": "铈",
        "jaopca.entry.Praseodymium": "镨",
        "jaopca.entry.Neodymium": "钕",
        "jaopca.entry.Promethium": "钷",
        "jaopca.entry.Samarium": "钐",
        "jaopca.entry.Europium": "铕",
        "jaopca.entry.Gadolinium": "钆",
        "jaopca.entry.Terbium": "铽",
        "jaopca.entry.Dysprosium": "镝",
        "jaopca.entry.Holmium": "钬",
        "jaopca.entry.Erbium": "铒",
        "jaopca.entry.Thullium": "铥",
        "jaopca.entry.Ytterbium": "镱",
        "jaopca.entry.Lutetium": "镥",
        "jaopca.entry.Thallium": "铊",
        "jaopca.entry.Polonium": "钋",
        "jaopca.entry.Astatine": "§0砹",
        "jaopca.entry.Actinium": "锕",
        "jaopca.entry.Protactinium": "镤",
        "jaopca.entry.Neptunium": "镎",
        "jaopca.entry.Plutonium": "钚",
        "jaopca.entry.Americium": "镅",
        "jaopca.entry.Curium": "锔",
        "jaopca.entry.Berkelium": "锫",
        "jaopca.entry.Californium": "锎",
        "jaopca.entry.Einsteinium": "锿",
        "jaopca.entry.Fermium": "镄",
        "jaopca.entry.Mendelevium": "钔",
        "jaopca.entry.Nobelium": "锘",
        "jaopca.entry.Lawrencium": "铹",
        "jaopca.entry.Rutherfordium": "",//104 Rf
        "jaopca.entry.Dubnium": "",//105 Db
        "jaopca.entry.Seaborgium": "",//106 Sg

        "jaopca.entry.Oganesson": "鿫",//118 Og
        "jaopca.entry.DisasterMetal": "天灾金属",
        "jaopca.entry.Teakerium": "§4熔融",
        "jaopca.entry.Amthirmisium": "§4电磁",
        "jaopca.entry.Darvenium": "§4预兆",
        "jaopca.entry.Cermilium": "§4控制",
        "jaopca.entry.Pardimalium": "§4灿烂",
        "jaopca.entry.Quadroticium": "§4远古",
        "jaopca.entry.Karosium": "§4黑暗",
        "jaopca.entry.Heliosisium": "§4飘渺",
        "jaopca.entry.Arksianium": "§4神圣",
//
        "journey.boss.name.sentryheart": "§4哨兵之心",
        "jer.worldgen.averageChunk": "平均每区块方块数",
        "death.attack.curse": "%s死于腐化的诅咒。",
        "craftcheck.failure.item.input": "缺少物品输入！",
        "craftcheck.failure.item.output.space": "没有足够的空间以供输出物品！",
        "craftcheck.failure.fluid.input": "缺少流体输入！",
        "craftcheck.failure.fluid.output.space": "没有足够的空间以供输出流体！",
        "craftcheck.failure.gas.input": "缺少气体输入！",
        "craftcheck.failure.gas.output.space": "没有足够的空间以供输出气体！",
        "craftcheck.failure.energy.input": "缺少能量输入！",
        "component.missing.modularmachinery.energy.output": "没有找到能量输出仓！",
        "component.missing.modularmachinery.energy.input": "没有找到能量输入仓！",
        "component.missing.modularmachinery.fluid.output": "没有找到流体输出仓！",
        "component.missing.modularmachinery.fluid.input": "没有找到流体输入仓！",
        "component.missing.modularmachinery.gas.output": "没有找到流体输出仓以供输出气体！",
        "component.missing.modularmachinery.gas.input": "没有找到流体输入仓以供输入气体！",
        "component.missing.modularmachinery.item.output": "没有找到物品输出仓！",
        "component.missing.modularmachinery.item.input": "没有找到物品输入仓！",
        "item.aether_portal_frame.name": "一键式天境传送门",
        "modifier.tconevo.crystalline.desc": "§c§r[已禁用]§r\n该特性将不会出现在工具或盔甲上。",
        "modifier.tconevo.will_strength_armor.desc": "§o至少你不会一下子就死去……\n§r满血时，你将不会被一击杀死",
        "tconevo.info.cannot_replace": "§c无法替换该部件。\n§e拥有进化属性的工具的部件无法被替换。",
        "tconevo.info.artifact_sealed": "§c无法改动未启封的“匠心之作”！\n§e要想改动该工具，请用工具锻造台将工具和§5启封之板§e合成。",
        "text.component.animus.transposition.cleared": "移位标记已清除！",
        "item.bloodmagic.alchemic_vial.base.name": "炼金之瓶",
        "tile.bloodarsenal.slate..name": "石板砖",
        "message.touhou_little_maid.change_model.disabled": "§e皮肤切换功能已被禁止，请使用§6扭蛋机§e抽取女仆皮肤！",
        "entity.Dummy.name": "训练用假人",
        "item.bountifulbaubles.trinketAnkhCharm.name": "安赫护符",
        "item.heart_food.name": "§c心之容器 EX§r",
        "tooltip.itemstages.name.default": "§5§ka§r §d未知物品 §5§ka§r",
        "commands.publish.started": "§e已在端口§6%s§e上开启局域网游戏。 \n§7(如果需要非正版玩家登录，请在整合包根目录的config/serverGlobalConfig.properties中把online-mode后面的true改成false)",
        "betterfoliage.rendererror": "§a[更好的树叶]§f 在渲染原木方块 %s §9@ §7(§6%s§7)§r 时出错。§7（该提示一般可忽略）",
        "potion.saturation": "饱腹",
        "tile.quark:monster_box.name": "§c陷阱刷怪笼",
        "tile.monster_box.name": "§c陷阱刷怪笼",
        "mob_effect.netherex:fire_burning": "极寒之焰",
        "info.nyx.blood_moon_sleeping": "§c你无法在血色之月的阴霾下安心入睡。",
        "tile.torchmaster.mega_torch.lit.tooltip": "§e正道的光，照在了大地上！",
        "entity.quazar.name": "§9史莱姆之神§r",
        "entity.champions.cinder_spark.name": "精英怪范围伤害",
        "vanillafix.gui.failed": "获取崩溃报告链接失败，请手动发送该报告",
        "dc.message.death": "§c[死亡次数统计] §e你已经阵亡§c§l%s§r§e次。",
        "dc.message.deathAndRank": "死亡次数: %1$s排名: %2$s",
        "dc.command.leaderboard": "§a========== §e死亡排行榜 §a==========",
        "ac.ritual.abyssalite": "渊素转化",
        "ac.ritual.abyssalite.desc": "使用阴影宝石将铁矿石变成渊素矿石！",
        "reskillable.skill.reskillable.mining": "挖掘 §7[§2+攻速§7]§r",
        "reskillable.skill.reskillable.gathering": "采集 §7[§2+幸运§7]§r",
        "reskillable.skill.reskillable.attack": "攻击 §7[§2+伤害§7]§r",
        "reskillable.skill.reskillable.defense": "防御 §7[§2+盔甲§7]§r",
        "reskillable.skill.reskillable.building": "建造 §7[§2+韧性§7]§r",
        "reskillable.skill.reskillable.farming": "农耕 §7[§2+生命§7]§r",
        "reskillable.skill.reskillable.agility": "敏捷 §7[§2+移速§7]§r",
        "reskillable.skill.reskillable.magic": "魔法 §7[§2+经验§7]§r",
        "message.died": "§e%s §7逝世于 %s §9(破坏坟墓以取回物品)",
        "death.attack.outOfWorld": "实体%1$s被从埃拉西亚公共界面移除",
        "material.extrabotany:ingotorichalcos.name": "§c[已禁用]",
        "material.extrabotany:ingotshadowium.name": "§c[已禁用]",
        "memorycleaner.gc.start": "§a[内存清理] §f正在清理内存，可能会导致卡顿！\n§7(如果这造成了较长时间的卡顿，请使用我们GitHub Wiki页面推荐的JVM参数。)",
        "item.draconicadditions:chaos_heart.name": "混沌龙心",
        "tile.denseneutroncollectors:compressed_neutron_collector.name": "聚合中子素收集器",
        "tile.denseneutroncollectors:double_compressed_neutron_collector.name": "质子中子素收集器",
        "tile.denseneutroncollectors:triple_compressed_neutron_collector.name": "平衡中子素收集器",
        "container.compressed_neutron_collector": "聚合中子素收集器",
        "container.double_compressed_neutron_collector": "质子中子素收集器",
        "container.triple_compressed_neutron_collector": "平衡中子素收集器",
        "entity.WitherBossCommandBlockHelpful.name": "凋灵风暴（初始阶段）",
        "entity.WitherStormBossHelpful.name": "凋灵风暴（完全阶段）",
        "entity.WitherStormBossTentacleHelpful.name": "凋灵风暴触手",
        "entity.WitherStormBossHeadHelpful.name": "凋灵风暴头",
        "entity.WitherStormBossTentacleDevourerHelpful.name": "凋灵风暴触手",
        "greedycraft.tconstruct.material.titanium.name": "钛",
        "greedycraft.tconstruct.material.manganese.name": "锰",
        "greedycraft.tooltip.command_block": "§e该方块属于技术性方块，无法在生存模式被放置\n§e如果因意外导致方块被放在地上，可以使用命令拆除扳手右键拆除",
        "greedycraft.tooltip.odct": "§e此物品可能具有多个ID，合成可能会发生冲突\n§e可以直接放入工作台或扔在地上转化为同名物品",
        "greedycraft.tooltip.contenttweaker.modularblock": "§c如果不会搭建模块化机器，可以在整合包手册中查看",
        "greedycraft.tooltip.conductive": "导电铁粒的熔点为575K，可以使用加热器搭配微型冶炼炉熔化",
        "greedycraft.tooltip.lumps": "法球可以通过探索梦魇世界地牢和击杀梦魇BOSS获得",
        "greedycraft.tooltip.utilityworld.warnings": "§4一旦使用了传送门，\n除非你放置了指路石等传送装置，\n否则请不要破坏此传送门及返回传送门，\n否则会引起世界丢失！",
        "tile.orderland_portal.name": "秩序之地传送门",
        "tile.everheaven_portal.name": "深空之域传送门",
        "greedycraft.tooltip.modularcontroller.not_need_blueprints": "§4此机械无需制作蓝图即可工作",
    },
    en_us: {
        "modifier.mutate.name": "Mutating",
        "modifier.mutate.desc": "Looks like something is changing?",
        "death.attack.cinderSpark": "%s was burnt to ashes by %s's fireball.'",
        "botania_tweaks.entrodupe.nicetry": "Get rid of your stupid TNT duplicator, we don't do that here.",
        "fluid.fusion_matrix": "Molten Coalescence Matrix",
        "fluid.insanium": "Molten Insanium",
        "fluid.cryonium": "Molten Cryonium",
        "fluid.ethaxium": "Ethaxium Fluid",
        "fluid.mithrillium": "Molten Mithrillium",
        "fluid.adaminite": "Molten Adaminite",
        "fluid.mithminite": "Molten Mithminite",
        "fluid.ravaging": "Ravaging Fluid",
        "fluid.gaia": "Gaian Mana",
        "fluid.terra_alloy": "Molten Terra Alloy",
        "fluid.cosmilite": "Cosmilite Hyperfluid",
        "fluid.astral_metal": "Astral Pulse",
        "fluid.orichalcos": "Molten Orichalcos",
        "fluid.netherite": "Molten Netherite",
        "fluid.ancient_debris": "Molten Ancient Debris",
        "fluid.scorched": "Molten Scorched Brick",
        "fluid.organic_fluid": "Organic Fluid",
        "fluid.poison": "Liquid Poison",
        "fluid.modularium": "Molten Modularium",
        "fluid.meteor": "Molten Meteor",
        "fluid.stainless_steel": "Molten Stainless Steel",
        "fluid.protonium": "Superdense Protonium Fluid",
        "fluid.electronium": "Viscous Electronium Fluid",
        "fluid.crimsonite": "Crimsonite Juice",
        "fluid.manganese_steel": "Molten Manganese Steel",
        "fluid.durasteel": "Molten Durasteel",
        "fluid.aeonsteel": "Molten Aeonsteel",
        "fluid.chromasteel": "Molten Chromasteel",
        "fluid.spectre": "Soul Springs",
        "fluid.gaiasteel": "Molten Gaiasteel",
        "death.attack.curse": "%s died from the curse of corruption.",
        "item.aether_portal_frame.name": "The Key To Heaven",
        "modifier.tconevo.crystalline.desc": "§c§n[Disabled]§r\nThis trait will not appear on tools or armors.",
        "modifier.tconevo.will_strength_armor.desc": "§c§n[Disabled]§r\nThis trait will not appear on tools or armors.",
        "tconevo.info.cannot_replace": "§cCannot replace this part.\n§eYou cannot replace parts with the Evolving trait.",
        "tconevo.info.artifact_sealed": "§cCannot modify a sealed artifact!\n§eTo modify this tool, unseal it with a Plate of Unsealing.",
        "text.component.animus.transposition.cleared": "Transposition mark cleared!",
        "item.bloodmagic.alchemic_vial.base.name": "Alchemic Vial",
        "tile.bloodarsenal.slate..name": "Slate",
        "message.touhou_little_maid.change_model.disabled": "§eSkin switching has been turned off, use the gashapon machine to get skins.",
        "entity.Dummy.name": "Training Dummy",
        "item.heart_food.name": "§cHeart Container EX§r",
        "tooltip.itemstages.name.default": "§5§ka§r §dUnknown Item §5§ka§r",
        "betterfoliage.rendererror": "§a[Better Foliage]§f Error rendering block %s §9@ §7(§6%s§7)§r. §7(This can be ignored)",
        "potion.saturation": "Saturation",
        "tile.quark:monster_box.name": "§cMonster Box",
        "tile.monster_box.name": "§cMonster Box",
        "mob_effect.netherex:fire_burning": "Frostflame",
        "info.nyx.blood_moon_sleeping": "§cYou cannot fall asleep under the shades of a blood moon.",
        "tile.torchmaster.mega_torch.lit.tooltip": "§eAnd God says there will be light.",
        "entity.quazar.name": "§9The Slime God§r",
        "entity.champions.cinder_spark.name": "Cinder Spark",
        "vanillafix.gui.failed": "Error fetching crash report link, please manually upload it.",
        "dc.message.death": "§c[Death Counter] §eYou have died §c§l%s§r§e times.",
        "dc.message.deathAndRank": "Deaths: %1$s Rank: %2$s",
        "dc.command.leaderboard": "§a========== §eDeath Leaderboard §a==========",
        "ac.ritual.abyssalite": "Abyssalite Conversion",
        "ac.ritual.abyssalite.desc": "Turn iron ores into abyssalite ores with these gems!",
        "reskillable.skill.reskillable.mining": "Mining §7[§2+ATKSpeed§7]§r",
        "reskillable.skill.reskillable.gathering": "Gathering §7[§2+Luck§7]§r",
        "reskillable.skill.reskillable.attack": "Attack §7[§2+Damage§7]§r",
        "reskillable.skill.reskillable.defense": "Defense §7[§2+Armor§7]§r",
        "reskillable.skill.reskillable.building": "Building §7[§2+Toughness§7]§r",
        "reskillable.skill.reskillable.farming": "Farming §7[§2+Health§7]§r",
        "reskillable.skill.reskillable.agility": "Agility §7[§2+Speed§7]§r",
        "reskillable.skill.reskillable.magic": "Magic §7[§2+XPGain§7]§r",
        "message.died": "§e%s §7Died on §a%s §9(Break the grave to retrieve items)",
        "pouchofunknown.destroy_message": "The %s you have just picked up has been destroyed. %sTo hold this item either acquire the required game stage or keep a §dPouch of Unknown§e in your inventory to hold it.",
        "death.attack.outOfWorld": "Entity %1$s was removed from the Elysian Public Interface",
        "material.extrabotany:ingotorichalcos.name": "§c[Disabled]",
        "material.extrabotany:ingotshadowium.name" : "§c[Disabled]",
        "memorycleaner.gc.start": "§a[MemoryCleaner] §fCleaning memory, this might cause some lag!\n§7(If your game pauses for a long time when this happens, please use the recommended JVM arguments in the installation guide which can be found on our GitHub wiki.)"
    }
};

val blueprintDesc as string[] = [
    "item.tconstruct.longsword.desc",
    "item.tconstruct.rapier.desc",
    "item.tconstruct.cleaver.desc",
    "item.tconstruct.shuriken.desc",
    "item.tconevo:tool_sceptre.desc",
    "item.katana.desc",
    "item.laser_gun.desc"
];

for lang, entries in localizationMap {
    for k, v in entries {
        game.setLocalization(lang, k, v);
    }
}

for key in blueprintDesc {
    game.setLocalization(key, game.localize(key) + "\n" + game.localize("greedycraft.tooltip.constant.blueprint_required"));
}
