//新源质
mods.thaumcraft.aspect.aspectBuilder()
    .tag('abyss')
    .chatColor(2894892)
    .component('dreadia')
    .component('coralos')
    .image(resource('thaumcraft:textures/aspects/abyss.png'))
    .register()

mods.thaumcraft.aspect.aspectBuilder()
    .tag('cthulhu')
    .chatColor(2704148)
    .image(resource('thaumcraft:textures/aspects/cthulhu.png'))
    .register()

mods.thaumcraft.aspect.aspectBuilder()
    .tag('tempestas')
    .chatColor(2712987)
    .component('aer')
    .component('aqua')
    .image(resource('thaumcraft:textures/aspects/tempestas.png'))
    .register()

mods.thaumcraft.aspect.aspectBuilder()
    .tag('pulvis')
    .chatColor(7960953)
    .component('ignis')
    .component('terra')
    .image(resource('thaumcraft:textures/aspects/pulvis.png'))
    .register()

mods.thaumcraft.aspect.aspectBuilder()
    .tag('primitivus')
    .chatColor(2859589)
    .component('terra')
    .component('perditio')
    .image(resource('thaumcraft:textures/aspects/primitivus.png'))
    .register()

mods.thaumcraft.aspect.aspectBuilder()
    .tag('vapor')
    .chatColor(16777215)
    .component('aqua')
    .component('ignis')
    .image(resource('thaumcraft:textures/aspects/vapor.png'))
    .register()

mods.thaumcraft.aspect.aspectBuilder()
    .tag('structura')
    .chatColor(11740686)
    .component('aqua')
    .component('ordo')
    .image(resource('thaumcraft:textures/aspects/structura.png'))
    .register()

//新研究类
mods.thaumcraft.research.researchCategoryBuilder()
    .key('ABYSSISM')
    .researchKey(null)
    .formulaAspect(aspect('coralos') * 10)
    .formulaAspect(aspect('dreadia') * 10)
    .formulaAspect(aspect('abyss') * 10)
    .icon(resource('abyssalcraft:textures/items/abyssalnomicon.png'))
    .background(resource('thaumcraft:textures/backgrounds/abyssism.png'))
    .background2(resource('thaumcraft:textures/backgrounds/abyssism.png'))
    .register()

//新扫描
mods.thaumcraft.research.addScannable("SHADOW_BEAST", entity('abyssalcraft:shadowbeast').entityClass, true)
mods.thaumcraft.research.addScannable("SPECTRAL_DRAGON", entity('abyssalcraft:dragonminion').entityClass, true)
mods.thaumcraft.research.addScannable("DREAD_GUARD", entity('abyssalcraft:dreadguard').entityClass, true)
mods.thaumcraft.research.addScannable("MINION_OF_GATEKEEPER", entity('abyssalcraft:jzaharminion').entityClass, true)
mods.thaumcraft.research.addScannable("LESSER_SHOGGOTH", entity('abyssalcraft:lessershoggoth').entityClass, true)
mods.thaumcraft.research.addScannable("ABYSSALNOMICON", item('abyssalcraft:abyssalnomicon'))
