/*
 * This script is created for the GreedyCraft modpack by TCreopargh.
 * You may NOT use this script in any other publicly distributed modpack without my permission.
 */

#priority 800

import crafttweaker.item.IItemStack;
import crafttweaker.data.IData;
import crafttweaker.item.IIngredient;
import crafttweaker.liquid.ILiquidStack;
import crafttweaker.oredict.IOreDictEntry;

import mods.nuclearcraft.Melter;
import mods.nuclearcraft.ChemicalReactor;
import mods.nuclearcraft.Supercooler;
import mods.nuclearcraft.Electrolyzer;
import mods.nuclearcraft.Pressurizer;
import mods.nuclearcraft.RadiationScrubber;
import mods.nuclearcraft.Radiation;
import mods.nuclearcraft.Crystallizer;
import mods.nuclearcraft.Separator;
import mods.nuclearcraft.Enricher;
import mods.nuclearcraft.Centrifuge;
import mods.nuclearcraft.SaltMixer;
import mods.nuclearcraft.IngotFormer;
import mods.nuclearcraft.Registration;
import mods.tconstruct.Alloy;
import mods.jaopca.JAOPCA;

var GEM as int = 666;

var NaCl as IItemStack = <additions:sodium_chloride>;
var KCl as IItemStack = <additions:potassium_chloride>;
var RbCl as IItemStack = <additions:rubidium_chloride>;
var CsCl as IItemStack = <additions:cesium_chloride>;
var PtCl4 as IItemStack = <additions:platinum_chloride>;
var CaCl2 as IItemStack = <additions:calcium_chloride>;
var SrCl2 as IItemStack = <additions:strontium_chloride>;
var BaCl2 as IItemStack = <additions:barium_chloride>;

for entry in JAOPCA.getMaterialsForType("INGOTS") {
    var ingot as IItemStack = entry.getItemStack("ingot");
    var dust as IItemStack = entry.getItemStack("dust");
    var nugget as IItemStack = entry.getItemStack("nugget");
    var block as IItemStack = entry.getItemStack("block");
    var molten as ILiquidStack = entry.getLiquidStack("molten", 16);
    Melter.addRecipe(ingot, molten * 9);
    Melter.addRecipe(dust, molten * 9);
    Melter.addRecipe(nugget, molten);
    Melter.addRecipe(block, molten * 81);
    IngotFormer.addRecipe(ingot, molten * 9);
}

function CreateElementMixer(inputIngot as IIngredient, inputDust as IIngredient, output1 as IItemStack, output2 as IItemStack, liquid as ILiquidStack, liquid1 as ILiquidStack, liquid2 as ILiquidStack, out1 as int, out2 as int) as void {
    var isotopeNum as int = out1 + out2;
    Separator.addRecipe(inputIngot * isotopeNum, output1 * out1, output2 * out2, isotopeNum as float / 2.0f);
    Separator.addRecipe(inputDust * isotopeNum, output1 * out1, output2 * out2, isotopeNum as float / 2.0f);
    Centrifuge.addRecipe(liquid * (16 * isotopeNum), liquid1 * (16 * out1), liquid2 * (16 * out2), null, null, null, null);
    Alloy.addRecipe(liquid * isotopeNum, [liquid1 * out1, liquid2 * out2]);
}

Alloy.addRecipe(<liquid:uranium> * 10, [<liquid:uranium_238> * 9, <liquid:uranium_235> * 1]);

CreateElementMixer(<ore:ingotNeptunium>, <ore:dustNeptunium>, <nuclearcraft:neptunium:5>, <nuclearcraft:neptunium>, <liquid:neptunium>, <liquid:neptunium_237>, <liquid:neptunium_236>, 5, 1);
CreateElementMixer(<ore:ingotPlutonium>, <ore:dustPlutonium>, <nuclearcraft:plutonium:15>, <nuclearcraft:plutonium:5>, <liquid:plutonium>, <liquid:plutonium_242>, <liquid:plutonium_239>, 5, 1);

Melter.removeRecipeWithInput(<nuclearcraft:gem_dust:10>);
Melter.removeRecipeWithInput(<nuclearcraft:gem:6>);
Melter.removeRecipeWithOutput(<liquid:sulfur> * 666);

var removeMb as int[] = [16, 144, 1296];
for mb in removeMb {
    Melter.removeRecipeWithOutput(<liquid:hydrogen> * mb);
    Melter.removeRecipeWithOutput(<liquid:helium> * mb);
    Melter.removeRecipeWithOutput(<liquid:nitrogen> * mb);
    Melter.removeRecipeWithOutput(<liquid:oxygen> * mb);
    Melter.removeRecipeWithOutput(<liquid:fluorine> * mb);
    Melter.removeRecipeWithOutput(<liquid:neon> * mb);
    Melter.removeRecipeWithOutput(<liquid:argon> * mb);
    Melter.removeRecipeWithOutput(<liquid:krypton> * mb);
    Melter.removeRecipeWithOutput(<liquid:xenon> * mb);
    Melter.removeRecipeWithOutput(<liquid:radon> * mb);
}

Melter.addRecipe(<ore:ingotHydrogen>, <liquid:hydrogen> * 46080);
Melter.addRecipe(<ore:dustHydrogen>, <liquid:hydrogen> * 46080);
Melter.addRecipe(<ore:nuggetHydrogen>, <liquid:hydrogen> * 5120);
Melter.addRecipe(<ore:blockHydrogen>, <liquid:hydrogen> * 414720);
Melter.addRecipe(<ore:ingotHelium>, <liquid:helium> * 46080);
Melter.addRecipe(<ore:dustHelium>, <liquid:helium> * 46080);
Melter.addRecipe(<ore:nuggetHelium>, <liquid:helium> * 5120);
Melter.addRecipe(<ore:blockHelium>, <liquid:helium> * 414720);
Melter.addRecipe(<ore:ingotNitrogen>, <liquid:nitrogen> * 46080);
Melter.addRecipe(<ore:dustNitrogen>, <liquid:nitrogen> * 46080);
Melter.addRecipe(<ore:nuggetNitrogen>, <liquid:nitrogen> * 5120);
Melter.addRecipe(<ore:blockNitrogen>, <liquid:nitrogen> * 414720);
Melter.addRecipe(<ore:ingotOxygen>, <liquid:oxygen> * 46080);
Melter.addRecipe(<ore:dustOxygen>, <liquid:oxygen> * 46080);
Melter.addRecipe(<ore:nuggetOxygen>, <liquid:oxygen> * 5120);
Melter.addRecipe(<ore:blockOxygen>, <liquid:oxygen> * 414720);
Melter.addRecipe(<ore:ingotFluorine>, <liquid:fluorine> * 46080);
Melter.addRecipe(<ore:dustFluorine>, <liquid:fluorine> * 46080);
Melter.addRecipe(<ore:nuggetFluorine>, <liquid:fluorine> * 5120);
Melter.addRecipe(<ore:blockFluorine>, <liquid:fluorine> * 414720);
Melter.addRecipe(<ore:ingotNeon>, <liquid:neon> * 46080);
Melter.addRecipe(<ore:dustNeon>, <liquid:neon> * 46080);
Melter.addRecipe(<ore:nuggetNeon>, <liquid:neon> * 5120);
Melter.addRecipe(<ore:blockNeon>, <liquid:neon> * 414720);
Melter.addRecipe(<ore:ingotArgon>, <liquid:argon> * 46080);
Melter.addRecipe(<ore:dustArgon>, <liquid:argon> * 46080);
Melter.addRecipe(<ore:nuggetArgon>, <liquid:argon> * 5120);
Melter.addRecipe(<ore:blockArgon>, <liquid:argon> * 414720);
Melter.addRecipe(<ore:ingotKrypton>, <liquid:krypton> * 46080);
Melter.addRecipe(<ore:dustKrypton>, <liquid:krypton> * 46080);
Melter.addRecipe(<ore:nuggetKrypton>, <liquid:krypton> * 5120);
Melter.addRecipe(<ore:blockKrypton>, <liquid:krypton> * 414720);
Melter.addRecipe(<ore:ingotXenon>, <liquid:xenon> * 46080);
Melter.addRecipe(<ore:dustXenon>, <liquid:xenon> * 46080);
Melter.addRecipe(<ore:nuggetXenon>, <liquid:xenon> * 5120);
Melter.addRecipe(<ore:blockXenon>, <liquid:xenon> * 414720);
Melter.addRecipe(<ore:ingotRadon>, <liquid:radon> * 46080);
Melter.addRecipe(<ore:dustRadon>, <liquid:radon> * 46080);
Melter.addRecipe(<ore:nuggetRadon>, <liquid:radon> * 5120);
Melter.addRecipe(<ore:blockRadon>, <liquid:radon> * 414720);
Melter.addRecipe(<ore:ingotChlorine>, <liquid:liquidchlorine> * 46080);
Melter.addRecipe(<ore:dustChlorine>, <liquid:liquidchlorine> * 46080);
Melter.addRecipe(<ore:nuggetChlorine>, <liquid:liquidchlorine> * 5120);
Melter.addRecipe(<ore:blockChlorine>, <liquid:liquidchlorine> * 414720);

Melter.addRecipe(<ore:dustSulfur>, <liquid:burningsulfurflow> * 144, 1.0, 1.0, 0.0);
Melter.addRecipe(<ore:ingotSulfur>, <liquid:burningsulfurflow> * 144, 1.0, 1.0, 0.0);
Melter.addRecipe(NaCl, <liquid:sodium_chloride> * 666);
Melter.addRecipe(KCl, <liquid:potassium_chloride> * 666);
Melter.addRecipe(RbCl, <liquid:rubidium_chloride> * 666);
Melter.addRecipe(CsCl, <liquid:cesium_chloride> * 666);
Melter.addRecipe(PtCl4, <liquid:platinum_chloride> * 666);
Melter.addRecipe(CaCl2, <liquid:calcium_chloride> * 666);
Melter.addRecipe(SrCl2, <liquid:strontium_chloride> * 666);
Melter.addRecipe(BaCl2, <liquid:barium_chloride> * 666);
Melter.addRecipe(<ore:dustZincChloride>, <liquid:zinc_chloride> * 666);
Melter.addRecipe(<ore:dustManganeseChloride>, <liquid:manganese_chloride> * 666);
Melter.addRecipe(<ore:dustPhosphorusPentaoxide>, <liquid:phosphorus_pentaoxide> * 666);
Melter.addRecipe(<ore:materialMethane>, <liquid:methane> * 200);
Melter.addRecipe(<additions:ancient_debris>, <liquid:ancient_debris> * 320);
Melter.addRecipe(<additions:netherite_scrap>, <liquid:ancient_debris> * 160);
Melter.addRecipe(<gct_mobs:resonate_debris>, <liquid:resonant_debris> * 320);
Melter.addRecipe(<gct_mobs:resonate_debris_cracked>, <liquid:resonant_debris> * 160);
Melter.addRecipe(<gct_mobs:resonated_scrap>, <liquid:resonant_debris> * 160);
Melter.addRecipe(<gct_mobs:gravity_debris>, <liquid:gravity_debris> * 320);
Melter.addRecipe(<gct_mobs:gravity_scrap>, <liquid:gravity_debris> * 160);
Melter.addRecipe(<tcomplement:materials:1>, <liquid:scorched> * 144);
Melter.addRecipe(<ore:itemSilicon>, <liquid:silicon> * 36);
Melter.addRecipe(<twilightforest:mazebreaker_pickaxe>, <liquid:fracturite> * 432);
Melter.addRecipe(<ore:ingotArsenic>, <liquid:arsenic> * 144);
Melter.addRecipe(<ore:dustArsenic>, <liquid:arsenic> * 144);
Melter.addRecipe(<ore:blockArsenic>, <liquid:arsenic> * 1296);
Melter.addRecipe(<ore:nuggetArsenic>, <liquid:arsenic> * 16);
Melter.addRecipe(<ore:ingotSkyAlloy>, <liquid:sky_alloy> * 144);
Melter.addRecipe(<ore:dustSkyAlloy>, <liquid:sky_alloy> * 144);
Melter.addRecipe(<ore:blockSkyAlloy>, <liquid:sky_alloy> * 1296);
Melter.addRecipe(<ore:nuggetSkyAlloy>, <liquid:sky_alloy> * 16);
Melter.addRecipe(<ore:ingotFireAlloy>, <liquid:fire_alloy> * 144);
Melter.addRecipe(<ore:dustFireAlloy>, <liquid:fire_alloy> * 144);
Melter.addRecipe(<ore:blockFireAlloy>, <liquid:fire_alloy> * 1296);
Melter.addRecipe(<ore:nuggetFireAlloy>, <liquid:fire_alloy> * 16);
Melter.addRecipe(<ore:ingotIceAlloy>, <liquid:ice_alloy> * 144);
Melter.addRecipe(<ore:dustIceAlloy>, <liquid:ice_alloy> * 144);
Melter.addRecipe(<ore:blockIceAlloy>, <liquid:ice_alloy> * 1296);
Melter.addRecipe(<ore:nuggetIceAlloy>, <liquid:ice_alloy> * 16);
Melter.addRecipe(<ore:ingotDraconiumAwakened>, <liquid:awakened_draconium> * 144);
Melter.addRecipe(<ore:dustDraconiumAwakened>, <liquid:awakened_draconium> * 144);
Melter.addRecipe(<ore:blockDraconiumAwakened>, <liquid:awakened_draconium> * 1296);
Melter.addRecipe(<ore:nuggetDraconiumAwakened>, <liquid:awakened_draconium> * 16);
Melter.addRecipe(<ore:ingotDraconiumChaotic>, <liquid:chaotic_draconium> * 144);
Melter.addRecipe(<ore:dustDraconiumChaotic>, <liquid:chaotic_draconium> * 144);
Melter.addRecipe(<ore:blockDraconiumChaotic>, <liquid:chaotic_draconium> * 1296);
Melter.addRecipe(<ore:nuggetDraconiumChaotic>, <liquid:chaotic_draconium> * 16);
Melter.addRecipe(<ore:ingotDraconiumRuled>, <liquid:ruled_draconium> * 144);
Melter.addRecipe(<ore:dustDraconiumRuled>, <liquid:ruled_draconium> * 144);
Melter.addRecipe(<ore:blockDraconiumRuled>, <liquid:ruled_draconium> * 1296);
Melter.addRecipe(<ore:nuggetDraconiumRuled>, <liquid:ruled_draconium> * 16);
Melter.addRecipe(<ore:ingotWitheriumRelifed>, <liquid:relifed_witherium> * 144);
Melter.addRecipe(<ore:dustWitheriumRelifed>, <liquid:relifed_witherium> * 144);
Melter.addRecipe(<ore:blockWitheriumRelifed>, <liquid:relifed_witherium> * 1296);
Melter.addRecipe(<ore:nuggetWitheriumRelifed>, <liquid:relifed_witherium> * 16);
Melter.addRecipe(<ore:ingotWitheriumStormy>, <liquid:stormy_witherium> * 144);
Melter.addRecipe(<ore:dustWitheriumStormy>, <liquid:stormy_witherium> * 144);
Melter.addRecipe(<ore:blockWitheriumStormy>, <liquid:stormy_witherium> * 1296);
Melter.addRecipe(<ore:nuggetWitheriumStormy>, <liquid:stormy_witherium> * 16);
Melter.addRecipe(<ore:ingotWitheriumEquipment>, <liquid:equipment_witherium> * 144);
Melter.addRecipe(<ore:dustWitheriumEquipment>, <liquid:equipment_witherium> * 144);
Melter.addRecipe(<ore:blockWitheriumEquipment>, <liquid:equipment_witherium> * 1296);
Melter.addRecipe(<ore:nuggetWitheriumEquipment>, <liquid:equipment_witherium> * 16);
Melter.addRecipe(<ore:ingotGalliumIndiumPhosphide>, <liquid:gallium_indium_phosphide> * 144);
Melter.addRecipe(<ore:dustGalliumIndiumPhosphide>, <liquid:gallium_indium_phosphide> * 144);
Melter.addRecipe(<ore:blockGalliumIndiumPhosphide>, <liquid:gallium_indium_phosphide> * 1296);
Melter.addRecipe(<ore:nuggetGalliumIndiumPhosphide>, <liquid:gallium_indium_phosphide> * 16);
Melter.addRecipe(<ore:ingotGallium>, <liquid:liquidgallium> * 144);
Melter.addRecipe(<ore:dustGallium>, <liquid:liquidgallium> * 144);
Melter.addRecipe(<ore:blockGallium>, <liquid:liquidgallium> * 1296);
Melter.addRecipe(<ore:nuggetGallium>, <liquid:liquidgallium> * 16);
Melter.addRecipe(<ore:ingotRoseGold>, <liquid:rose_gold> * 144);
Melter.addRecipe(<ore:dustRoseGold>, <liquid:rose_gold> * 144);
Melter.addRecipe(<ore:blockRoseGold>, <liquid:rose_gold> * 1296);
Melter.addRecipe(<ore:nuggetRoseGold>, <liquid:rose_gold> * 16);
Melter.addRecipe(<ore:ingotElectrumFlux>, <liquid:fluxed_electrum> * 144);
Melter.addRecipe(<ore:dustElectrumFlux>, <liquid:fluxed_electrum> * 144);
Melter.addRecipe(<ore:blockElectrumFlux>, <liquid:fluxed_electrum> * 1296);
Melter.addRecipe(<ore:nuggetElectrumFlux>, <liquid:fluxed_electrum> * 16);
Melter.addRecipe(<ore:gemGalliumPhosphide>, <liquid:gallium_phosphide> * GEM);
Melter.addRecipe(<ore:dustGalliumPhosphide>, <liquid:gallium_phosphide> * GEM);
Melter.addRecipe(<ore:blockGalliumPhosphide>, <liquid:gallium_phosphide> * (GEM * 9));
Melter.addRecipe(<ore:nuggetGalliumPhosphide>, <liquid:gallium_phosphide> * (GEM / 9));
Melter.addRecipe(<ore:gemIndiumPhosphide>, <liquid:indium_phosphide> * GEM);
Melter.addRecipe(<ore:dustIndiumPhosphide>, <liquid:indium_phosphide> * GEM);
Melter.addRecipe(<ore:blockIndiumPhosphide>, <liquid:indium_phosphide> * (GEM * 9));
Melter.addRecipe(<ore:nuggetIndiumPhosphide>, <liquid:indium_phosphide> * (GEM / 9));
Melter.addRecipe(<ore:ingotGlowingSignalum>, <liquid:glowing_signalum> * 144);
Melter.addRecipe(<ore:dustGlowingSignalum>, <liquid:glowing_signalum> * 144);
Melter.addRecipe(<ore:blockGlowingSignalum>, <liquid:glowing_signalum> * 1296);
Melter.addRecipe(<ore:nuggetGlowingSignalum>, <liquid:glowing_signalum> * 16);
Melter.addRecipe(<ore:ingotRoyalAlloy>, <liquid:royal_alloy> * 144);
Melter.addRecipe(<ore:dustRoyalAlloy>, <liquid:royal_alloy> * 144);
Melter.addRecipe(<ore:blockRoyalAlloy>, <liquid:royal_alloy> * 1296);
Melter.addRecipe(<ore:nuggetRoyalAlloy>, <liquid:royal_alloy> * 16);
Melter.addRecipe(<gct_ores:balanced_matrix_ingot>, <liquid:balanced_matrix> * 144);
Melter.addRecipe(<gct_ores:balanced_matrix_block>, <liquid:balanced_matrix> * 1296);
Melter.addRecipe(<ore:nuggetBalancedMatrix>, <liquid:balanced_matrix> * 16);
Melter.addRecipe(<ore:dustBalancedMatrix>, <liquid:balanced_matrix> * 144);
Melter.addRecipe(<abyssalcraft:cingot>, <liquid:liquified_coralium> * 144);
Melter.addRecipe(<abyssalcraft:ingotblock:1>, <liquid:liquified_coralium> * 1296);
Melter.addRecipe(<ore:nuggetLiquifiedCoralium>, <liquid:liquified_coralium> * 16);
Melter.addRecipe(<ore:dustLiquifiedCoralium>, <liquid:liquified_coralium> * 144);
Melter.addRecipe(<abyssalcraft:abylcorore>, <liquid:liquified_coralium> * 288);
Melter.addRecipe(<ore:ingotBasalt>, <liquid:basalt_fluid> * 144);
Melter.addRecipe(<ore:dustBasalt>, <liquid:basalt_fluid> * 144);
Melter.addRecipe(<ore:blockBasalt>, <liquid:basalt_fluid> * 1296);
Melter.addRecipe(<ore:nuggetBasalt>, <liquid:basalt_fluid> * 16);
Melter.addRecipe(<ore:ingotTiberium>, <liquid:tiberium_fluid> * 144);
Melter.addRecipe(<ore:dustTiberium>, <liquid:tiberium_fluid> * 144);
Melter.addRecipe(<ore:blockTiberium>, <liquid:tiberium_fluid> * 1296);
Melter.addRecipe(<ore:nuggetTiberium>, <liquid:tiberium_fluid> * 16);
Melter.addRecipe(<ore:crystalTiberium>, <liquid:tiberium_fluid> * 72);
Melter.addRecipe(<ore:ingotAurorium>, <liquid:aurorium_fluid> * 144);
Melter.addRecipe(<ore:dustAurorium>, <liquid:aurorium_fluid> * 144);
Melter.addRecipe(<ore:blockAurorium>, <liquid:aurorium_fluid> * 1296);
Melter.addRecipe(<ore:nuggetAurorium>, <liquid:aurorium_fluid> * 16);
Melter.addRecipe(<ore:ingotPrometheum>, <liquid:prometheum_fluid> * 144);
Melter.addRecipe(<ore:dustPrometheum>, <liquid:prometheum_fluid> * 144);
Melter.addRecipe(<ore:blockPrometheum>, <liquid:prometheum_fluid> * 1296);
Melter.addRecipe(<ore:nuggetPrometheum>, <liquid:prometheum_fluid> * 16);
Melter.addRecipe(<ore:ingotDuranite>, <liquid:duranite_fluid> * 144);
Melter.addRecipe(<ore:dustDuranite>, <liquid:duranite_fluid> * 144);
Melter.addRecipe(<ore:blockDuranite>, <liquid:duranite_fluid> * 1296);
Melter.addRecipe(<ore:nuggetDuranite>, <liquid:duranite_fluid> * 16);
Melter.addRecipe(<ore:ingotValyrium>, <liquid:valyrium_fluid> * 144);
Melter.addRecipe(<ore:dustValyrium>, <liquid:valyrium_fluid> * 144);
Melter.addRecipe(<ore:blockValyrium>, <liquid:valyrium_fluid> * 1296);
Melter.addRecipe(<ore:nuggetValyrium>, <liquid:valyrium_fluid> * 16);
Melter.addRecipe(<ore:ingotVibranium>, <liquid:vibranium_fluid> * 144);
Melter.addRecipe(<ore:dustVibranium>, <liquid:vibranium_fluid> * 144);
Melter.addRecipe(<ore:blockVibranium>, <liquid:vibranium_fluid> * 1296);
Melter.addRecipe(<ore:nuggetVibranium>, <liquid:vibranium_fluid> * 16);
Melter.addRecipe(<ore:ingotKarmesine>, <liquid:karmesine_fluid> * 144);
Melter.addRecipe(<ore:dustKarmesine>, <liquid:karmesine_fluid> * 144);
Melter.addRecipe(<ore:blockKarmesine>, <liquid:karmesine_fluid> * 1296);
Melter.addRecipe(<ore:nuggetKarmesine>, <liquid:karmesine_fluid> * 16);
Melter.addRecipe(<ore:ingotJauxum>, <liquid:jauxum_fluid> * 144);
Melter.addRecipe(<ore:dustJauxum>, <liquid:jauxum_fluid> * 144);
Melter.addRecipe(<ore:blockJauxum>, <liquid:jauxum_fluid> * 1296);
Melter.addRecipe(<ore:nuggetJauxum>, <liquid:jauxum_fluid> * 16);
Melter.addRecipe(<ore:ingotOvium>, <liquid:ovium_fluid> * 144);
Melter.addRecipe(<ore:dustOvium>, <liquid:ovium_fluid> * 144);
Melter.addRecipe(<ore:blockOvium>, <liquid:ovium_fluid> * 1296);
Melter.addRecipe(<ore:nuggetOvium>, <liquid:ovium_fluid> * 16);
Melter.addRecipe(<ore:ingotTerrax>, <liquid:terrax_fluid> * 144);
Melter.addRecipe(<ore:dustTerrax>, <liquid:terrax_fluid> * 144);
Melter.addRecipe(<ore:blockTerrax>, <liquid:terrax_fluid> * 1296);
Melter.addRecipe(<ore:nuggetTerrax>, <liquid:terrax_fluid> * 16);
Melter.addRecipe(<ore:ingotPalladium>, <liquid:palladium_fluid> * 144);
Melter.addRecipe(<ore:dustPalladium>, <liquid:palladium_fluid> * 144);
Melter.addRecipe(<ore:blockPalladium>, <liquid:palladium_fluid> * 1296);
Melter.addRecipe(<ore:nuggetPalladium>, <liquid:palladium_fluid> * 16);
Melter.addRecipe(<ore:ingotUru>, <liquid:uru_fluid> * 144);
Melter.addRecipe(<ore:dustUru>, <liquid:uru_fluid> * 144);
Melter.addRecipe(<ore:blockUru>, <liquid:uru_fluid> * 1296);
Melter.addRecipe(<ore:nuggetUru>, <liquid:uru_fluid> * 16);
Melter.addRecipe(<ore:ingotOsram>, <liquid:osram_fluid> * 144);
Melter.addRecipe(<ore:dustOsram>, <liquid:osram_fluid> * 144);
Melter.addRecipe(<ore:blockOsram>, <liquid:osram_fluid> * 1296);
Melter.addRecipe(<ore:nuggetOsram>, <liquid:osram_fluid> * 16);
Melter.addRecipe(<ore:ingotAbyssum>, <liquid:abyssum_fluid> * 144);
Melter.addRecipe(<ore:dustAbyssum>, <liquid:abyssum_fluid> * 144);
Melter.addRecipe(<ore:blockAbyssum>, <liquid:abyssum_fluid> * 1296);
Melter.addRecipe(<ore:nuggetAbyssum>, <liquid:abyssum_fluid> * 16);
Melter.addRecipe(<ore:ingotEezo>, <liquid:eezo_fluid> * 144);
Melter.addRecipe(<ore:dustEezo>, <liquid:eezo_fluid> * 144);
Melter.addRecipe(<ore:blockEezo>, <liquid:eezo_fluid> * 1296);
Melter.addRecipe(<ore:nuggetEezo>, <liquid:eezo_fluid> * 16);
Melter.addRecipe(<ore:ingotTriberium>, <liquid:triberium_fluid> * 144);
Melter.addRecipe(<ore:dustTriberium>, <liquid:triberium_fluid> * 144);
Melter.addRecipe(<ore:blockTriberium>, <liquid:triberium_fluid> * 1296);
Melter.addRecipe(<ore:nuggetTriberium>, <liquid:triberium_fluid> * 16);
Melter.addRecipe(<ore:ingotFractum>, <liquid:fractum_fluid> * 144);
Melter.addRecipe(<ore:dustFractum>, <liquid:fractum_fluid> * 144);
Melter.addRecipe(<ore:blockFractum>, <liquid:fractum_fluid> * 1296);
Melter.addRecipe(<ore:nuggetFractum>, <liquid:fractum_fluid> * 16);
Melter.addRecipe(<ore:ingotViolium>, <liquid:violium_fluid> * 144);
Melter.addRecipe(<ore:dustViolium>, <liquid:violium_fluid> * 144);
Melter.addRecipe(<ore:blockViolium>, <liquid:violium_fluid> * 1296);
Melter.addRecipe(<ore:nuggetViolium>, <liquid:violium_fluid> * 16);
Melter.addRecipe(<ore:ingotProxii>, <liquid:proxii_fluid> * 144);
Melter.addRecipe(<ore:dustProxii>, <liquid:proxii_fluid> * 144);
Melter.addRecipe(<ore:blockProxii>, <liquid:proxii_fluid> * 1296);
Melter.addRecipe(<ore:nuggetProxii>, <liquid:proxii_fluid> * 16);
Melter.addRecipe(<ore:ingotTritonite>, <liquid:tritonite_fluid> * 144);
Melter.addRecipe(<ore:dustTritonite>, <liquid:tritonite_fluid> * 144);
Melter.addRecipe(<ore:blockTritonite>, <liquid:tritonite_fluid> * 1296);
Melter.addRecipe(<ore:nuggetTritonite>, <liquid:tritonite_fluid> * 16);
Melter.addRecipe(<ore:ingotIgnitz>, <liquid:ignitz_fluid> * 144);
Melter.addRecipe(<ore:dustIgnitz>, <liquid:ignitz_fluid> * 144);
Melter.addRecipe(<ore:blockIgnitz>, <liquid:ignitz_fluid> * 1296);
Melter.addRecipe(<ore:nuggetIgnitz>, <liquid:ignitz_fluid> * 16);
Melter.addRecipe(<ore:ingotImperomite>, <liquid:imperomite_fluid> * 144);
Melter.addRecipe(<ore:dustImperomite>, <liquid:imperomite_fluid> * 144);
Melter.addRecipe(<ore:blockImperomite>, <liquid:imperomite_fluid> * 1296);
Melter.addRecipe(<ore:nuggetImperomite>, <liquid:imperomite_fluid> * 16);
Melter.addRecipe(<ore:ingotSolarium>, <liquid:solarium_fluid> * 144);
Melter.addRecipe(<ore:dustSolarium>, <liquid:solarium_fluid> * 144);
Melter.addRecipe(<ore:blockSolarium>, <liquid:solarium_fluid> * 1296);
Melter.addRecipe(<ore:nuggetSolarium>, <liquid:solarium_fluid> * 16);
Melter.addRecipe(<ore:ingotNihilite>, <liquid:nihilite_fluid> * 144);
Melter.addRecipe(<ore:dustNihilite>, <liquid:nihilite_fluid> * 144);
Melter.addRecipe(<ore:blockNihilite>, <liquid:nihilite_fluid> * 1296);
Melter.addRecipe(<ore:nuggetNihilite>, <liquid:nihilite_fluid> * 16);
Melter.addRecipe(<ore:ingotAdamant>, <liquid:adamant_fluid> * 144);
Melter.addRecipe(<ore:dustAdamant>, <liquid:adamant_fluid> * 144);
Melter.addRecipe(<ore:blockAdamant>, <liquid:adamant_fluid> * 1296);
Melter.addRecipe(<ore:nuggetAdamant>, <liquid:adamant_fluid> * 16);
Melter.addRecipe(<ore:ingotDyonite>, <liquid:dyonite_fluid> * 144);
Melter.addRecipe(<ore:dustDyonite>, <liquid:dyonite_fluid> * 144);
Melter.addRecipe(<ore:blockDyonite>, <liquid:dyonite_fluid> * 1296);
Melter.addRecipe(<ore:nuggetDyonite>, <liquid:dyonite_fluid> * 16);
Melter.addRecipe(<ore:ingotNucleum>, <liquid:nucleum_fluid> * 144);
Melter.addRecipe(<ore:dustNucleum>, <liquid:nucleum_fluid> * 144);
Melter.addRecipe(<ore:blockNucleum>, <liquid:nucleum_fluid> * 1296);
Melter.addRecipe(<ore:nuggetNucleum>, <liquid:nucleum_fluid> * 16);
Melter.addRecipe(<ore:ingotLumix>, <liquid:lumix_fluid> * 144);
Melter.addRecipe(<ore:dustLumix>, <liquid:lumix_fluid> * 144);
Melter.addRecipe(<ore:blockLumix>, <liquid:lumix_fluid> * 1296);
Melter.addRecipe(<ore:nuggetLumix>, <liquid:lumix_fluid> * 16);
Melter.addRecipe(<ore:ingotSeismum>, <liquid:seismum_fluid> * 144);
Melter.addRecipe(<ore:dustSeismum>, <liquid:seismum_fluid> * 144);
Melter.addRecipe(<ore:blockSeismum>, <liquid:seismum_fluid> * 1296);
Melter.addRecipe(<ore:nuggetSeismum>, <liquid:seismum_fluid> * 16);
Melter.addRecipe(<ore:ingotAstrium>, <liquid:astrium_fluid> * 144);
Melter.addRecipe(<ore:dustAstrium>, <liquid:astrium_fluid> * 144);
Melter.addRecipe(<ore:blockAstrium>, <liquid:astrium_fluid> * 1296);
Melter.addRecipe(<ore:nuggetAstrium>, <liquid:astrium_fluid> * 16);
Melter.addRecipe(<ore:ingotNiob>, <liquid:niob_fluid> * 144);
Melter.addRecipe(<ore:dustNiob>, <liquid:niob_fluid> * 144);
Melter.addRecipe(<ore:blockNiob>, <liquid:niob_fluid> * 1296);
Melter.addRecipe(<ore:nuggetNiob>, <liquid:niob_fluid> * 16);
Melter.addRecipe(<ore:ingotYrdeen>, <liquid:yrdeen_fluid> * 144);
Melter.addRecipe(<ore:dustYrdeen>, <liquid:yrdeen_fluid> * 144);
Melter.addRecipe(<ore:blockYrdeen>, <liquid:yrdeen_fluid> * 1296);
Melter.addRecipe(<ore:nuggetYrdeen>, <liquid:yrdeen_fluid> * 16);
Melter.addRecipe(<ore:ingotIox>, <liquid:iox_fluid> * 144);
Melter.addRecipe(<ore:dustIox>, <liquid:iox_fluid> * 144);
Melter.addRecipe(<ore:blockIox>, <liquid:iox_fluid> * 1296);
Melter.addRecipe(<ore:nuggetIox>, <liquid:iox_fluid> * 16);
Melter.addRecipe(<ore:ingotMeteorite>, <liquid:meteorite_fluid> * 144);
Melter.addRecipe(<ore:dustMeteorite>, <liquid:meteorite_fluid> * 144);
Melter.addRecipe(<ore:blockMeteorite>, <liquid:meteorite_fluid> * 1296);
Melter.addRecipe(<ore:nuggetMeteorite>, <liquid:meteorite_fluid> * 16);
Melter.addRecipe(<ore:ingotObsidiorite>, <liquid:obsidiorite_fluid> * 144);
Melter.addRecipe(<ore:dustObsidiorite>, <liquid:obsidiorite_fluid> * 144);
Melter.addRecipe(<ore:blockObsidiorite>, <liquid:obsidiorite_fluid> * 1296);
Melter.addRecipe(<ore:nuggetObsidiorite>, <liquid:obsidiorite_fluid> * 16);
Melter.addRecipe(<ore:ingotDilithium>, <liquid:dilithium_fluid> * 144);
Melter.addRecipe(<ore:dustDilithium>, <liquid:dilithium_fluid> * 144);
Melter.addRecipe(<ore:blockDilithium>, <liquid:dilithium_fluid> * 1296);
Melter.addRecipe(<ore:nuggetDilithium>, <liquid:dilithium_fluid> * 16);
Melter.addRecipe(<ore:crystalDilithium>, <liquid:dilithium_fluid> * 72);
Melter.addRecipe(<minecraft:magma>, <liquid:magma_fluid> * 288);
Melter.addRecipe(<theaurorian:auroriansteel>, <liquid:tamoltenauroriansteel> * 144);
Melter.addRecipe(<theaurorian:auroriansteelnugget>, <liquid:tamoltenauroriansteel> * 16);
Melter.addRecipe(<theaurorian:auroriansteelblock>, <liquid:tamoltenauroriansteel> * 1296);
Melter.addRecipe(<ore:dustAurorianSteel>, <liquid:tamoltenauroriansteel> * 144);
Melter.addRecipe(<theaurorian:moonstoneore>, <liquid:tamoltenmoonstone> * 288);
Melter.addRecipe(<theaurorian:moonstoneingot>, <liquid:tamoltenmoonstone> * 144);
Melter.addRecipe(<theaurorian:moonstonenugget>, <liquid:tamoltenmoonstone> * 16);
Melter.addRecipe(<theaurorian:moonstoneblock>, <liquid:tamoltenmoonstone> * 1296);
Melter.addRecipe(<ore:dustMoonstone>, <liquid:tamoltenmoonstone> * 144);
Melter.addRecipe(<theaurorian:ceruleanore>, <liquid:tamoltencerulean> * 288);
Melter.addRecipe(<theaurorian:ceruleaningot>, <liquid:tamoltencerulean> * 144);
Melter.addRecipe(<theaurorian:ceruleannugget>, <liquid:tamoltencerulean> * 16);
Melter.addRecipe(<theaurorian:ceruleanblock>, <liquid:tamoltencerulean> * 1296);
Melter.addRecipe(<ore:dustCerulean>, <liquid:tamoltencerulean> * 144);
Melter.addRecipe(<ore:ingotEcoBasicAlloy>, <liquid:eco_basic_alloy> * 144);
Melter.addRecipe(<ore:dustEcoBasicAlloy>, <liquid:eco_basic_alloy> * 144);
Melter.addRecipe(<ore:blockEcoBasicAlloy>, <liquid:eco_basic_alloy> * 1296);
Melter.addRecipe(<ore:nuggetEcoBasicAlloy>, <liquid:eco_basic_alloy> * 16);
Melter.addRecipe(<ore:ingotBlueAlloy>, <liquid:blue_alloy> * 144);
Melter.addRecipe(<ore:dustBlueAlloy>, <liquid:blue_alloy> * 144);
Melter.addRecipe(<ore:blockBlueAlloy>, <liquid:blue_alloy> * 1296);
Melter.addRecipe(<ore:nuggetBlueAlloy>, <liquid:blue_alloy> * 16);

Melter.addRecipe(<thermalfoundation:material:893>, <liquid:redstone> * 250);
Melter.addRecipe(<thermalfoundation:material:894>, <liquid:glowstone> * 250);
Melter.addRecipe(<thermalfoundation:material:895>, <liquid:ender> * 250);

Melter.addRecipe(<gct_mobs:bnatuz_dust>, <liquid:naturaeum> * 100);
Melter.addRecipe(<gct_mobs:bthdz_dust>, <liquid:tonitruium> * 100);
Melter.addRecipe(<gct_mobs:bligtz_dust>, <liquid:lumixeium> * 100);
Melter.addRecipe(<gct_mobs:bninz_dust>, <liquid:noxexeum> * 100);
Melter.addRecipe(<gct_mobs:naturaeum_dust>, <liquid:naturaeum> * 250);
Melter.addRecipe(<gct_mobs:tonitruium_dust>, <liquid:tonitruium> * 250);
Melter.addRecipe(<gct_mobs:lumixeium_dust>, <liquid:lumixeium> * 250);
Melter.addRecipe(<gct_mobs:noxexeum_dust>, <liquid:noxexeum> * 250);

IngotFormer.removeRecipeWithOutput(<additions:hydrogen_ingot>);
IngotFormer.removeRecipeWithOutput(<additions:helium_ingot>);
IngotFormer.removeRecipeWithOutput(<additions:nitrogen_ingot>);
IngotFormer.removeRecipeWithOutput(<additions:oxygen_ingot>);
IngotFormer.removeRecipeWithOutput(<additions:fluorine_ingot>);
IngotFormer.removeRecipeWithOutput(<additions:neon_ingot>);
IngotFormer.removeRecipeWithOutput(<additions:argon_ingot>);
IngotFormer.removeRecipeWithOutput(<additions:krypton_ingot>);
IngotFormer.removeRecipeWithOutput(<additions:xenon_ingot>);
IngotFormer.removeRecipeWithOutput(<additions:radon_ingot>);
IngotFormer.addRecipe(<liquid:awakened_draconium> * 144, <draconicevolution:draconic_ingot>);
IngotFormer.addRecipe(<liquid:chaotic_draconium> * 144, <gct_ores:chaotic_draconium_ingot>);
IngotFormer.addRecipe(<liquid:ruled_draconium> * 144, <gct_ores:ruled_draconium_ingot>);
IngotFormer.addRecipe(<liquid:relifed_witherium> * 144, <gct_ores:relifed_witherium_ingot>);
IngotFormer.addRecipe(<liquid:stormy_witherium> * 144, <gct_ores:stormy_witherium_ingot>);
IngotFormer.addRecipe(<liquid:equipment_witherium> * 144, <gct_ores:equipment_witherium_ingot>);
IngotFormer.addRecipe(<liquid:gallium_indium_phosphide> * 144, <additions:gallium_indium_phosphide>);
IngotFormer.addRecipe(<liquid:gallium_phosphide> * GEM, <additions:gallium_phosphide>);
IngotFormer.addRecipe(<liquid:indium_phosphide> * GEM, <additions:indium_phosphide>);
IngotFormer.addRecipe(<liquid:liquidgallium> * 144, <moretcon:ingotgallium>);
IngotFormer.addRecipe(<liquid:rose_gold> * 144, <mca:rose_gold_ingot>);
IngotFormer.addRecipe(<liquid:fluxed_electrum> * 144, <redstonearsenal:material:32>);
IngotFormer.addRecipe(<liquid:glowing_signalum> * 144, <additions:glowing_signalum_ingot>);
IngotFormer.addRecipe(<liquid:royal_alloy> * 144, <tiths:ingot_royal_alloy>);
IngotFormer.addRecipe(<liquid:balanced_matrix> * 144, <gct_ores:balanced_matrix_ingot>);
IngotFormer.addRecipe(<liquid:liquified_coralium> * 144, <abyssalcraft:cingot>);
IngotFormer.addRecipe(<liquid:basalt_fluid> * 144, <taiga:basalt_ingot>);
IngotFormer.addRecipe(<liquid:tiberium_fluid> * 144, <taiga:tiberium_ingot>);
IngotFormer.addRecipe(<liquid:aurorium_fluid> * 144, <taiga:aurorium_ingot>);
IngotFormer.addRecipe(<liquid:prometheum_fluid> * 144, <taiga:prometheum_ingot>);
IngotFormer.addRecipe(<liquid:duranite_fluid> * 144, <taiga:duranite_ingot>);
IngotFormer.addRecipe(<liquid:valyrium_fluid> * 144, <taiga:valyrium_ingot>);
IngotFormer.addRecipe(<liquid:vibranium_fluid> * 144, <taiga:vibranium_ingot>);
IngotFormer.addRecipe(<liquid:karmesine_fluid> * 144, <taiga:karmesine_ingot>);
IngotFormer.addRecipe(<liquid:jauxum_fluid> * 144, <taiga:jauxum_ingot>);
IngotFormer.addRecipe(<liquid:ovium_fluid> * 144, <taiga:ovium_ingot>);
IngotFormer.addRecipe(<liquid:terrax_fluid> * 144, <taiga:terrax_ingot>);
IngotFormer.addRecipe(<liquid:palladium_fluid> * 144, <taiga:palladium_ingot>);
IngotFormer.addRecipe(<liquid:uru_fluid> * 144, <taiga:uru_ingot>);
IngotFormer.addRecipe(<liquid:osram_fluid> * 144, <taiga:osram_ingot>);
IngotFormer.addRecipe(<liquid:abyssum_fluid> * 144, <taiga:abyssum_ingot>);
IngotFormer.addRecipe(<liquid:eezo_fluid> * 144, <taiga:eezo_ingot>);
IngotFormer.addRecipe(<liquid:triberium_fluid> * 144, <taiga:triberium_ingot>);
IngotFormer.addRecipe(<liquid:fractum_fluid> * 144, <taiga:fractum_ingot>);
IngotFormer.addRecipe(<liquid:violium_fluid> * 144, <taiga:violium_ingot>);
IngotFormer.addRecipe(<liquid:proxii_fluid> * 144, <taiga:proxii_ingot>);
IngotFormer.addRecipe(<liquid:tritonite_fluid> * 144, <taiga:tritonite_ingot>);
IngotFormer.addRecipe(<liquid:ignitz_fluid> * 144, <taiga:ignitz_ingot>);
IngotFormer.addRecipe(<liquid:imperomite_fluid> * 144, <taiga:imperomite_ingot>);
IngotFormer.addRecipe(<liquid:solarium_fluid> * 144, <taiga:solarium_ingot>);
IngotFormer.addRecipe(<liquid:nihilite_fluid> * 144, <taiga:nihilite_ingot>);
IngotFormer.addRecipe(<liquid:adamant_fluid> * 144, <taiga:adamant_ingot>);
IngotFormer.addRecipe(<liquid:dyonite_fluid> * 144, <taiga:dyonite_ingot>);
IngotFormer.addRecipe(<liquid:nucleum_fluid> * 144, <taiga:nucleum_ingot>);
IngotFormer.addRecipe(<liquid:lumix_fluid> * 144, <taiga:lumix_ingot>);
IngotFormer.addRecipe(<liquid:seismum_fluid> * 144, <taiga:seismum_ingot>);
IngotFormer.addRecipe(<liquid:astrium_fluid> * 144, <taiga:astrium_ingot>);
IngotFormer.addRecipe(<liquid:niob_fluid> * 144, <taiga:niob_ingot>);
IngotFormer.addRecipe(<liquid:yrdeen_fluid> * 144, <taiga:yrdeen_ingot>);
IngotFormer.addRecipe(<liquid:iox_fluid> * 144, <taiga:iox_ingot>);
IngotFormer.addRecipe(<liquid:meteorite_fluid> * 144, <taiga:meteorite_ingot>);
IngotFormer.addRecipe(<liquid:obsidiorite_fluid> * 144, <taiga:obsidiorite_ingot>);
IngotFormer.addRecipe(<liquid:dilithium_fluid> * 144, <taiga:dilithium_ingot>);
IngotFormer.addRecipe(<liquid:eco_basic_alloy> * 144, <additions:eco_basic_alloy_ingot>);
IngotFormer.addRecipe(<liquid:blue_alloy> * 144, <additions:blue_alloy_ingot>);

SaltMixer.removeRecipeWithInput(<liquid:arsenic> * 1332, <liquid:nak> * 144);

SaltMixer.addRecipe(<liquid:arsenic> * 288, <liquid:nak> * 144, <liquid:arsenic_nak> * 144);
SaltMixer.addRecipe(<liquid:cryotheum> * 250, <liquid:liquid_helium> * 1000, <liquid:hecryo_liquid> * 1000);

ChemicalReactor.removeRecipeWithInput(<liquid:boron> * 72, <liquid:arsenic> * 333);
ChemicalReactor.removeRecipeWithInput(<liquid:liquidhydrogen> * 250, <liquid:fluorine> * 250);
ChemicalReactor.removeRecipeWithInput(<liquid:sulfur> * 333, <liquid:hydrogen> * 500);
ChemicalReactor.removeRecipeWithInput(<liquid:sodium> * 144, <liquid:sulfur> * 333);
ChemicalReactor.removeRecipeWithInput(<liquid:potassium> * 144, <liquid:sulfur> * 333);
ChemicalReactor.removeRecipeWithInput(<liquid:sulfur> * 333, <liquid:oxygen> * 500);

ChemicalReactor.addRecipe(<liquid:nitric_acid> * 250, <liquid:hydrofluoric_acid> * 750, <liquid:aqua_fluoride> * 1000, null);
ChemicalReactor.addRecipe(<liquid:nitric_acid> * 250, <liquid:liquidhydrofluricacid> * 750, <liquid:aqua_fluoride> * 1000, null);
ChemicalReactor.addRecipe(<liquid:gallium_phosphide> * 333, <liquid:indium_phosphide> * 333, <liquid:gallium_indium_phosphide> * 72, null);
ChemicalReactor.addRecipe(<liquid:hydrogen_fluoride> * 250, <liquid:water> * 250, <liquid:hydrofluoric_acid> * 250, null);
ChemicalReactor.addRecipe(<liquid:liquidhydrogenchloride> * 250, <liquid:water> * 250, <liquid:hydrochloric_acid> * 250, null);
ChemicalReactor.addRecipe(<liquid:sulfur> * 36, <liquid:hydrogen> * 250, <liquid:hydrogen_sulfide> * 250, null);
ChemicalReactor.addRecipe(<liquid:sodium> * 144, <liquid:sulfur> * 72, <liquid:sodium_sulfide> * 72, null);
ChemicalReactor.addRecipe(<liquid:potassium> * 144, <liquid:sulfur> * 72, <liquid:potassium_sulfide> * 72, null);
ChemicalReactor.addRecipe(<liquid:hydrogen> * 250, <liquid:liquidchlorine> * 250, <liquid:liquidhydrogenchloride> * 500, null);
ChemicalReactor.addRecipe(<liquid:hydrogen> * 250, <liquid:fluorine> * 250, <liquid:hydrogen_fluoride> * 500, null);
ChemicalReactor.addRecipe(<liquid:boron> * 72, <liquid:arsenic> * 72, <liquid:bas> * 333, null);
ChemicalReactor.addRecipe(<liquid:burningsulfurflow> * 36, <liquid:oxygen> * 250, <liquid:sulfur_dioxide> * 250, null);
ChemicalReactor.addRecipe(<liquid:ammonia> * 400, <liquid:oxygen> * 500, <liquid:nitrogen_oxide> * 400, <liquid:water> * 600);
ChemicalReactor.addRecipe(<liquid:nitrogen_oxide> * 500, <liquid:oxygen> * 250, <liquid:nitrogen_dioxide> * 500, null);
ChemicalReactor.addRecipe(<liquid:nitrogen_dioxide> * 750, <liquid:water> * 250, <liquid:nitric_acid> * 500, <liquid:nitrogen_oxide> * 250);
ChemicalReactor.addRecipe(<liquid:methane> * 250, <liquid:fluorine> * 250, <liquid:fluoromethane> * 250, <liquid:hydrogen_fluoride> * 250);
ChemicalReactor.addRecipe(<liquid:methane> * 250, <liquid:liquidchlorine> * 250, <liquid:chloromethane> * 250, <liquid:liquidhydrogenchloride> * 250);
ChemicalReactor.addRecipe(<liquid:chloromethane> * 250, <liquid:liquidchlorine> * 250, <liquid:dichloromethane> * 250, <liquid:liquidhydrogenchloride> * 250);
ChemicalReactor.addRecipe(<liquid:dichloromethane> * 250, <liquid:liquidchlorine> * 250, <liquid:trichloromethane> * 250, <liquid:liquidhydrogenchloride> * 250);
ChemicalReactor.addRecipe(<liquid:trichloromethane> * 250, <liquid:liquidchlorine> * 250, <liquid:carbon_tetrachloride> * 250, <liquid:liquidhydrogenchloride> * 250);
ChemicalReactor.addRecipe(<liquid:rich_brine> * 1000, <liquid:liquidchlorine> * 500, <liquid:poor_brine> * 750, <liquid:halogen_brine> * 250);
ChemicalReactor.addRecipe(<liquid:iodine_solution> * 1000, <liquid:carbon_tetrachloride> * 200, <liquid:water> * 1000, <liquid:iodine_carbon_tetrachloride_solution> * 200);
ChemicalReactor.addRecipe(<liquid:halogen_brine> * 100, <liquid:sulfur_dioxide> * 100, <liquid:bromine_gas> * 800, <liquid:iodine_solution> * 100);
ChemicalReactor.addRecipe(<liquid:platinum> * 72, <liquid:liquidchlorine> * 1000, <liquid:platinum_chloride> * 333, null);
ChemicalReactor.addRecipe(<liquid:platinum_chloride> * 333, <liquid:hydrochloric_acid> * 1000, <liquid:chloroplatinic_acid_solution> * 333, null);
ChemicalReactor.addRecipe(<liquid:chloroplatinic_acid_solution> * 333, <liquid:sodium_hydroxide_solution> * 666, <liquid:sodium_chloroplatinate_solution> * 333, null);
ChemicalReactor.addRecipe(<liquid:calcium_hydroxide_solution> * 333, <liquid:hydrochloric_acid> * 1000, <liquid:calcium_chloride_solution> * 333, null);
ChemicalReactor.addRecipe(<liquid:strontium_sulfide_solution> * 333, <liquid:hydrochloric_acid> * 1000, <liquid:strontium_chloride_solution> * 333, <liquid:hydrogen_sulfide> * 500);
ChemicalReactor.addRecipe(<liquid:barium_sulfide_solution> * 333, <liquid:hydrochloric_acid> * 1000, <liquid:barium_chloride_solution> * 333, <liquid:hydrogen_sulfide> * 500);
ChemicalReactor.addRecipe(<liquid:hydrogen_sulfide> * 250, <liquid:oxygen> * 375, <liquid:water> * 250, <liquid:sulfur_dioxide> * 250);
ChemicalReactor.addRecipe(<liquid:liquidgallium> * 72, <liquid:phosphorus> * 72, <liquid:gallium_phosphide> * 333, null);
ChemicalReactor.addRecipe(<liquid:indium> * 72, <liquid:phosphorus> * 72, <liquid:indium_phosphide> * 333, null);
ChemicalReactor.addRecipe(<liquid:phosphine> * 1000, <liquid:oxygen> * 750, <liquid:phosphorus_pentaoxide> * 333, <liquid:water> * 1500);
ChemicalReactor.addRecipe(<liquid:phosphorus> * 144, <liquid:oxygen> * 1250, <liquid:phosphorus_pentaoxide> * 333, null);
ChemicalReactor.addRecipe(<liquid:phosphorus_pentaoxide> * 333, <liquid:water> * 1500, <liquid:phosphoric_acid> * 1000, null);
ChemicalReactor.addRecipe(<liquid:phosphoric_acid> * 500, <liquid:sodium_hydroxide_solution> * 333, <liquid:sodium_dihydrogen_phosphate_solution> * 333, <liquid:water> * 500);
ChemicalReactor.addRecipe(<liquid:sodium_dihydrogen_phosphate_solution> * 333, <liquid:sodium_hydroxide_solution> * 333, <liquid:sodium_hydrogen_phosphate_solution> * 333, <liquid:water> * 500);
ChemicalReactor.addRecipe(<liquid:sodium_hydrogen_phosphate_solution> * 333, <liquid:sodium_hydroxide_solution> * 333, <liquid:sodium_phosphate_solution> * 333, <liquid:water> * 500);
ChemicalReactor.addRecipe(<liquid:magnesium> * 72, <liquid:sulfuric_acid> * 500, <liquid:magnesium_sulfate_solution> * 333, <liquid:hydrogen> * 500);
ChemicalReactor.addRecipe(<liquid:zinc> * 72, <liquid:liquidchlorine> * 500, <liquid:zinc_chloride> * 333, null);
ChemicalReactor.addRecipe(<liquid:manganese> * 72, <liquid:liquidchlorine> * 500, <liquid:manganese_chloride> * 333, null);
ChemicalReactor.addRecipe(<liquid:iron> * 72, <liquid:sulfuric_acid> * 500, <liquid:iron_2_sulfate_solution> * 333, <liquid:hydrogen> * 500);
ChemicalReactor.addRecipe(<liquid:zinc_chloride> * 333, <liquid:water> * 500, <liquid:zinc_chloride_solution> * 333, null);
ChemicalReactor.addRecipe(<liquid:manganese_chloride> * 333, <liquid:water> * 500, <liquid:manganese_chloride_solution> * 333, null);
ChemicalReactor.addRecipe(<liquid:molybdenum> * 72, <liquid:oxygen> * 750, <liquid:molybdenum_trioxide> * 333, null);
ChemicalReactor.addRecipe(<liquid:molybdenum_trioxide> * 333, <liquid:sodium_hydroxide_solution> * 666, <liquid:sodium_molybdate_solution> * 333, <liquid:water> * 500);
ChemicalReactor.addRecipe(<liquid:rich_brine> * 500, <liquid:ammonia> * 500, <liquid:ammonia_brine> * 500, null);

Crystallizer.addRecipe(<liquid:iodine_carbon_tetrachloride_solution> * 200, <jaopca:dust.iodine>);
Crystallizer.addRecipe(<liquid:chloroplatinic_acid_solution> * 666, <additions:chloroplatinic_acid>);
Crystallizer.addRecipe(<liquid:sodium_chloroplatinate_solution> * 666, <additions:sodium_chloroplatinate>);
Crystallizer.addRecipe(<liquid:calcium_hydroxide_solution> * 666, <additions:calcium_hydroxide>);
Crystallizer.addRecipe(<liquid:strontium_sulfide_solution> * 666, <additions:strontium_sulfide>);
Crystallizer.addRecipe(<liquid:barium_sulfide_solution> * 666, <additions:barium_sulfide>);
Crystallizer.addRecipe(<liquid:calcium_chloride_solution> * 666, CaCl2);
Crystallizer.addRecipe(<liquid:strontium_chloride_solution> * 666, SrCl2);
Crystallizer.addRecipe(<liquid:barium_chloride_solution> * 666, BaCl2);
Crystallizer.addRecipe(<liquid:sodium_phosphate_solution> * 666, <additions:sodium_phosphate>);
Crystallizer.addRecipe(<liquid:sodium_dihydrogen_phosphate_solution> * 666, <additions:sodium_dihydrogen_phosphate>);
Crystallizer.addRecipe(<liquid:sodium_hydrogen_phosphate_solution> * 666, <additions:sodium_hydrogen_phosphate>);
Crystallizer.addRecipe(<liquid:ammonium_chloride_solution> * 666, <additions:ammonium_chloride>);
Crystallizer.addRecipe(<liquid:magnesium_sulfate_solution> * 666, <additions:magnesium_sulfate>);
Crystallizer.addRecipe(<liquid:iron_2_sulfate_solution> * 666, <additions:iron_2_sulfate>);
Crystallizer.addRecipe(<liquid:zinc_chloride_solution> * 666, <additions:zinc_chloride>);
Crystallizer.addRecipe(<liquid:manganese_chloride_solution> * 666, <additions:manganese_chloride>);
Crystallizer.addRecipe(<liquid:sodium_hydrogen_carbonate_solution> * 666, <additions:sodium_hydrogen_carbonate>);
Crystallizer.addRecipe(<liquid:sodium_molybdate_solution> * 666, <additions:sodium_molybdate>);

Enricher.addRecipe(<ore:dustIodine>, <liquid:carbon_tetrachloride> * 200, <liquid:iodine_carbon_tetrachloride_solution> * 200);
Enricher.addRecipe(<ore:ingotIodine>, <liquid:carbon_tetrachloride> * 200, <liquid:iodine_carbon_tetrachloride_solution> * 200);
Enricher.addRecipe(<ore:dustChloroplatinicAcid>, <liquid:water> * 1000, <liquid:chloroplatinic_acid_solution> * 666);
Enricher.addRecipe(<ore:dustSodiumChloroplatinate>, <liquid:water> * 1000, <liquid:sodium_chloroplatinate_solution> * 666);
Enricher.addRecipe(<ore:dustCalciumOxide>, <liquid:water> * 1500, <liquid:calcium_hydroxide_solution> * 666);
Enricher.addRecipe(<ore:dustCalciumHydroxide>, <liquid:water> * 1000, <liquid:calcium_hydroxide_solution> * 666);
Enricher.addRecipe(<ore:dustCalciumChloride>, <liquid:water> * 1000, <liquid:calcium_chloride_solution> * 666);
Enricher.addRecipe(<ore:dustStrontiumChloride>, <liquid:water> * 1000, <liquid:strontium_chloride_solution> * 666);
Enricher.addRecipe(<ore:dustBariumChloride>, <liquid:water> * 1000, <liquid:barium_chloride_solution> * 666);
Enricher.addRecipe(<ore:dustStrontiumSulfide>, <liquid:water> * 1000, <liquid:strontium_sulfide_solution> * 666);
Enricher.addRecipe(<ore:dustBariumSulfide>, <liquid:water> * 1000, <liquid:barium_sulfide_solution> * 666);
Enricher.addRecipe(<ore:dustSodiumPhosphate>, <liquid:water> * 1000, <liquid:sodium_phosphate_solution> * 666);
Enricher.addRecipe(<ore:dustSodiumDihydrogenPhosphate>, <liquid:water> * 1000, <liquid:sodium_dihydrogen_phosphate_solution> * 666);
Enricher.addRecipe(<ore:dustSodiumHydrogenPhosphate>, <liquid:water> * 1000, <liquid:sodium_hydrogen_phosphate_solution> * 666);
Enricher.addRecipe(<ore:dustPhosphorusPentaoxide>, <liquid:water> * 3000, <liquid:phosphoric_acid> * 2000);
Enricher.addRecipe(<ore:dustAmmoniumChloride>, <liquid:water> * 1000, <liquid:ammonium_chloride_solution> * 666);
Enricher.addRecipe(<ore:dustMagnesiumSulfate>, <liquid:water> * 1000, <liquid:magnesium_sulfate_solution> * 666);
Enricher.addRecipe(<ore:dustIron(II)Sulfate>, <liquid:water> * 1000, <liquid:iron_2_sulfate_solution> * 666);
Enricher.addRecipe(<ore:dustZincChloride>, <liquid:water> * 1000, <liquid:zinc_chloride_solution> * 666);
Enricher.addRecipe(<ore:dustManganeseChloride>, <liquid:water> * 1000, <liquid:manganese_chloride_solution> * 666);
Enricher.addRecipe(<ore:dustSodiumHydrogenCarbonate>, <liquid:water> * 1000, <liquid:sodium_hydrogen_carbonate_solution> * 666);
Enricher.addRecipe(<ore:dustCryotheum>, <liquid:liquid_helium> * 1000, <liquid:hecryo_liquid> * 1000);
Enricher.addRecipe(<ore:dustSodiumMolybdate>, <liquid:water> * 1000, <liquid:sodium_molybdate_solution> * 666);

Electrolyzer.addRecipe(<liquid:brine> * 1000, <liquid:sodium_hydroxide_solution> * 666, <liquid:hydrogen> * 500, <liquid:liquidchlorine> * 500, null, 1.0d, 1.0d, 0.0d);
Electrolyzer.addRecipe(<liquid:sodium_chloride> * 333, <liquid:sodium> * 72, <liquid:liquidchlorine> * 250, null, null);
Electrolyzer.addRecipe(<liquid:potassium_chloride> * 333, <liquid:potassium> * 72, <liquid:liquidchlorine> * 250, null, null, 1.5d, 2.0d);
Electrolyzer.addRecipe(<liquid:rubidium_chloride> * 333, <liquid:rubidium> * 72, <liquid:liquidchlorine> * 250, null, null, 5.0d, 15.0d);
Electrolyzer.addRecipe(<liquid:cesium_chloride> * 333, <liquid:caesium> * 72, <liquid:liquidchlorine> * 250, null, null, 7.0d, 20.0d);
Electrolyzer.addRecipe(<liquid:platinum_chloride> * 333, <liquid:platinum> * 72, <liquid:liquidchlorine> * 1000, null, null);
Electrolyzer.addRecipe(<liquid:hydrochloric_acid> * 500, <liquid:hydrogen> * 250, <liquid:liquidchlorine> * 250, null, null);
Electrolyzer.addRecipe(<liquid:calcium_chloride> * 333, <liquid:calcium> * 72, <liquid:liquidchlorine> * 500, null, null, 1.5d, 2.0d);
Electrolyzer.addRecipe(<liquid:strontium_chloride> * 333, <liquid:strontium> * 72, <liquid:liquidchlorine> * 500, null, null, 3.0d, 6.0d);
Electrolyzer.addRecipe(<liquid:barium_chloride> * 333, <liquid:barium> * 72, <liquid:liquidchlorine> * 500, null, null, 4.5d, 10.0d);

Centrifuge.removeRecipeWithInput(<liquid:arsenic_nak> * 144);

Centrifuge.addRecipe(<liquid:arsenic_nak> * 144, <liquid:arsenic> * 288, <liquid:nak> * 144, null, null, null, null);
Centrifuge.addRecipe(<liquid:mixed_hydrocarbon> * 1000, <liquid:methane> * 500, <liquid:ethene> * 250, <liquid:ethylene> * 250, null, null, null);

Supercooler.addRecipe(<liquid:bromine_gas> * 8000, <liquid:bromine> * 25, 0.9d, 1.0d, 0.0d);
Supercooler.addRecipe(<liquid:hydrogen> * 8000, <liquid:liquid_hydrogen> * 25, 1.0d, 1.0d, 0.0d);
Supercooler.addRecipe(<liquid:nitrogen> * 8000, <liquid:liquid_nitrogen> * 25, 1.0d, 1.0d, 0.0d);
Supercooler.addRecipe(<liquid:oxygen> * 8000, <liquid:liquid_oxygen> * 25, 1.0d, 1.0d, 0.0d);
Supercooler.addRecipe(<liquid:fluorine> * 8000, <liquid:liquid_fluorine> * 25, 1.0d, 1.0d, 0.0d);
Supercooler.addRecipe(<liquid:neon> * 8000, <liquid:liquid_neon> * 25, 1.0d, 1.0d, 0.0d);
Supercooler.addRecipe(<liquid:liquidchlorine> * 8000, <liquid:liquid_chlorine> * 25, 1.0d, 1.0d, 0.0d);
Supercooler.addRecipe(<liquid:argon> * 8000, <liquid:liquid_argon> * 25, 1.0d, 1.0d, 0.0d);
Supercooler.addRecipe(<liquid:krypton> * 8000, <liquid:liquid_krypton> * 25, 1.0d, 1.0d, 0.0d);
Supercooler.addRecipe(<liquid:xenon> * 8000, <liquid:liquid_xenon> * 25, 1.0d, 1.0d, 0.0d);
Supercooler.addRecipe(<liquid:radon> * 8000, <liquid:liquid_radon> * 25, 1.0d, 1.0d, 0.000004d);

Separator.addRecipe(<ore:dustSodiumChloroplatinate>, PtCl4, NaCl * 2);
Separator.addRecipe(<ore:dustPotassiumChloroplatinate>, PtCl4, KCl * 2);
Separator.addRecipe(<ore:dustRubidiumChloroplatinate>, PtCl4, RbCl * 2);
Separator.addRecipe(<ore:dustCesiumChloroplatinate>, PtCl4, CsCl * 2);

Radiation.setMaterialRadiationLevel("Technetium", 0.000000000985d);
Radiation.setMaterialRadiationLevel("Promethium", 0.064d);
Radiation.setMaterialRadiationLevel("Astatine", 1.28d);
Radiation.setMaterialRadiationLevel("Radon", 0.000032d);
Radiation.setMaterialRadiationLevel("Francium", 0.144d);
Radiation.setMaterialRadiationLevel("Actinium", 0.00054d);
Radiation.setMaterialRadiationLevel("Protactinium", 1.4d);
Radiation.setMaterialRadiationLevel("Neptunium", 0.00000025d);
Radiation.setMaterialRadiationLevel("Americium", 0.00086d);
Radiation.setMaterialRadiationLevel("Curium", 0.00027d);
Radiation.setMaterialRadiationLevel("Berkelium", 0.00095d);
Radiation.setMaterialRadiationLevel("Californium", 0.004d);
Radiation.setMaterialRadiationLevel("Einsteinium", 0.006d);
Radiation.setMaterialRadiationLevel("Fermium", 0.0085d);
Radiation.setMaterialRadiationLevel("Mendelevium", 0.009d);
Radiation.setMaterialRadiationLevel("Nobelium", 0.015d);
Radiation.setMaterialRadiationLevel("Lawrencium", 0.02d);
Radiation.setMaterialRadiationLevel("Rutherfordium", 0.032d);
Radiation.setMaterialRadiationLevel("Dubnium", 0.048d);
Radiation.setMaterialRadiationLevel("Seaborgium", 0.06d);
Radiation.setMaterialRadiationLevel("Bohrium", 0.072d);
Radiation.setMaterialRadiationLevel("Hassium", 0.085d);
Radiation.setMaterialRadiationLevel("Meitnerium", 0.11d);
Radiation.setMaterialRadiationLevel("Darmstadtium", 0.16d);
Radiation.setMaterialRadiationLevel("Roentgenium", 0.2d);
Radiation.setMaterialRadiationLevel("Copernicium", 0.25d);
Radiation.setMaterialRadiationLevel("Nihonium", 0.29d);
Radiation.setMaterialRadiationLevel("Flerovium", 0.34d);
Radiation.setMaterialRadiationLevel("Moscovium", 0.40d);
Radiation.setMaterialRadiationLevel("Livermorium", 0.49d);
Radiation.setMaterialRadiationLevel("Tennessine", 0.55d);
Radiation.setMaterialRadiationLevel("Oganesson", 0.64d);

Radiation.setMaterialRadiationLevel("Iridium192", 0.0000018d);
Radiation.setMaterialRadiationLevel("Irradium", 0.00085d);
Radiation.setMaterialRadiationLevel("Nucleum", 0.000012d);