#loader preinit

#priority 1008

import mods.treetweaker.TreeFactory;

var evileye = TreeFactory.createTree("evileye");
evileye.setTreeType("CANOPY");
evileye.setLog("gct_additions:evileye_log");
evileye.setLeaf("gct_additions:evileye_leaves");
evileye.setMinHeight(6);
evileye.setExtraHeight(4);
evileye.setGenFrequency(5);
evileye.setGenAttempts(1);
evileye.extraThick = false;
evileye.setGenBiome("gct_additions:bloodyplain");
evileye.setBaseBlock("gct_additions:bloodygrass");
evileye.setDimWhitelist(41);
evileye.addSapling();
evileye.register();

var evileye2 = TreeFactory.createTree("evileye2");
evileye2.setTreeType("CANOPY");
evileye2.setLog("gct_additions:evileye_log");
evileye2.setLeaf("gct_additions:evileye_leaves");
evileye2.setMinHeight(6);
evileye2.setExtraHeight(4);
evileye2.setGenFrequency(5);
evileye2.setGenAttempts(1);
evileye2.extraThick = false;
evileye2.setGenBiome("gct_additions:curruptplain");
evileye2.setBaseBlock("gct_additions:corruptgrass");
evileye2.setDimWhitelist(41);
evileye2.register();

var livingwood = TreeFactory.createTree("livingwood");
livingwood.setTreeType("OAK");
livingwood.setLog("gct_additions:livingwood_log");
livingwood.setLeaf("gct_additions:livingwood_leaves");
livingwood.setMinHeight(4);
livingwood.setExtraHeight(1);
livingwood.setGenFrequency(1);
livingwood.setGenAttempts(6);
livingwood.extraThick = false;
livingwood.setGenBiome("gct_additions:mana_forest");
livingwood.setBaseBlock("gct_additions:mana_grass");
livingwood.setDimWhitelist(0);
livingwood.addSapling();
livingwood.register();

var mana_tree = TreeFactory.createTree("mana_tree");
mana_tree.setTreeType("LARGE_OAK");
mana_tree.setLog("gct_additions:mana_log");
mana_tree.setLeaf("gct_additions:mana_leaves");
mana_tree.setMinHeight(8);
mana_tree.setExtraHeight(6);
mana_tree.setGenFrequency(1);
mana_tree.setGenAttempts(2);
mana_tree.extraThick = false;
mana_tree.setGenBiome("gct_additions:mana_forest");
mana_tree.setBaseBlock("gct_additions:mana_grass");
mana_tree.setDimWhitelist(0);
mana_tree.addSapling();
mana_tree.register();

var livingwood2 = TreeFactory.createTree("livingwood2");
livingwood2.setTreeType("OAK");
livingwood2.setLog("gct_additions:livingwood_log");
livingwood2.setLeaf("gct_additions:livingwood_leaves");
livingwood2.setMinHeight(4);
livingwood2.setExtraHeight(1);
livingwood2.setGenFrequency(1);
livingwood2.setGenAttempts(6);
livingwood2.extraThick = false;
livingwood2.setGenBiome("gct_additions:mana_forest_hill");
livingwood2.setBaseBlock("gct_additions:mana_grass");
livingwood2.setDimWhitelist(0);
livingwood2.register();

var mana_tree2 = TreeFactory.createTree("mana_tree");
mana_tree2.setTreeType("LARGE_OAK");
mana_tree2.setLog("gct_additions:mana_log");
mana_tree2.setLeaf("gct_additions:mana_leaves");
mana_tree2.setMinHeight(8);
mana_tree2.setExtraHeight(6);
mana_tree2.setGenFrequency(1);
mana_tree2.setGenAttempts(2);
mana_tree2.extraThick = false;
mana_tree2.setGenBiome("gct_additions:mana_forest_hill");
mana_tree2.setBaseBlock("gct_additions:mana_grass");
mana_tree2.setDimWhitelist(0);
mana_tree2.register();

var dreamwood = TreeFactory.createTree("dreamwood");
dreamwood.setTreeType("OAK");
dreamwood.setLog("gct_additions:dreamwood_log");
dreamwood.setLeaf("gct_additions:dreamwood_leaves");
dreamwood.setMinHeight(4);
dreamwood.setExtraHeight(1);
dreamwood.setGenFrequency(1);
dreamwood.setGenAttempts(2);
dreamwood.extraThick = false;
dreamwood.setGenBiome("gct_additions:alfheim_forest");
dreamwood.setBaseBlock("gct_additions:alf_grass");
dreamwood.setDimWhitelist(42);
dreamwood.addSapling();
dreamwood.register();

var redreamwood = TreeFactory.createTree("redreamwood");
redreamwood.setTreeType("OAK");
redreamwood.setLog("gct_additions:reversed_dreamwood_log");
redreamwood.setLeaf("gct_additions:reversed_dreamwood_leaves");
redreamwood.setMinHeight(4);
redreamwood.setExtraHeight(1);
redreamwood.setGenFrequency(1);
redreamwood.setGenAttempts(2);
redreamwood.extraThick = false;
redreamwood.setGenBiome("gct_additions:reversed_forest");
redreamwood.setBaseBlock("gct_additions:reversed_alf_grass");
redreamwood.setDimWhitelist(42);
redreamwood.addSapling();
redreamwood.register();

var infused1 = TreeFactory.createTree("infused");
infused1.setTreeType("SPRUCE");
infused1.setLog("astralsorcery:blockinfusedwood");
infused1.setLeaf("gct_additions:wildplain_leaves");
infused1.setMinHeight(10);
infused1.setExtraHeight(6);
infused1.setGenFrequency(1);
infused1.setGenAttempts(2);
infused1.extraThick = false;
infused1.setGenBiome("gct_additions:cancer_hills");
infused1.setBaseBlock("gct_additions:lunar_grass");
infused1.setDimWhitelist(80);
infused1.register();

var infused2 = TreeFactory.createTree("infused2");
infused2.setTreeType("SPRUCE");
infused2.setLog("astralsorcery:blockinfusedwood");
infused2.setLeaf("gct_additions:wildplain_leaves");
infused2.setMinHeight(10);
infused2.setExtraHeight(6);
infused2.setGenFrequency(6);
infused2.setGenAttempts(2);
infused2.extraThick = false;
infused2.setGenBiome("gct_additions:virgo_plain");
infused2.setBaseBlock("gct_additions:lunar_grass");
infused2.setDimWhitelist(80);
infused2.register();

var infused3 = TreeFactory.createTree("infused3");
infused3.setTreeType("SPRUCE");
infused3.setLog("astralsorcery:blockinfusedwood");
infused3.setLeaf("gct_additions:wildplain_leaves");
infused3.setMinHeight(10);
infused3.setExtraHeight(6);
infused3.setGenFrequency(1);
infused3.setGenAttempts(2);
infused3.extraThick = false;
infused3.setGenBiome("gct_additions:gemini_valley");
infused3.setBaseBlock("gct_additions:lunar_grass");
infused3.setDimWhitelist(80);
infused3.register();
