/*
 * This script is created for the GreedyCraft modpack by TCreopargh.
 * You may NOT use this script in any other publicly distributed modpack without my permission.
 */

#priority 800

import crafttweaker.game.IGame;

import scripts.util.lang as LangUtil;

val localizationMap as string[string][string] = {
    zh_cn: {
        "jei.tofucraft.category.crusher": "豆腐能粉碎机",
        "jei.tofucraft.category.compressor": "豆腐压缩机",
        "jei.tofucraft.category.aggregator": "豆腐聚合器",
        "jei.tofucraft.category.advanced_aggregator": "高级豆腐聚合器",
        "dragon.minion": "龙之侍从",
        "dragon.larva": "龙之幼体",
        "wither.minion": "凋灵侍从",
        "material.adamant.name": "精金",
        "tile.adamant_block.name": "精金块",
        "tile.adamant_ore.name": "精金矿石",
        "item.adamant_nugget.name": "精金粒",
        "item.adamant_dust.name": "精金粉",
        "item.adamant_ingot.name": "精金锭",
        "fluid.tconstruct.adamant_fluid.name": "熔融精金",
        "item.itemcraftingcomponent.reso_gem.name": "共振海蓝宝石",
        "tile.thaumadditions:adaminite_smelter.name": "铿金源质冶炼厂",
        "tile.thaumadditions:jar_adaminite.name": "铿金源质罐子",
        "tile.thaumadditions:adaminite_block.name": "铿金块",
        "item.thaumadditions:adaminite_nugget.name": "铿金粒",
        "item.thaumadditions:adaminite_ingot.name": "铿金锭",
        "item.thaumadditions:adaminite_plate.name": "铿金板",
        "item.thaumadditions:adaminite_nugget.name": "铿金粒",
        "item.thaumadditions:adaminite_fabric.name": "铿金布匹",
        "item.thaumadditions:adaminite_sword.name": "铿金剑",
        "item.thaumadditions:adaminite_hood.name": "铿金神秘使兜帽",
        "item.thaumadditions:adaminite_robe.name": "铿金神秘使法袍",
        "item.thaumadditions:adaminite_belt.name": "铿金神秘使腰带",
        "item.thaumadditions:adaminite_boots.name": "铿金神秘使靴子",
        "item.slimeball.name": "绿色史莱姆球",
        "tile.solarflux:solar_panel_wyvern.name": "飞龙太阳能电池板",
        "research_name.thaumadditions:adaminite": "铿金金属",
        "research_stage.thaumadditions:adaminite.2": "我的实验已大获成功！书中它这种新造物称之为“铿金”。我都要疯了！我听说过灵液，神之血，但我认为这金属要远比灵液好，尽管它存在于这世上的任何地方。",
        "research_name.thaumadditions:adaminite_smelter": "铿金源质冶炼厂",
        "research_stage.thaumadditions:adaminite_smelter.2": "好啊！铿金似乎更好更高效！铿金源质冶炼厂现在能多产生 20% 源质。这意味着我可以更少的冶炼源质了。",
        "research_stage.thaumadditions:mithminite_smelter.1": "我想要改进铿金源质冶炼厂的质量并让它更快并且经常产生额外的源质。我知道秘金应该能有所帮助，并且我需要一点实验来确认我的想法是正确的。",
        "research_name.thaumadditions:adaminite_smelter": "铿金源质冶炼厂",
        "research_name.thaumadditions:adaminite_jar": "铿金源质罐子",
        "research_stage.thaumadditions:mithminite_jar.2": "我的结论是正确的，铿金罐子可以被秘金合金用一中复杂的注魔来觉醒, 这种新的（我希望是最终的）罐子可以装 4000 点源质，是铿金源质罐子的两倍。 我同时也注意到这罐子能销毁流入的多余源质，这可能对我的那些旧的虚空罐子是应该很不错的升级，而且这也不会因为源质溢出而爆炸。",
        "research_stage.thaumadditions:adaminite_jar.2": "铿金非常独特！我认为这个罐子可以容纳 2000 点源质，这使得它内部空间的源质十分稠密。",
        "research_stage.thaumadditions:adaminite_jar.3": "铿金非常独特！我认为这个罐子可以容纳 2000 点源质，这使得它内部空间的源质十分稠密。我听到一个叫泽尔西伦的人的声音，他是其中一位创世者，曾创造了这个世界。他轻声低语道：“这个罐子密度太大了，也许在某些特定的情况下会不稳定。我不认为把它完全装满源质是一个好主意...”。我从他的话语中也听出他非常惊讶于我所完成的这一艰难的挑战。",
        "research_stage.thaumadditions:mithminite_jar.1": "既然已我知晓了用秘银和一些水银可能可以觉醒铿金，我只需知道我能否负担得起这些秘金源质罐子。",
        "modifier.moretcon.corroding.name": "氧化",
        "modifier.gritty.name": "残痕",
        "modifier.splinters.name": "断裂",
        "modifier.fragile_changed.name": "脆化",
        "modifier.ported_changed.name": "交互",
        "modifier.ported.name": "交互",
        "modifier.tconevo.opportunist.name": "机会主义",
        "material.prometheum.name": "普罗姆",
        "tile.prometheum_block.name": "普罗姆块",
        "tile.prometheum_ore.name": "普罗姆矿石",
        "item.prometheum_nugget.name": "普罗姆粒",
        "item.prometheum_dust.name": "普罗姆粉",
        "item.prometheum_ingot.name": "普罗姆锭",
        "fluid.tconstruct.prometheum_fluid.name": "熔融普罗姆",
        "tile.zensummoning.altar.name": "铸造祭坛",
        "material.duranite.name": "耐力金属",
        "tile.duranite_block.name": "耐力金属块",
        "tile.duranite_ore.name": "耐力金属矿石",
        "item.duranite_nugget.name": "耐力金属粒",
        "item.duranite_dust.name": "耐力金属粉",
        "item.duranite_ingot.name": "耐力金属锭",
        "fluid.tconstruct.duranite_fluid.name": "熔融耐力金属",
        "material.niob.name": "尼博",
        "tile.niob_block.name": "尼博块",
        "item.niob_nugget.name": "尼博粒",
        "item.niob_dust.name": "尼博粉",
        "item.niob_ingot.name": "尼博锭",
        "fluid.tconstruct.niob_fluid.name": "熔融尼博",
        "jaopca.entry.Ambrosium": "神能晶",
        "modifier.curvature.name": "曲度",
        "tile.mist.niobium_ore": "铌矿石",
        "tile.mist.gold_ore": "朦胧金矿石",
        "tile.mist.iron_ore": "朦胧铁矿石",
        "tile.mist.sulfur_ore": "朦胧硫磺矿石",
        "tile.mist.saltpeter_ore": "朦胧硝石矿石",
        "tile.mist.r_tree_trunk": "橡胶树原木",
        "tile.mist.r_tree_leaves": "橡胶树树叶",
        "thaumicaugmentation.text.entered_void": "你拜访了无尽的虚空。",
        "thaumicaugmentation.text.mountain": "你拜访了一座高山。",
        "thaumicaugmentation.text.desert": "你拜访了一片荒漠。",
        "thaumicaugmentation.text.ocean": "你拜访了一片大海。",
        "thaumicaugmentation.text.forest": "你拜访了一片森林。",
        "thaumicaugmentation.text.impetus_damage": "你感受到了冲力带来的震撼。",
        "thaumicaugmentation.text.long_time_in_water": "你逐渐地适应了深水的压力。",
        "thaumicaugmentation.text.entered_spire": "你发现了%s。",
        "thaumicaugmentation.text.boss_room_spire": "你发现了尖塔的核心。",
        "death.attack.cinderSpark": "%s被%s的火球烧成了灰烬。",
        "botania_tweaks.entrodupe.nicetry": "TNT复制机？给爷爪巴。爷不吃这套。",
        "item.withered_nether_star.name": "暗黑下界之星",
        "entity.ChaosGuardianHelpful.name": "秩序守护使",
        "fluid.fusion_matrix": "熔融聚合矩阵",
        "fluid.insanium": "熔融究极精华",
        "jaopca.entry.Infernium": "永燃",
        "jaopca.entry.Titanium": "钛",
        "jaopca.entry.LiquifiedCoralium": "精炼珊瑚",
        "fluid.cryonium": "熔融极寒",
        "jaopca.entry.Cryonium": "极寒",
        "jaopca.entry.Experience": "知识精华",
        "fluid.ethaxium": "熔融伊桑斯",
        "jaopca.entry.Cytosinite": "胞嘧",
        "jaopca.entry.Umbrium": "影素",
        "jaopca.entry.Hephaestite": "赫菲斯辛",
        "jaopca.entry.Scarlite": "绯红宝石",
        "jaopca.entry.Chromium": "铬",
        "jaopca.entry.Aqualite": "水华",
        "fluid.mithrillium": "熔融秘银",
        "fluid.adaminite": "熔融铿金",
        "fluid.mithminite": "熔融秘金",
        "fluid.ravaging": "毁灭流质",
        "fluid.gaia": "熔融盖亚魂锭",
        "fluid.terra_alloy": "熔融大地合金",
        "fluid.cosmilite": "寰宇超流体",
        "fluid.astral_metal": "星辰涌流",
        "fluid.orichalcos": "熔融奥利哈刚",
        "fluid.netherite": "熔融下界合金",
        "fluid.ancient_debris": "熔融远古残骸",
        "fluid.scorched": "熔融高炉砖",
        "fluid.organic_fluid": "有机液",
        "fluid.poison": "毒液",
        "fluid.modularium": "熔融模块化合金",
        "fluid.ignite": "熔融炽星",
        "fluid.stainless_steel": "熔融不锈钢",
        "fluid.protonium": "极密质子流体",
        "fluid.electronium": "粘性电子流质",
        "fluid.crimsonite": "猩红浆液",
        "fluid.manganese_steel": "熔融锰钢",
        "fluid.durasteel": "熔融耐钢",
        "fluid.aeonsteel": "熔融恒钢",
        "fluid.chromasteel": "熔融炫钢",
        "fluid.spectre": "灵魂之泉",
        "fluid.gaiasteel": "熔融盖亚钢",
        "fluid.blackiron": "熔融黑铁",
        "fluid.heavenite": "熔融穹金",
        "fluid.ghostite": "熔融鬼金",
        "fluid.waringlium": "熔融瓦伦格尔",
        "fluid.tierite": "熔融缠绕合金",
        "fluid.cheatieum": "熔融诡术合金",
        "fluid.idiessite": "熔融伊迪斯",
        "fluid.cthughate": "燋燎之火焰",
        "fluid.ranglium": "熔融峦金",
        "fluid.godiarite": "熔融天佑合金",
        "fluid.rainite": "熔融暴雨合金",
        "fluid.panloeseum": "熔融潘洛斯",
        "fluid.husturite": "无名之疾风",
        "fluid.fallenium": "熔融落金",
        "fluid.phoenixite": "熔融凤凰合金",
        "fluid.depthite": "熔融深邃合金",
        "fluid.lovaquite": "熔融洛瓦克",
        "fluid.rangolarite": "熔融朗格拉",
        "fluid.clearite": "熔融晴天合金",
        "fluid.wefenium": "熔融尖晶",
        "fluid.errorite": "熔融错误合金",
        "fluid.numbereum": "熔融数字合金",
        "fluid.treasurite": "熔融宝金",
        "fluid.leadite": "熔融导金",
        "fluid.martisite": "熔融战神合金",
        "fluid.flashite": "熔融闪金",
        "fluid.overlaite": "熔融叠金",
        "fluid.rupee": "熔融卢比",
        "fluid.realmite": "熔融诺米特",
        "fluid.arlemite": "熔融阿勒米特",
        "fluid.shadow_bar": "熔融阴影",
        "fluid.hellstone": "熔融罪恶",
        "fluid.lava_solid": "熔融固态岩浆",
        "fluid.aquatic": "熔融海洋结晶",
        "fluid.balancite": "熔融守恒合金",
        "fluid.glowing_signalum": "熔融荧光信素",
        "fluid.fallen_metal": "堕落聚合物",
        "fluid.relifed_metal": "重生聚合物",
        "fluid.stormy_metal": "风暴解构质",
        "fluid.ordered_metal": "秩序超流质",
        "fluid.finallium": "终焉灵体液",
        "fluid.eden": "熔融伊甸",
        "fluid.wildwood": "熔融原始",
        "fluid.apalachia": "熔融阿帕拉契亚",
        "fluid.skythern": "熔融冰刺",
        "fluid.mortum": "熔融黑金",
        "fluid.twilight_crystal": "熔融暮光结晶",
        "fluid.hellcrust":"熔融焦岩",
        "fluid.umbra":"熔融本影",
        "fluid.crystalline":"熔融月凝晶",
        "fluid.aurorianite":"熔融极光",
        "fluid.niobium":"熔融铌",
        "fluid.horizonite":"熔融炎铁",
        "fluid.falsite":"熔融伪匿",
        "fluid.ventium":"熔融风腾",
        "fluid.apocalypsium": "熔融天启",
        "fluid.sanite": "熔融灵神钢",
        "fluid.harcadium": "熔融末晶",
        "fluid.void_essence": "熔融虚空精华",
        "fluid.adamantium": "熔融艾德曼合金",
        "fluid.hellite": "熔融炼狱金属",
        "fluid.blackhole_alloy": "熔融黑洞合金",
        "fluid.creative_alloy": "熔融创世合金",
        "fluid.ruthenium": "熔融钌",
        "fluid.rhodium": "熔融铑",
        "fluid.porpezite": "熔融钯金",
        "fluid.raisium": "熔融扬升合金",
        "fluid.astronicium": "熔融太空合金",
        "fluid.compressite": "熔融极密合金",
        "fluid.dullium": "熔融沉黯",
        "fluid.daynight": "熔融昼夜合金",
        "fluid.mythsteel": "熔融神话钢",
        "fluid.cthulhurite": "深海之呼吸",
        "fluid.elfsteel": "熔融精灵钢",
        "fluid.chillinium": "熔融寒心铁",
        "fluid.iciricium": "熔融冰纹金",
        "fluid.moltenium": "熔融炎熔晶",
        "fluid.typhoonite": "熔融飓风合金",
        "fluid.thermallite": "极致炽热流体",
        "fluid.photonium": "光子纠缠流质",
        "fluid.mercury": "液汞",
        "fluid.enderiron": "熔融末影镀层铁",
        "fluid.enderironex": "熔融增强末影",
        "fluid.crystaltine": "稳定水晶流体",
        "fluid.azathothium": "痴愚之狂乱",
        "fluid.nyarlathotepium": "伏行之混沌",
        "fluid.yogsothothium": "归一之时空",
        "fluid.shubniggurathium": "孕育之黑暗",
        "fluid.rubidium": "熔融铷",
        "fluid.caesium": "熔融铯",
        "fluid.francium": "熔融钫",
        "fluid.zodiacite": "星灵拟态流质",
        "fluid.pe": "液体位能",
        "fluid.nasalum": "熔融星空",
        "fluid.lunarine": "熔融月华",
        "fluid.wigthium": "阴魂浆液",
        "fluid.darkest": "至暗浆液",
        "fluid.murderite": "血渊浆液",
        "fluid.ghost_metal": "熔融恶灵金属",
        "fluid.impetusite": "熔融元动金属",
        "fluid.eldritch_steel": "熔融邪术钢",
        "fluid.corruptium": "熔融腐化金属",
        "fluid.cursium": "熔融咒缚",
        "fluid.botanical": "熔融植物魂",
        "fluid.botanical_awakened": "熔融觉醒植物魂",
        "fluid.rosium": "熔融血玫瑰",
        "fluid.chrysanthemium": "熔融金雏菊",
        "fluid.dandelionium": "熔融蒲公英",
        "fluid.myosotisium": "熔融勿忘我",
        "fluid.begonium": "熔融秋海棠",
        "fluid.carnationium": "熔融康乃馨",
        "fluid.star_alloy": "共晶星链物质",
        "fluid.resonant_debris": "熔融共鸣残骸",
        "fluid.enderite": "熔融末影合金",
        "fluid.frostburn_metal": "霜炙化合物",
        "fluid.eucite": "熔融桉金",
        "fluid.corbite": "熔融尘金",
        "fluid.disaster_metal": "天灾共聚物",
        "fluid.scientificite": "科幻悬浊液",
        "fluid.abyssine": "深渊污浊流质",
        "fluid.wolframium": "熔融钨",
        "fluid.phosphorus": "磷蒸气",
        "fluid.clock_alloy": "熔融时钟合金",
        "fluid.twilit_alloy": "熔融黄昏合金",
        "fluid.mist_alloy": "熔融迷踪合金",
        "fluid.sharpen_alloy": "熔融锐化合金",
        "fluid.killer_alloy": "熔融杀戮合金",
        "fluid.curse_alloy": "熔融灾祸合金",
        "fluid.legendite": "熔融荣耀合金",
        "fluid.holysteel": "熔融神圣钢",
        "fluid.earth": "熔融大地",
        "fluid.aurune": "熔融灵蕴金属",
        "fluid.sorrowium": "殇魂流质",
        "fluid.undead": "不死流质",
        "fluid.darkice": "灼热黑冰",
        "fluid.calcium": "熔融钙",
        "fluid.strontium": "熔融锶",
        "fluid.barium": "熔融钡",
        "fluid.radium": "熔融镭",
        "fluid.plutonium": "熔融钚",
        "fluid.endusium": "熔融聚影铁",
        "fluid.holium": "熔融圣金",
        "fluid.apollonium": "熔融太阳神",
        "fluid.uracilite": "熔融尿嘧",
        "fluid.germanium": "熔融锗",
        "fluid.silicon": "熔融硅",
        "fluid.carbon": "熔融碳",
        "fluid.flamium": "熔融炎心铁",
        "fluid.eugardite": "熔融神光合金",
        "fluid.neptunium": "熔融镎",
        "fluid.bismuth": "熔融铋",
        "fluid.gravity_debris": "熔融重力残骸",
        "fluid.aetherite": "熔融天境合金",
        "fluid.flux": "拟态通量流质",
        "fluid.unshapable_liquid": "不定形流质",
        "fluid.endest_steel": "熔融终影钢",
        "fluid.fracturite": "熔融解构金属",
        "fluid.queenslime": "熔融皇后史莱姆",
        "fluid.emperorslime": "熔融帝皇史莱姆",
        "fluid.godslime": "熔融创神史莱姆",
        "fluid.twilit": "暮色集合流质",
        "fluid.betwnite": "熔融交错钢",
        "fluid.ascensionite": "熔融虚无合金",
        "fluid.iodine": "熔融碘",
        "fluid.pruified": "纯净流体",
        "fluid.wavite": "波动熔胶",
        "fluid.rose_gold": "熔融玫瑰金",
        "fluid.ruled_draconium": "熔融守则龙素",
        "fluid.relifed_witherium": "熔融复活凋灵",
        "fluid.stormy_witherium": "熔融风暴凋灵",
        "fluid.equipment_witherium": "熔融平衡凋灵",
        "fluid.phosphorus_pentaoxide": "熔融五氧化二磷",
        "fluid.zinc_chloride": "熔融氯化锌",
        "fluid.manganese_chloride": "熔融氯化锰",
        "fluid.molybdenum_trioxide": "熔融三氧化钼",
        "fluid.deusiotium": "熔融神人金属",
        "fluid.blue_alloy": "熔融蓝晶合金",
        "fluid.eco_basic_alloy": "熔融ECO基础合金",
        //化工相关液体
        "fluid.liquid_air": "液态空气",
        "fluid.hydrochloric_acid": "盐酸",
        "fluid.nitric_acid": "硝酸",
        "fluid.phosphoric_acid": "磷酸",
        "fluid.aqua_fluoride": "氟王水",
        "fluid.bromine": "液溴",
        "fluid.bromine_gas": "溴蒸气",
        "fluid.phosphine": "膦",
        "fluid.rich_brine": "富集盐水",
        "fluid.poor_brine": "乏盐水",
        "fluid.halogen_brine": "卤水",
        "fluid.ammonia_brine": "氨盐水",
        "fluid.iodine_solution": "碘水",
        "fluid.carbon_tetrachloride": "四氯化碳",
        "fluid.trichloromethane": "三氯甲烷",
        "fluid.dichloromethane": "二氯甲烷",
        "fluid.chloromethane": "氯甲烷",
        "fluid.methane": "甲烷",
        "fluid.ethylene": "乙炔",
        "fluid.mixed_hydrocarbon": "混合烃",
        "fluid.hydrogen_fluoride": "氟化氢",
        "fluid.iodine_carbon_tetrachloride_solution": "碘-四氯化碳溶液",
        "fluid.nitrogen_oxide": "一氧化氮",
        "fluid.nitrogen_dioxide": "二氧化氮",
        "fluid.hydrogen_sulfide": "硫化氢",
        "fluid.chloroplatinic_acid_solution": "氯铂酸",
        "fluid.sodium_chloroplatinate_solution": "氯铂酸钠溶液",
        "fluid.calcium_chloride_solution": "氯化钙溶液",
        "fluid.calcium_hydroxide_solution": "氢氧化钙溶液",
        "fluid.strontium_chloride_solution": "氯化锶溶液",
        "fluid.strontium_sulfide_solution": "硫化锶溶液",
        "fluid.barium_chloride_solution": "氯化钡溶液",
        "fluid.barium_sulfide_solution": "硫化钡溶液",
        "fluid.sodium_phosphate_solution": "磷酸钠溶液",
        "fluid.sodium_hydrogen_phosphate_solution": "磷酸氢钠溶液",
        "fluid.sodium_dihydrogen_phosphate_solution": "磷酸二氢钠溶液",
        "fluid.ammonium_chloride_solution": "氯化铵溶液",
        "fluid.magnesium_sulfate_solution": "硫酸镁溶液",
        "fluid.iron_2_sulfate_solution": "硫酸亚铁溶液",
        "fluid.zinc_chloride_solution": "氯化锌溶液",
        "fluid.manganese_chloride_solution": "氯化锰溶液",
        "fluid.sodium_molybdate_solution": "钼酸钠溶液",
        "fluid.sodium_hydrogen_carbonate_solution": "碳酸氢钠溶液",
        "fluid.sodium_chloride": "熔融氯化钠",
        "fluid.potassium_chloride": "熔融氯化钾",
        "fluid.rubidium_chloride": "熔融氯化铷",
        "fluid.cesium_chloride": "熔融氯化铯",
        "fluid.platinum_chloride": "熔融氯化铂",
        "fluid.calcium_chloride": "熔融氯化钙",
        "fluid.strontium_chloride": "熔融氯化锶",
        "fluid.barium_chloride": "熔融氯化钡",
        "fluid.liquid_hydrogen": "液氢",
        "fluid.liquid_nitrogen": "液氮",
        "fluid.liquid_oxygen": "液氧",
        "fluid.liquid_fluorine": "液氟",
        "fluid.liquid_neon": "液氖",
        "fluid.liquid_chlorine": "液氯",
        "fluid.liquid_argon": "液氩",
        "fluid.liquid_krypton": "液氪",
        "fluid.liquid_xenon": "液氙",
        "fluid.liquid_radon": "液氡",
        "fluid.oxygen": "氧",
        "fluid.nitrogen": "氮",
        "fluid.neon": "氖",
        "fluid.argon": "氩",
        "fluid.krypton": "氪",
        "fluid.xenon": "氙",
        "fluid.radon": "氡",
        "fluid.hecryo_liquid": "§c凛冰-液氦溶液",
        "fluid.liquidgoldenamber": "熔融金琥珀",
        "fluid.substrate_lifeessence": "生命源质底物",
        "fluid.serum": "血浆",
        "fluid.culture_medium": "液体培养基",
        //
        "fluid.liquidlegend": "荣耀浆液",
        //
        "tile.abyss_liquid.name": "暗渊溶液",
        "journey.boss.name.sentryheart": "§4哨兵之心",
        "jer.worldgen.averageChunk": "平均每区块方块数",
        "death.attack.curse": "%s死于腐化的诅咒。",
        "craftcheck.failure.item.input": "缺少物品输入！",
        "craftcheck.failure.item.output.space": "没有足够的空间以供输出物品！",
        "craftcheck.failure.fluid.input": "缺少流体输入！",
        "craftcheck.failure.fluid.output.space": "没有足够的空间以供输出流体！",
        "craftcheck.failure.gas.input": "缺少气体输入！",
        "craftcheck.failure.gas.output.space": "没有足够的空间以供输出气体！",
        "craftcheck.failure.energy.input": "缺少能量输入！",
        "component.missing.modularmachinery.energy.output": "没有找到能量输出仓！",
        "component.missing.modularmachinery.energy.input": "没有找到能量输入仓！",
        "component.missing.modularmachinery.fluid.output": "没有找到流体输出仓！",
        "component.missing.modularmachinery.fluid.input": "没有找到流体输入仓！",
        "component.missing.modularmachinery.gas.output": "没有找到流体输出仓以供输出气体！",
        "component.missing.modularmachinery.gas.input": "没有找到流体输入仓以供输入气体！",
        "component.missing.modularmachinery.item.output": "没有找到物品输出仓！",
        "component.missing.modularmachinery.item.input": "没有找到物品输入仓！",
        "item.aether_portal_frame.name": "一键式天境传送门",
        "modifier.tconevo.crystalline.desc": "§c§r[已禁用]§r\n该特性将不会出现在工具或盔甲上。",
        "modifier.tconevo.will_strength_armor.desc": "§o至少你不会一下子就死去……\n§r满血时，你将不会被一击杀死",
        "tconevo.info.cannot_replace": "§c无法替换该部件。\n§e拥有进化属性的工具的部件无法被替换。",
        "tconevo.info.artifact_sealed": "§c无法改动未启封的“匠心之作”！\n§e要想改动该工具，请用工具锻造台将工具和§5启封之板§e合成。",
        "text.component.animus.transposition.cleared": "移位标记已清除！",
        "item.bloodmagic.alchemic_vial.base.name": "炼金之瓶",
        "tile.bloodarsenal.slate..name": "石板砖",
        "item.nae2.part.exposer.name": "ME存储暴露接口",
        "tile.nae2.exposer.name": "ME存储暴露接口",
        "message.touhou_little_maid.change_model.disabled": "§e皮肤切换功能已被禁止，请使用§6扭蛋机§e抽取女仆皮肤！",
        "entity.Dummy.name": "训练用假人",
        "item.bountifulbaubles.trinketAnkhCharm.name": "安赫护符",
        "item.heart_food.name": "§c心之容器 EX§r",
        "tooltip.itemstages.name.default": "§5§ka§r §d未知物品 §5§ka§r",
        "commands.publish.started": "§e已在端口§6%s§e上开启局域网游戏。",
        "potion.saturation": "饱腹",
        "tile.quark:monster_box.name": "§c陷阱刷怪笼",
        "tile.monster_box.name": "§c陷阱刷怪笼",
        "mob_effect.netherex:fire_burning": "极寒之焰",
        "info.nyx.blood_moon_sleeping": "§c你无法在血色之月的阴霾下安心入睡。",
        "tile.torchmaster.mega_torch.lit.tooltip": "§e正道的光，照在了大地上！",
        "entity.quazar.name": "§9史莱姆之神§r",
        "entity.champions.cinder_spark.name": "精英怪范围伤害",
        "dc.message.death": "§c[死亡次数统计] §e你已经阵亡§c§l%s§r§e次。",
        "dc.message.deathAndRank": "死亡次数: %1$s排名: %2$s",
        "dc.command.leaderboard": "§a========== §e死亡排行榜 §a==========",
        "ac.ritual.abyssalite": "渊素转化",
        "ac.ritual.abyssalite.desc": "使用阴影宝石将铁矿石变成渊素矿石！",
        "reskillable.skill.reskillable.mining": "挖掘 §7[§2+攻速§7]§r",
        "reskillable.skill.reskillable.gathering": "采集 §7[§2+幸运§7]§r",
        "reskillable.skill.reskillable.attack": "攻击 §7[§2+伤害§7]§r",
        "reskillable.skill.reskillable.defense": "防御 §7[§2+盔甲§7]§r",
        "reskillable.skill.reskillable.building": "建造 §7[§2+韧性§7]§r",
        "reskillable.skill.reskillable.farming": "农耕 §7[§2+生命§7]§r",
        "reskillable.skill.reskillable.agility": "敏捷 §7[§2+移速§7]§r",
        "reskillable.skill.reskillable.magic": "魔法 §7[§2+经验§7]§r",
        "message.died": "§e%s §7逝世于 %s §9(破坏坟墓以取回物品)",
        "death.attack.outOfWorld": "实体%1$s被从埃拉西亚公共界面移除",
        "material.extrabotany:ingotorichalcos.name": "§c[已禁用]",
        "material.extrabotany:ingotshadowium.name": "§c[已禁用]",
        "memorycleaner.gc.start": "§a[内存清理] §f正在清理内存，可能会导致卡顿！\n§7(如果这造成了较长时间的卡顿，请使用我们GitHub Wiki页面推荐的JVM参数。)",
        "tile.denseneutroncollectors:compressed_neutron_collector.name": "聚合中子素收集器",
        "tile.denseneutroncollectors:double_compressed_neutron_collector.name": "质子中子素收集器",
        "tile.denseneutroncollectors:triple_compressed_neutron_collector.name": "平衡中子素收集器",
        "container.compressed_neutron_collector": "聚合中子素收集器",
        "container.double_compressed_neutron_collector": "质子中子素收集器",
        "container.triple_compressed_neutron_collector": "平衡中子素收集器",
        "entity.WitherBossCommandBlockHelpful.name": "凋灵风暴（初始阶段）",
        "entity.WitherStormBossHelpful.name": "凋灵风暴（完全阶段）",
        "entity.WitherStormBossTentacleHelpful.name": "凋灵风暴触手",
        "entity.WitherStormBossHeadHelpful.name": "凋灵风暴头",
        "entity.WitherStormBossTentacleDevourerHelpful.name": "凋灵风暴触手",
        "greedycraft.tconstruct.material.titanium.name": "钛",
        "greedycraft.tconstruct.material.manganese.name": "锰",
        "greedycraft.tooltip.command_block": "§e该方块属于技术性方块，无法在生存模式被放置\n§e如果因意外导致方块被放在地上，可以使用命令拆除扳手右键拆除",
        "greedycraft.tooltip.odct": "§e此物品可能具有多个ID，合成可能会发生冲突\n§e可以直接放入工作台或扔在地上转化为同名物品",
        "greedycraft.tooltip.contenttweaker.modularblock": "§c如果不会搭建模块化机器，可以在整合包手册中查看",
        "greedycraft.tooltip.conductive": "导电铁粒的熔点为575K，可以使用加热器搭配微型冶炼炉熔化",
        "greedycraft.tooltip.lumps": "法球可以通过探索梦魇世界地牢和击杀梦魇BOSS获得",
        "greedycraft.tooltip.utilityworld.warnings": "§4一旦使用了传送门，\n除非你放置了指路石等传送装置，\n否则请不要破坏此传送门及返回传送门，\n否则会引起世界丢失！",
        "tile.orderland_portal.name": "秩序之地传送门",
        "tile.everheaven_portal.name": "深空之域传送门",
        "greedycraft.tooltip.modularcontroller.not_need_blueprints": "§4此机械无需制作蓝图即可工作"
    }
};

val blueprintDesc as string[] = [
    "item.tconstruct.longsword.desc",
    "item.tconstruct.rapier.desc",
    "item.tconstruct.cleaver.desc",
    "item.tconstruct.shuriken.desc",
    "item.tconevo:tool_sceptre.desc",
    "item.katana.desc",
    "item.laser_gun.desc"
];

for lang, entries in localizationMap {
    for k, v in entries {
        game.setLocalization(lang, k, v);
    }
}

for key in blueprintDesc {
    game.setLocalization(key, game.localize(key) + "\n" + game.localize("greedycraft.tooltip.constant.blueprint_required"));
}
