/*
 * This script is created for the GreedyCraft modpack by TCreopargh.
 * You may NOT use this script in any other publicly distributed modpack without my permission.
 */

#priority 1

import crafttweaker.item.IItemStack;
import crafttweaker.data.IData;
import crafttweaker.item.IIngredient;

import crafttweaker.game.IGame;
import crafttweaker.oredict.IOreDictEntry;

import scripts.util.oredict as OredictUtil;

<ore:ingotNetherite>.remove(<divinerpg:netherite_ingot>);
<ore:blockNetherite>.remove(<divinerpg:netherite_block>);
<ore:oreNetherite>.remove(<divinerpg:netherite_ore>);
<ore:blockHellstone>.remove(<journey:hellstoneblock>);
<ore:ingotHellstone>.remove(<journey:hellstoneingot>);
<ore:oreHellstone>.remove(<journey:hellstoneore>);
<ore:gemSapphire>.remove(<journey:sapphire>);
<ore:oreSapphire>.remove(<journey:sapphireore>);
<ore:blockSapphire>.remove(<journey:sapphireblock>);
<ore:ingotcthulhurite>.remove(<gct_mobs:cthulhurite_ingot>);
<ore:blockEden>.remove(<divinerpg:eden_block>);
<ore:blockWildwood>.remove(<divinerpg:wildwood_block>);
<ore:blockApalachia>.remove(<divinerpg:apalachia_block>);
<ore:blockSkythern>.remove(<divinerpg:skythern_block>);
<ore:blockMortum>.remove(<divinerpg:mortum_block>);
<ore:oreEden>.remove(<divinerpg:eden_ore>);
<ore:oreWildwood>.remove(<divinerpg:wildwood_ore>);
<ore:oreApalachia>.remove(<divinerpg:apalachia_ore>);
<ore:oreSkythern>.remove(<divinerpg:skythern_ore>);
<ore:oreMortum>.remove(<divinerpg:mortum_ore>);
<ore:nuggetTitanium>.remove(<tiths:nugget_titanium>);
<ore:cinnabar>.remove(<tiths:cinnabar>);
<ore:mercury>.remove(<tiths:cinnabar>);
<ore:ingotBlackIron>.remove(<extendedcrafting:material>);
<ore:blockBlackIron>.remove(<extendedcrafting:storage>);
<ore:nuggetBlackIron>.remove(<extendedcrafting:material:1>);
<ore:oreGallium>.remove(<moretcon:oregallium>);
<ore:ingotShadowium>.remove(<extrabotany:material:5>);
<ore:tungstenIngot>.remove(<endreborn:item_ingot_wolframium>);
<ore:Geardensite>.remove(<gct_ores:densite_gear>);
<ore:gemMoonstone>.remove(<tiths:moon_stone>);
<ore:blockMoonstone>.remove(<tiths:block_moon_stone>);
<ore:ingotValkyrieMetal>.remove(<moretcon:ingotvalkyriemetal>);
<ore:blockValkyrieMetal>.remove(<moretcon:blockvalkyriemetal>);
<ore:dustValkyrieMetal>.remove(<moretcon:dustvalkyriemetal>);
<ore:nuggetValkyrieMetal>.remove(<moretcon:nuggetvalkyriemetal>);
<ore:blockQuartzMana>.remove(<botania:quartztypemana>);
<ore:blockQuartzDark>.remove(<botania:quartztypedark>);
<ore:blockQuartzDark>.remove(<thaumictinkerer:black_quartz_block>);
<ore:blockQuartzDark>.remove(<botania:quartztypedark:1>);
<ore:blockQuartzDark>.remove(<botania:quartztypedark:2>);
<ore:book>.remove(<tiths:ancient_book_irisia>);

<ore:ingotCthulhurite>.add(<gct_mobs:cthulhurite_ingot>);
<ore:starlight>.add(<journey:sapphire>);
/*
var vetheaDisabled as IItemStack[] = [
    <waystones:warp_stone>,
    <waystones:waystone>,
    <waystones:warp_scroll>,
    <bountifulbaubles:wormholemirror>,
    <bountifulbaubles:magicmirror>,
    <bountifulbaubles:potionrecall>,
    <bountifulbaubles:potionwormhole>,
    <draconicevolution:dislocator>,
    <draconicevolution:dislocator_advanced>,
    <botania:flugeleye>,
    <compactmachines3:machine>,
    <compactmachines3:machine:1>,
    <compactmachines3:machine:2>,
    <compactmachines3:machine:3>,
    <compactmachines3:machine:4>,
    <compactmachines3:machine:5>,
    <minecraft:bucket>,
    <minecraft:water_bucket>,
    <minecraft:lava_bucket>,
    <forge:bucketfilled>,
    <thermalexpansion:florb>,
    <thermalexpansion:reservoir>,
    <minecraft:gold_ingot>,
    <appliedenergistics2:material>,
    <minecraft:redstone>,
    <thermalfoundation:material:163>,
    <thermalfoundation:material:128>,
    <tcomplement:cast_clay>,
    <tconstruct:clay_cast>,
    <minecraft:ender_chest>,
    <minecraft:ender_eye>,
    <minecraft:blaze_powder>,
    <minecraft:ender_pearl>,
    <minecraft:ender_chest>,
    <extrautils2:user>,
    <minecraft:ender_pearl>,
    <minecraft:ender_eye>,
    <minecraft:blaze_powder>,
    <minecraft:blaze_rod>,
    <minecraft:obsidian>
];
if (!isNull(itemUtils.getItem("utilityworlds:portal_void"))) {
    vetheaDisabled += itemUtils.getItem("utilityworlds:portal_void");
    vetheaDisabled += itemUtils.getItem("utilityworlds:portal_garden");
}
for item in vetheaDisabled {
    <ore:vetheaDisabled>.add(item);
} */

var oredictMap as IIngredient[][IOreDictEntry] = {
    <ore:logWood> : [
        <betterendforge:mossy_glowshroom_log>,
        <betterendforge:lacugrove_stripped_log>,
        <betterendforge:lacugrove_log>,
        <betterendforge:end_lotus_stripped_log>,
        <betterendforge:end_lotus_log>,
        <betterendforge:pythadendron_stripped_log>,
        <betterendforge:pythadendron_log>,
        <betterendforge:dragon_tree_stripped_log>,
        <betterendforge:dragon_tree_log>,
        <betterendforge:tenanea_stripped_log>,
        <betterendforge:tenanea_log>,
        <betterendforge:helix_tree_stripped_log>,
        <betterendforge:helix_tree_log>,
        <betterendforge:umbrella_tree_stripped_log>,
        <betterendforge:umbrella_tree_log>,
        <betterendforge:jellyshroom_stripped_log>,
        <betterendforge:jellyshroom_log>,
        <betterendforge:lucernia_log>,
        <betterendforge:lucernia_stripped_log>,
        <betterendforge:mossy_glowshroom_stripped_log>
    ],
    <ore:plankWood> : [
        <betterendforge:mossy_glowshroom_planks>,
        <betterendforge:lacugrove_planks>,
        <betterendforge:end_lotus_planks>,
        <betterendforge:pythadendron_planks>,
        <betterendforge:dragon_tree_planks>,
        <betterendforge:tenanea_planks>,
        <betterendforge:helix_tree_planks>,
        <betterendforge:umbrella_tree_planks>,
        <betterendforge:jellyshroom_planks>,
        <betterendforge:lucernia_planks>
    ],
    <ore:treeSapling> : [
        <betterendforge:hydralux_sapling>,
        <betterendforge:small_jellyshroom>,
        <betterendforge:mossy_glowshroom_sapling>,
        <betterendforge:lacugrove_sapling>,
        <betterendforge:pythadendron_sapling>,
        <betterendforge:dragon_tree_sapling>,
        <betterendforge:tenanea_sapling>,
        <betterendforge:helix_tree_sapling>,
        <betterendforge:umbrella_tree_sapling>,
        <betterendforge:lucernia_sapling>
    ],
    <ore:treeLeaves> : [
        <betterendforge:lacugrove_leaves>,
        <betterendforge:pythadendron_leaves>,
        <betterendforge:dragon_tree_leaves>,
        <betterendforge:tenanea_leaves>,
        <betterendforge:helix_tree_leaves>,
        <betterendforge:lucernia_leaves>
    ],
    <ore:slabWood> : [
        <betterendforge:mossy_glowshroom_slab>,
        <betterendforge:lacugrove_slab>,
        <betterendforge:end_lotus_slab>,
        <betterendforge:pythadendron_slab>,
        <betterendforge:dragon_tree_slab>,
        <betterendforge:tenanea_slab>,
        <betterendforge:helix_tree_slab>,
        <betterendforge:umbrella_tree_slab>,
        <betterendforge:jellyshroom_slab>,
        <betterendforge:lucernia_slab>,
    ],
    <ore:stairWood> : [
        <betterendforge:mossy_glowshroom_stairs>,
        <betterendforge:lacugrove_stairs>,
        <betterendforge:end_lotus_stairs>,
        <betterendforge:pythadendron_stairs>,
        <betterendforge:dragon_tree_stairs>,
        <betterendforge:tenanea_stairs>,
        <betterendforge:helix_tree_stairs>,
        <betterendforge:umbrella_tree_stairs>,
        <betterendforge:jellyshroom_stairs>,
        <betterendforge:lucernia_stairs>
    ],
    <ore:plantEnd> : [
        <betterendforge:umbrella_moss>,
        <betterendforge:umbrella_moss_tall>,
        <betterendforge:creeping_moss>,
        <betterendforge:chorus_grass>,
        <betterendforge:cave_grass>,
        <betterendforge:crystal_grass>,
        <betterendforge:amber_grass>,
        <betterendforge:shadow_plant>,
        <betterendforge:bushy_grass>,
        <betterendforge:jungle_grass>,
        <betterendforge:blooming_cooksonia>,
        <betterendforge:salteago>,
        <betterendforge:vaiolush_fern>,
        <betterendforge:fracturn>,
        <betterendforge:globulagus>,
        <betterendforge:inflexia>,
        <betterendforge:clawfern>,
        <betterendforge:aeridium>,
        <betterendforge:orango>,
        <betterendforge:lutebus>,
        <betterendforge:lamellarium>,
        <betterendforge:bolux_mushroom>,
        <betterendforge:blue_vine_fur>,
        <betterendforge:bubble_coral>,
        <betterendforge:murkweed>,
        <betterendforge:needlegrass>,
        <betterendforge:charnia_red>,
        <betterendforge:charnia_purple>,
        <betterendforge:charnia_orange>,
        <betterendforge:charnia_light_blue>,
        <betterendforge:charnia_cyan>,
        <betterendforge:charnia_green>,
        <betterendforge:glowing_pillar_leaves>,
        <betterendforge:twisted_umbrella_moss>,
        <betterendforge:twisted_umbrella_moss_tall>,
        <betterendforge:neon_cactus>,
        <betterendforge:tail_moss>,
        <betterendforge:cyan_moss>,
        <betterendforge:twisted_moss>,
        <betterendforge:bulb_moss>,
        <betterendforge:purple_polypore>,
        <betterendforge:aurant_polypore>,
        <betterendforge:jungle_fern>,
        <betterendforge:ruscus>,
        <betterendforge:pond_anemone>,
        <betterendforge:dense_vine>,
        <betterendforge:twisted_vine>,
        <betterendforge:bulb_vine>,
        <betterendforge:jungle_vine>,
        <betterendforge:rubinea>,
        <betterendforge:mossy_glowshroom_sapling>,
        <betterendforge:mossy_glowshroom_fur>,
        <betterendforge:lacugrove_sapling>,
        <betterendforge:tenanea_flowers>,
        <betterendforge:tenanea_outer_leaves>,
        <betterendforge:amaranita_fur>,
        <betterendforge:small_amaranita_mushroom>,
        <stygian:endglow>,
        <stygian:endtallgrass>,
        <stygian:endcactus>
    ],
    <ore:gearDensite> : [<gct_ores:densite_gear>],
    <ore:oreIron> : [<sakura:iron_sand>],
    <ore:gemAmber> : [<betterendforge:amber_gem>],
    //<ore:vetheaDisabled> : [<ore:ingotBrass>],
    <ore:ingotBlackiron> : [<extendedcrafting:material>],
    <ore:blockBlackiron> : [<extendedcrafting:storage>],
    <ore:nuggetBlackiron> : [<extendedcrafting:material:1>],
    <ore:stoneDarkDense> : [<gct_aby:densedarkstone>],
    <ore:oreDreadium> : [<gct_aby:dreadiumore>],
    <ore:oreEthaxium> : [<gct_aby:ethauxiumore>],
    <ore:oreSanite> : [<gct_aby:saniteore>],
    <ore:nuclearShadow> : [<gct_aby:shadownuclear>],
    <ore:ingotBloodcrust> : [<journey:hellstoneingot>],
    <ore:blockBloodcrust> : [<journey:hellstoneblock>],
    <ore:oreBloodcrust> : [<journey:hellstoneore>],
    <ore:blockFierymetal> : [<twilightforest:block_storage:1>],
    <ore:ingotFierymetal> : [<twilightforest:fiery_ingot>],
    <ore:gemCarminite> : [<twilightforest:carminite>],
    <ore:blockCarminite> : [<twilightforest:block_storage:4>],
    <ore:slimeball> : [<defiledlands:foul_slime>, <thermalfoundation:material:833>],
    <ore:workbench> : [<ore:craftingTableWood>, <randomthings:customworkbench:*>],
    <ore:plantFibre> : [<hooked:microcrafting>],
    <ore:string> : [<hooked:microcrafting:1>],
    <ore:dirt> : [<biomesoplenty:dirt:*>],
    <ore:ingotFusionMatrix> : [<tconevo:material>],
    <ore:ingotCoalescenceMatrix> : [<tconevo:material>],
    <ore:blockCoalescenceMatrix> : [<ore:blockFusionMatrix>],
    <ore:blockBasalt> : [<netherex:basalt>],
    <ore:blockBasalt> : [<ore:stoneBasalt>],
    <ore:stoneBasalt> : [<taiga:basalt_block>],
    <ore:foodChocolate> : [<actuallyadditions:item_food:9>, <ore:foodChocolateBar>],
    <ore:foodChocolateBar> : [<ore:foodChocolate>],
    <ore:foodCandyCane> : [<aether_legacy:candy_cane>],
    <ore:CandyCane> : [<ore:foodCandyCane>],
    <ore:ingotGaia> : [<ore:gaiaIngot>],
    <ore:blockTerrasteel> : [<botania:storage:1>],
    <ore:blockElvenElementium> : [<botania:storage:2>],
    <ore:blockOrichalcos> : [<extrabotany:blockorichalcos>],
    <ore:blockTungsten> : [<endreborn:block_wolframium>],
    <ore:blockWolframium> : [<endreborn:block_wolframium>],
    <ore:ingotWolframium> : [<endreborn:item_ingot_wolframium>],
    <ore:oreWolframium> : [<endreborn:block_wolframium_ore>],
    <ore:blockEndorium> : [<endreborn:block_endorium>],
    <ore:bedrock> : [<minecraft:bedrock>],
    <ore:toolTiC> : [
        <plustic:laser_gun>,
        <plustic:katana>,
        <tcomplement:chisel>,
        <tconstruct:pickaxe>,
        <tconstruct:shovel>,
        <tconstruct:hatchet>,
        <tconstruct:mattock>,
        <tconstruct:kama>,
        <tconstruct:hammer>,
        <tconstruct:excavator>,
        <tconstruct:lumberaxe>,
        <tconstruct:scythe>,
        <tconstruct:broadsword>,
        <tconstruct:longsword>,
        <tconstruct:rapier>,
        <tconstruct:frypan>,
        <tconstruct:battlesign>,
        <tconstruct:cleaver>,
        <tconstruct:shortbow>,
        <tconstruct:longbow>,
        <tconstruct:crossbow>,
        <tconstruct:shuriken>,
        <tconstruct:arrow>,
        <tconstruct:bolt>,
        <tconevo:tool_sceptre>,
        <tcongreedyaddon:battleaxe>,
        <tcongreedyaddon:dagger>,
        <tcongreedyaddon:greatblade>,
        <tcongreedyaddon:allinonetool>,
        <moretcon:blbow>,
        <moretcon:blsword>,
        <moretcon:blaxe>,
        <moretcon:blpick>,
        <moretcon:blshovel>,
        <moretcon:ring>,
        <moretcon:gauntlet>
    ],
    <ore:armorTiC> : [
        <conarm:helmet>,
        <conarm:chestplate>,
        <conarm:leggings>,
        <conarm:boots>
    ],
    <ore:dungeonLootTier0> : [
        <touhou_little_maid:power_point>
    ],
    <ore:dungeonLootTier1> : [
        <additions:medkit_small>,
        <additions:bag_of_dyes>,
        <quark:rune:*>,
        <cyclicmagic:apple_emerald>,
        <additions:tower_chest_key>,
        <scalinghealth:crystalshard>,
        <additions:huaji>,
        <extrabotany:material>,
        <cyclicmagic:corrupted_chorus>,
        <additions:tcsponsors-sponsor_chest_fragment>,
        <forestry:broken_bronze_pickaxe>,
        <forestry:kit_pickaxe>,
        <cyclicmagic:sprout_seed>,
        <cyclicmagic:ender_pearl_reuse>,
        <cyclicmagic:ender_eye_orb>,
        <cyclicmagic:charm_wing>,
        <cyclicmagic:charm_antidote>,
        <cyclicmagic:charm_fire>,
        <cyclicmagic:charm_void>,
        <actuallyadditions:item_misc:20>,
        <ore:itemPoop>, 
        <ore:gemShadow>, 
        <ore:record>,
        <journey:tomatoseeds>,
        <journey:loot_pouch>,
        <journey:magic_dust>
    ],
    <ore:dungeonLootTier2> : [
        <randomthings:magichood>,
        <openblocks:technicolor_glasses>,
        <additions:delivery_order>,
        <enderio:item_dark_steel_sword>,
        <cyclicmagic:tool_prospector>,
        <cyclicmagic:glove_climb>,
        <enderio:item_conduit_probe>,
        <cyclicmagic:sack_ender>,
        <randomthings:biomecrystal>,
        <enderio:item_dark_steel_boots>,
        <additions:medkit_big>,
        <bountifulbaubles:phantomprism>,
        <additions:sunny_doll>,
        <extrabotany:bottledstar>,
        <bountifulbaubles:trinketmagiclenses>,
        <randomthings:summoningpendulum>,
        <enderio:item_basic_capacitor:4>,
        <enderio:item_basic_capacitor:3>,
        <bountifulbaubles:shieldcobalt>,
        <enderio:item_travel_staff>,
        <randomthings:lavacharm>,
        <cyclicmagic:evoker_fang>,
        <cyclicmagic:ender_lightning>,
        <cyclicmagic:tool_auto_torch>,
        <bountifulbaubles:amuletcross>,
        <bountifulbaubles:flaregun>,
        <randomthings:slimecube>,
        <cyclicmagic:tool_warp_home>,
        <cyclicmagic:tool_push>,
        <bountifulbaubles:trinketluckyhorseshoe>,
        <extrabotany:bottledpixie>,
        <cyclicmagic:crafting_food>,
        <cyclicmagic:inventory_food>,
        <cyclicmagic:ender_tnt_6>,
        <forestry:miner_bag>,
        <botania:overgrowthseed>,
        <bountifulbaubles:brokenblackdragonscale>,
        <bountifulbaubles:trinketbezoar>,
        <bountifulbaubles:magicmirror>,
        <bountifulbaubles:amuletsinempty>,
        <bountifulbaubles:trinketobsidianskull>,
        <cyclicmagic:ender_dungeon>,
        <extrabotany:bottledflame>,
        <astralsorcery:itemconstellationpaper>,
        <additions:loli_lolipop>,
        <openblocks:trophy:*>,
        <charm:charged_emerald>,
        <charm:totem_of_shielding>,
        <ore:dungeonShield>,
        <ore:inventoryPet>,
        <journey:loot_pouch_gold>,
        <journey:xp_catalyst>,
        <advanced-fishing:blazing_fishing_pole:*>
    ],
    <ore:dungeonLootTier3> : [
        <additions:goodie_bag>,
        <additions:true_eye_of_ender>,
        <additions:medkit_super>,
        <additions:experience_transporter>,
        <additions:skill_reset_scroll>,
        <additions:tcsponsors-sponsors_chest>,
        <cyclicmagic:heart_food>,
        <additions:one_punch>,
        <additions:experiment_note>,
        <mowziesmobs:wrought_helmet>,
        <mowziesmobs:wrought_axe>,
        <journey:loot_pouch_diamond>
    ],
    <ore:metalGene> : [
        <additions:cytosinite_ingot>,
        <additions:thyminite_ingot>,
        <additions:guaninite_ingot>,
        <additions:adeninite_ingot>
    ],
    <ore:metalWyvern> : [
        <additions:cryonium_ingot>,
        <additions:aetherium_ingot>,
        <additions:lavarite_ingot>,
        <additions:snowingium_ingot>
    ],
    <ore:metalAwakened> :  [
        <additions:infernium_ingot>,
        <additions:canopium_ingot>,
        <additions:plasmarite_ingot>,
        <additions:freezite_ingot>
    ],
    <ore:metalChaotic> : [
        <additions:titanium_ingot>,
        <additions:mistium_ingot>,
        <additions:bnightium_ingot>,
        <additions:oceanium_ingot>
    ],
    <ore:gemCincinnasite> : [<betternether:cincinnasite>],
    <ore:gemTofu> : [<tofucraft:material:18>],
    <ore:gemTofuStrong> : [<tofucraft:material:25>],
    <ore:gemDiamondPink> : [<sakura:sakura_diamond>],
    <ore:gemDiamondSakura> : [<sakura:sakura_diamond>],
    <ore:dustCrystalHeart> : [<scalinghealth:heartdust>],
    <ore:shardCrystalHeart> : [<scalinghealth:crystalshard>],
    <ore:heartContainer> : [
        <scalinghealth:heartcontainer>,
        <cyclicmagic:heart_food>
    ],
    <ore:compressed1xDirt> : [<ore:compressedDirt1>],
    <ore:compressedDirt1> : [<ore:compressed1xDirt>],
    <ore:compressed2xDirt> : [<ore:compressedDirt2>],
    <ore:compressedDirt2> : [<ore:compressed2xDirt>],
    <ore:beanCocoa> : [<minecraft:dye:3>],
    <ore:quartzDark> : [<ore:gemQuartzBlack>],
    <ore:gemQuartzBlack> : [<ore:quartzDark>],
    <ore:blockShadowium> : [<extrabotany:blockshadowium>],
    <ore:ingotBrickScorched> : [<tcomplement:materials:1>],
    <ore:blockScorched> : [<tcomplement:scorched_block:*>],
    <ore:slabScorched> : [<tcomplement:scorched_slab:*>],
    <ore:stairScorched> : [
        <tcomplement:scorched_stairs_stone>,
        <tcomplement:scorched_stairs_cobble>,
        <tcomplement:scorched_stairs_paver>,
        <tcomplement:scorched_stairs_brick>,
        <tcomplement:scorched_stairs_brick_cracked>,
        <tcomplement:scorched_stairs_brick_fancy>,
        <tcomplement:scorched_stairs_brick_square>,
        <tcomplement:scorched_stairs_brick_triangle>,
        <tcomplement:scorched_stairs_brick_small>,
        <tcomplement:scorched_stairs_road>,
        <tcomplement:scorched_stairs_tile>,
        <tcomplement:scorched_stairs_creeper>
    ],
    <ore:pebble> : [<minecraft:flint>],
    <ore:ingotModularium> : [<modularmachinery:itemmodularium>],
    <ore:cobblestone> : [<ore:holystone>],
    <ore:ice> : [<minecraft:packed_ice>],
    <ore:blockGlass> : [<betternether:quartz_stained_glass:*>, 
        <betternether:quartz_glass:*>, 
        <botany:stained:*>, 
        <extratrees:stainedglass:*>
    ],
    <ore:essenceChromium> : [<mysticalcreations:chromium_essence>],
    <ore:essenceTitanium> : [<mysticalcreations:titanium_essence>],
    <ore:essenceWitch> : [<mysticalcreations:witch_essence>],
    <ore:essenceCake> : [<mysticalcreations:cake_essence>],
    <ore:essenceStainlessSteel> : [<mysticalcreations:stainless_steel_essence>],
    <ore:dustWood> : [<ore:pulpWood>],
    <ore:pulpWood> : [<ore:dustWood>],
    <ore:itemRune> : [<quark:rune:*>],
    <ore:gemTerrestrial> : [<biomesoplenty:terrestrial_artifact>],
    <ore:blockRottenFlesh> : [<thaumcraft:flesh_block>, <charm:rotten_flesh_block>],
    <ore:rottenFlesh> : [<minecraft:rotten_flesh>],
    <ore:spiderEye> : [<minecraft:spider_eye>],
    <ore:mycelium> : [
        <quark:glowcelium>,
        <netherex:hyphae>,
        <biomesoplenty:grass:8>,
        <betternether:nether_mycelium>
    ],
    <ore:netherrack> : [<betternether:netherrack_moss>],
    <ore:shardCreative> : [<additions:creative_shard>],
    <ore:soulCreative> : [<additions:creative_soul>],
    <ore:blockDiamondPink> : [<sakura:sakura_diamond_block>],
    <ore:blockDiamondSakura> : [<sakura:sakura_diamond_block>],
    <ore:blockQuartzBlack> : [<ore:blockQuartzDark>],
    <ore:blockQuartzDark> : [<ore:blockQuartzBlack>],
    <ore:rodBlizz> : [<netherex:frost_rod>],
    <ore:dustBlizz> : [<netherex:frost_powder>],
    <ore:netherrack> : [<betternether:nether_mycelium>],
    <ore:ingotSpectre> : [<randomthings:ingredient:3>],
    <ore:stringSpectre> : [<randomthings:ingredient:12>],
    <ore:prismarine> : [<ore:blockPrismarine>],
    <ore:blockManaDiamond> : [<botania:storage:3>],
    <ore:plantFiber> : [<ore:plantFibre>],
    <ore:listAllFiber> : [<ore:plantFiber>],
    <ore:oreDiamond>: [<extrabees:misc:1>],
    <ore:singularityIron> : [<avaritia:singularity:0>],
    <ore:singularityGold> : [<avaritia:singularity:1>],
    <ore:singularityLapis> : [<avaritia:singularity:2>],
    <ore:singularityRedstone> : [<avaritia:singularity:3>],
    <ore:singularityQuartz> : [<avaritia:singularity:4>],
    <ore:singularityCopper> : [<avaritia:singularity:5>],
    <ore:singularityTin> : [<avaritia:singularity:6>],
    <ore:singularityLead> : [<avaritia:singularity:7>],
    <ore:singularitySilver> : [<avaritia:singularity:8>],
    <ore:singularityNickel> : [<avaritia:singularity:9>],
    <ore:singularityDiamond> : [<avaritia:singularity:10>],
    <ore:singularityEmerald> : [<avaritia:singularity:11>],
    <ore:singularityElectrumFlux> : [<avaritia:singularity:12>],
    <ore:singularityPlatinum> : [<avaritia:singularity:13>],
    <ore:singularityIridium> : [<avaritia:singularity:14>],
    <ore:netherStarWithered> : [<ageofminecraft:withered_nether_star>],
    <ore:ingotWitherium> : [<tiths:ingot_witherium>],
    <ore:ingotWitheriumInert> : [<tiths:ingot_inert_witherium>],
    <ore:blockWitherium> : [<tiths:block_witherium>],
    <ore:blockWitheriumInert> : [<tiths:block_inert_witherium>],
    <ore:coreDraconium> : [<draconicevolution:draconic_core>],
    <ore:coreWyvern> : [<draconicevolution:wyvern_core>],
    <ore:coreAwakened> : [<draconicevolution:awakened_core>],
    <ore:coreChaotic> : [<draconicevolution:chaotic_core>],
    <ore:coreWitherium> : [<gct_ores:witheric_core>],
    <ore:coreFallen> : [<gct_ores:fallen_core>],
    <ore:coreRelifed> : [<gct_ores:relifed_core>],
    <ore:coreStormy> : [<gct_ores:stormy_core>],
    <ore:coreBasic> : [
        <draconicevolution:draconic_core>,
        <gct_ores:witheric_core>
    ],
    <ore:coreExcellent> : [
        <draconicevolution:wyvern_core>,
        <gct_ores:fallen_core>
    ],
    <ore:coreSuperior> : [
        <draconicevolution:awakened_core>,
        <gct_ores:relifed_core>
    ],
    <ore:coreEpic> : [
        <draconicevolution:chaotic_core>,
        <gct_ores:stormy_core>
    ],
    <ore:metalEvery> : [
        <gct_ores:fire_alloy_ingot>,
        <gct_ores:sky_alloy_ingot>,
        <gct_ores:ice_alloy_ingot>,
        <additions:terra_alloy_ingot>
    ],
    <ore:gemChaosShard> : [<draconicevolution:chaos_shard>],
    <ore:blockCommand> : [
        <minecraft:command_block>,
        <minecraft:chain_command_block>,
        <minecraft:repeating_command_block>
    ],
    <ore:blockStructure> : [
        <minecraft:structure_block:*>
    ],
    <ore:latticeDiamond> : [<avaritia:resource>],
    <ore:ingotLavaSolid> : [<divinerpg:netherite_ingot>],
    <ore:blockLavaSolid> : [<divinerpg:netherite_block>],
    <ore:oreLavaSolid> : [<divinerpg:netherite_ore>],
    <ore:nuggetLavaSolid> : [<divinerpg:netherite_nugget>],
    <ore:gemIceStone> : [<divinerpg:ice_stone>],
    <ore:nuggetIceStone> : [<divinerpg:ice_shards>],
    <ore:shardsIceStone> : [<ore:nuggetIceStone>],
    <ore:ingotShadowBar> : [<divinerpg:shadow_bar>],
    <ore:ingotHellstone> : [<divinerpg:hellstone_ingot>],
    <ore:nuggetTerran> : [<divinerpg:terran_shards>],
    <ore:shardsTerran> : [<ore:nuggetTerran>],
    <ore:nuggetJungle> : [<divinerpg:jungle_shards>],
    <ore:shardsJungle> : [<ore:nuggetJungle>],
    <ore:nuggetDivine> : [<divinerpg:divine_shards>],
    <ore:shardsDivine> : [<ore:nuggetDivine>],
    <ore:nuggetCorrupted> : [<divinerpg:corrupted_shards>],
    <ore:shardsCorrupted> : [<ore:nuggetCorrupted>],
    <ore:nuggetMolten> : [<divinerpg:molten_shards>],
    <ore:shardsMolten> : [<ore:nuggetMolten>],
    <ore:nuggetEnderDivine> : [<divinerpg:ender_shards>],
    <ore:shardsEnderDivine> : [<ore:nuggetEnderDivine>],
    <ore:shardsCyclops> : [<divinerpg:cyclops_eye_shards>],
    <ore:gemTerran> : [<divinerpg:terran_stone>],
    <ore:gemJungle> : [<divinerpg:jungle_stone>],
    <ore:gemDivine> : [<divinerpg:divine_stone>],
    <ore:gemCorrupted> : [<divinerpg:corrupted_stone>],
    <ore:gemMolten> : [<divinerpg:molten_stone>],
    <ore:gemBloodgem> : [<divinerpg:bloodgem>],
    <ore:gemEnderDivine> : [<divinerpg:ender_stone>],
    <ore:oreAquatic> : [<divinerpg:pure_aquatic_pellets>],
    <ore:palletsAquatic> : [<divinerpg:aquatic_pellets>],
    <ore:eyeCyclops> : [<divinerpg:cyclops_eye>],
    <ore:eyeEnderLegendary> : [<divinerpg:legendary_ender_eye>],
    <ore:gemBlueFire> : [<divinerpg:bluefire_stone>],
    <ore:dustBlazePurple> : [<divinerpg:purple_blaze>],
    <ore:dustBlazeFury> : [<divinerpg:fury_fire>],
    <ore:rodBlazeAquatic> : [<divinerpg:aquatic_blaze_rod>],
    <ore:eyeWatching> : [<divinerpg:watching_eye>],
    <ore:scaleKraken> : [<divinerpg:kraken_scale>],
    <ore:ballAqua> : [<divinerpg:aqua_ball>],
    <ore:gemHealing> : [<divinerpg:healing_stone>],
    <ore:crystalCinnabar> : [<tiths:mercury_sulfide>],
    <ore:itemCinnabar> : [<ore:gemCinnabar>],
    <ore:ingotMercurySulfuride> : [<ore:gemCinnabar>],
    <ore:ingotStellarium> : [<tiths:ingot_stellarium>],
    <ore:ingotRoyalAlloy> : [<tiths:ingot_royal_alloy>],
    <ore:ingotSilverImmersed> : [<tiths:ingot_immersed_silver>],
    <ore:ingotWitheriumInert> : [<tiths:ingot_inert_witherium>],
    <ore:ingotPolarium> : [<tiths:ingot_polarium>],
    <ore:ingotHalleium> : [<tiths:ingot_halleium>],
    <ore:ingotAltairium> : [<tiths:ingot_altairium>],
    <ore:ingotHothium> : [<tiths:ingot_hothium>],
    <ore:ingotTonium> : [<tiths:ingot_tonium>],
    <ore:ingotCocoarium> : [<tiths:ingot_cocoa>],
    <ore:ingotIrisia> : [<tiths:ingot_irisia>],
    <ore:ingotOraclium> : [<tiths:ingot_oraclium>],
    <ore:ingotSteamium> : [<tiths:ingot_steamium>],
    <ore:ingotGrainium> : [<tiths:ingot_grain>],
    <ore:ingotChloroplast> : [<tiths:ingot_chloroplast>],
    <ore:ingotDecurrium> : [<tiths:ingot_decurrium>],
    <ore:ingotImitatium> : [<tiths:ingot_imitatium>],
    <ore:ingotMagiga> : [<tiths:ingot_magiga>],
    <ore:ingotSolita> : [<tiths:ingot_solita>],
    <ore:ingotTanatonium> : [<tiths:ingot_tanatonium>],
    <ore:itemMagentaMatter> : [<projectex:matter:0>],
    <ore:itemPinkMatter> : [<projectex:matter:1>],
    <ore:itemPurpleMatter> : [<projectex:matter:2>],
    <ore:itemVioletMatter> : [<projectex:matter:3>],
    <ore:itemBlueMatter> : [<projectex:matter:4>],
    <ore:itemCyanMatter> : [<projectex:matter:5>],
    <ore:itemGreenMatter> : [<projectex:matter:6>],
    <ore:itemLimeMatter> : [<projectex:matter:7>],
    <ore:itemYellowMatter> : [<projectex:matter:8>],
    <ore:itemOrangeMatter> : [<projectex:matter:9>],
    <ore:itemWhiteMatter> : [<projectex:matter:10>],
    <ore:itemFadingMatter> : [<projectex:matter:11>],
    <ore:ingotElementium> : [<ore:ingotElvenElementium>],
    <ore:nuggetElementium> : [<ore:nuggetElvenElementium>],
    <ore:blockElementium> : [<botania:storage:2>],
    <ore:blockCalciumCarbonate> : [<ore:stoneLimestone>, <ore:stoneMarble>],
    <ore:gemManaDiamond> : [<ore:manaDiamond>],
    <ore:gemManaLapis> : [<botanicadds:mana_lapis>],
    <ore:blockManaLapis> : [<botanicadds:mana_lapis_block>],
    <ore:gemManaQuartz> : [<botania:quartz:1>],
    <ore:shardSpace> : [<rftools:dimensional_shard>],
    <ore:ingotAurorianite> : [<theaurorian:aurorianiteingot>],
    <ore:ingotCrystalline> : [<theaurorian:crystallineingot>],
    <ore:ingotUmbra> : [<theaurorian:umbraingot>],
    <ore:logWoodVethea> : [
        <divinerpg:dreamwood_log>,
        <divinerpg:hyrewood_log>,
        <divinerpg:mintwood_log>,
        <divinerpg:firewood_log>
    ],
    <ore:gemDilithium> : [<taiga:dilithium_crystal>],
    <ore:dilithium> : [<taiga:dilithium_crystal>],
    <ore:dustShadium> : [<journey:shadiumdust>],
    <ore:dustLunium> : [<journey:luniumdust>],
    <ore:ingotVentium> : [<blue_skies:ventium_ingot>],
    <ore:ingotFalsite> : [<blue_skies:falsite_ingot>],
    <ore:ingotHorizonite> : [<blue_skies:horizonite_ingot>],
    <ore:oreHorizonite> : [<blue_skies:horizonite_ore>],
    <ore:ingotDreadium> : [<abyssalcraft:dreadiumingot>],
    <ore:blockDreadium> : [<abyssalcraft:ingotblock:2>],
    <ore:crystalClusterDreadium> : [<abyssalcraft:crystalcluster:14>],
    <ore:crystalDreadium> : [<abyssalcraft:crystal:14>],
    <ore:crystalShardDreadium> : [<abyssalcraft:crystalshard:14>],
    <ore:crystalFragmentDreadium> : [<abyssalcraft:crystalfragment:14>],
    <ore:nuggetDreadium> : [<abyssalcraft:ingotnugget:2>],
    <ore:oreDreadium> : [<gct_aby:dreadiumore>],
    <ore:oreDiopside> : [<blue_skies:everbright_diopside_ore>, <blue_skies:everdawn_diopside_ore>],
    <ore:orePyrope> : [<blue_skies:everbright_pyrope_ore>, <blue_skies:everdawn_pyrope_ore>],
    <ore:oreTurquoise> : [<blue_skies:everbright_turquoise_ore>, <blue_skies:everdawn_turquoise_ore>],
    <ore:oreCharoite> : [<blue_skies:everbright_charoite_ore>, <blue_skies:everdawn_charoite_ore>],
    <ore:oreMoonstoneBlue> : [<blue_skies:everbright_moonstone_ore>, <blue_skies:everdawn_moonstone_ore>],
    <ore:gemDiopside> : [<blue_skies:diopside_gem>],
    <ore:gemPyrope> : [<blue_skies:pyrope_gem>],
    <ore:gemTurquoise> : [<blue_skies:turquoise_gem>],
    <ore:gemCharoite> : [<blue_skies:charoite>],
    <ore:gemMoonstoneBlue> : [<blue_skies:moonstone_shard>],
    <ore:blockDiopside> : [<blue_skies:diopside_block>],
    <ore:blockPyrope> : [<blue_skies:pyrope_block>],
    <ore:blockTurquoise> : [<blue_skies:turquoise_block>],
    <ore:blockCharoite> : [<blue_skies:charoite_block>],
    <ore:blockMoonstoneBlue> : [<blue_skies:moonstone_block>],
    <ore:blockOraclium> : [<tiths:block_oraclium>],
    <ore:blockHalleium> : [<tiths:block_halleium>],
    <ore:blockAltairium> : [<tiths:block_altairium>],
    <ore:blockPolarium> : [<tiths:block_polarium>],
    <ore:blockTonium> : [<tiths:block_tonium>],
    <ore:blockStellarium> : [<tiths:block_stellarium>],
    <ore:blockHothium> : [<tiths:block_hothium>],
    <ore:blockMagiga> : [<tiths:block_magiga>],
    <ore:blockImitatium> : [<tiths:block_imitatium>],
    <ore:blockTanatonium> : [<tiths:block_tanatonium>],
    <ore:blockSteamium> : [<tiths:block_steamium>],
    <ore:blockSilverImmersed> : [<tiths:block_immersed_silver>],
    <ore:oreHalleium> : [<tiths:ore_halleium>],
    <ore:oreHothium> : [<tiths:ore_hothium>],
    <ore:oreAltairium> : [<tiths:ore_altairium>],
    <ore:orePolarium> : [<tiths:ore_polarium>],
    <ore:oreTonium> : [<tiths:ore_tonium>],
    <ore:oreStellarium> : [<tiths:ore_stellarium>],
    <ore:nuggetHalleium> : [<tiths:nugget_halleium>],
    <ore:nuggetHothium> : [<tiths:nugget_hothium>],
    <ore:nuggetAltairium> : [<tiths:nugget_altairium>],
    <ore:nuggetPolarium> : [<tiths:nugget_polarium>],
    <ore:nuggetTonium> : [<tiths:nugget_tonium>],
    <ore:nuggetStellarium> : [<tiths:nugget_stellarium>],
    <ore:nuggetMagiga> : [<tiths:nugget_magiga>],
    <ore:nuggetImitatium> : [<tiths:nugget_imitatium>],
    <ore:nuggetTanatonium> : [<tiths:nugget_tanatonium>],
    <ore:nuggetSteamium> : [<tiths:nugget_steamium>],
    <ore:nuggetSilverImmersed> : [<tiths:nugget_immersed_silver>],
    <ore:gemBlackrock> : [<tiths:blackrock>],
    <ore:gemBedrockBroken> : [<tiths:broken_bedrock>],
    <ore:gemIceBroken> : [<tiths:broken_ice>],
    <ore:gemCorundum> : [<tiths:corundum>],
    <ore:shardEnderCrevice> : [<tiths:ender_crevice_shard>],
    <ore:scaleDragonEnder> : [
        <tiths:ender_dragon_squama>,
        <endreborn:dragon_scales>,
        <mysticalagradditions:stuff:3>
    ],
    <ore:gemFurutorin> : [<tiths:furutorin>],
    <ore:gemSpiderLegHard> : [<tiths:hard_spider_leg>],
    <ore:gemHeavesand> : [<tiths:heavesand>],
    <ore:gemIcelandspar> : [<tiths:iceland_spar>],
    <ore:gemIcelit> : [<tiths:icelit>],
    <ore:gemLavaCrystal> : [<tiths:lava_crystal>],
    <ore:gemLizanite> : [<tiths:lizanite>],
    <ore:dustNiter> : [<tiths:nitre>],
    <ore:dustSaltpeter> : [<tiths:nitre>],
    <ore:nuggetChloroplast> : [<tiths:nugget_chloroplast>],
    <ore:nuggetCocoa> : [<tiths:nugget_cocoa>],
    <ore:nuggetDecurrium> : [<tiths:nugget_decurrium>],
    <ore:nuggetWitheriumInert> : [<tiths:nugget_inert_witherium>],
    <ore:nuggetIrisia> : [<tiths:nugget_irisia>],
    <ore:nuggetOraclium> : [<tiths:nugget_oraclium>],
    <ore:nuggetRoyalAlloy> : [<tiths:nugget_royal_alloy>],
    <ore:nuggetSolita> : [<tiths:nugget_solita>],
    <ore:nuggetWitherium> : [<tiths:nugget_witherium>],
    <ore:gemPotos> : [<tiths:potos>],
    <ore:gemProustite> : [<tiths:proustite>],
    <ore:gemPyrophyllite> : [<tiths:pyrophyllite>],
    <ore:itemWitheringDust> : [<tiths:withering_essence>],
    <ore:gemRedins> : [<tiths:redins>],
    <ore:gemSpiderLeg> : [<tiths:spider_leg>],
    <ore:gemTalcum> : [<tiths:talcum>],
    <ore:gemTorrentialCrystal> : [<tiths:torrential_crystal>],
    <ore:gemTourmaline> : [<tiths:tourmaline>],
    <ore:gemRoot> : [<tiths:tree_root>],
    <ore:gemUlun> : [<tiths:ulun>],
    <ore:gemVibratingCrystal> : [<tiths:vibrating_crystal>],
    <ore:blockBlackrock> : [<tiths:block_blackrock>],
    <ore:sandBlood> : [<tiths:block_blood_sand>],
    <ore:blockChloroplast> : [<tiths:block_chloroplast>],
    <ore:sandBloodCoagulated> : [<tiths:block_coagulated_blood_sand>],
    <ore:blockCocoa> : [<tiths:block_cocoa>],
    <ore:blockGlass> : [<tiths:block_colorful_glass>],
    <ore:blockCordierite> : [<tiths:block_cordierite>],
    <ore:blockCorundum> : [<tiths:block_corundum>],
    <ore:blockDecurrium> : [<tiths:block_decurrium>],
    <ore:blockFulgurite> : [<tiths:block_fulgurite>],
    <ore:blockFurutorin> : [<tiths:block_furutorin>],
    <ore:blockHeavesand> : [<tiths:block_heavesand>],
    <ore:blockIcelandspar> : [<tiths:block_iceland_spar>],
    <ore:blockIcelit> : [<tiths:block_icelit>],
    <ore:blockIrisia> : [<tiths:block_irisia>],
    <ore:blockLavaCrystal> : [<tiths:block_lava_crystal>],
    <ore:blockLizanite> : [<tiths:block_lizanite>],
    <ore:blockMercurySulfide> : [<tiths:block_mercury_sulfide>],
    <ore:blockCinnabar> : [<tiths:block_mercury_sulfide>],
    <ore:blockMeteorolite> : [<tiths:block_meteorolite>],
    <ore:blockMoonstone> : [<tiths:block_moon_stone>],
    <ore:blockNiter> : [<tiths:block_nitre>],
    <ore:blockSaltpeter> : [<tiths:block_nitre>],
    <ore:blockOpal> : [<tiths:block_opal>],
    <ore:blockPotos> : [<tiths:block_potos>],
    <ore:blockPrehnite> : [<tiths:block_prehnite>],
    <ore:blockProustite> : [<tiths:block_proustite>],
    <ore:blockPyrophyllite> : [<tiths:block_pyrophyllite>],
    <ore:blockRoyalAlloy> : [<tiths:block_royal_alloy>],
    <ore:blockRedins> : [<tiths:block_redins>],
    <ore:blockSolita> : [<tiths:block_solita>],
    <ore:blockSpinel> : [<tiths:block_spinel>],
    <ore:blockSunstone> : [<tiths:block_sun_stone>],
    <ore:blockTalcum> : [<tiths:block_talcum>],
    <ore:blockTopaz> : [<tiths:block_topaz>],
    <ore:blockTorrentialCrystal> : [<tiths:block_torrential_crystal>],
    <ore:blockUlun> : [<tiths:block_ulun>],
    <ore:blockVibratingCrystal> : [<tiths:block_vibrating_crystal>],
    <ore:gemBrumeJade> : [<tiths:brume_jade>],
    <ore:oreBrumeJade> : [<tiths:ore_brume_jade>],
    <ore:oreBlackrock> : [<tiths:ore_blackrock>],
    <ore:oreBedrockBroken> : [<tiths:ore_broken_bedrock>],
    <ore:oreChloroplast> : [<tiths:ore_chloroplast>],
    <ore:oreCinnabar> : [<tiths:ore_cinnabar>],
    <ore:oreCordierite> : [<tiths:ore_cordierite>],
    <ore:oreCorundum> : [<tiths:ore_corundum>],
    <ore:oreFurutorin> : [<tiths:ore_furutorin>],
    <ore:oreHeavesand> : [<tiths:ore_heavesand>],
    <ore:oreIcelandspar> : [<tiths:ore_iceland_spar>],
    <ore:oreIcelit> : [<tiths:ore_icelit>],
    <ore:oreImitatium> : [<tiths:ore_imitatium>],
    <ore:oreImmersedSilver> : [<tiths:ore_immersed_silver>],
    <ore:oreWitheriumInert> : [<tiths:ore_inert_witherium>],
    <ore:oreDyeBlack> : [<tiths:ore_ink_powder>],
    <ore:oreLavaCrystal> : [<tiths:ore_lava_crystal>],
    <ore:oreLizanite> : [<tiths:ore_lizanite>],
    <ore:oreMoonstone> : [<tiths:ore_moon_stone>],
    <ore:oreNiter> : [<tiths:ore_nitre>],
    <ore:oreSaltpeter> : [<tiths:ore_nitre>],
    <ore:oreOpal> : [<tiths:ore_opal>],
    <ore:orePotos> : [<tiths:ore_potos>],
    <ore:orePrehnite> : [<tiths:ore_prehnite>],
    <ore:oreProustite> : [<tiths:ore_proustite>],
    <ore:orePyrophyllite> : [<tiths:ore_pyrophyllite>],
    <ore:oreRedins> : [<tiths:ore_redins>],
    <ore:oreDirtSolid> : [<tiths:ore_solid_dirt>],
    <ore:oreSandSolid> : [<tiths:ore_solid_sand>],
    <ore:oreStoneSolid> : [<tiths:ore_solid_stone>],
    <ore:oreSpinel> : [<tiths:ore_spinel>],
    <ore:oreSunstone> : [<tiths:ore_sun_stone>],
    <ore:oreTalcum> : [<tiths:ore_talcum>],
    <ore:oreTopaz> : [<tiths:ore_topaz>],
    <ore:oreTourmaline> : [<tiths:ore_tourmaline>],
    <ore:oreRoot> : [<tiths:ore_tree_root>],
    <ore:oreUlun> : [<tiths:ore_ulun>],
    <ore:oreVibratingCrystal> : [<tiths:ore_vibrating_crystal>],
    <ore:gemAquamarine> : [<divinerpg:aquamarine>],
    <ore:ingotNeutronium> : [<avaritia:resource:4>],
    <ore:blockNeutronium> : [<avaritia:block_resource>],
    <ore:nuggetNeutronium> : [<avaritia:resource:3>],
    <ore:blockPhotonium> : [<extrabotany:blockphotonium>],
    <ore:blockGaia> : [<avaritiatweaks:gaia_block>],
    <ore:treeSaplingLiving> : [<treetweaker:livingwood>],
    <ore:treeSaplingDream> : [<treetweaker:dreamwood>, <treetweaker:redreamwood>],
    <ore:treeSapling> : [<treetweaker:evileye>],
    <ore:gemMercury> : [<thaumcraft:quicksilver>, <tiths:cinnabar>],
    <ore:gemQuicksilver> : [<thaumcraft:quicksilver>, <tiths:cinnabar>],
    <ore:nuggetMercury> : [<thaumcraft:nugget:5>],
    <ore:blockMercury> : [<tiths:block_cinnabar>],
    <ore:blockQuicksilver> : [<tiths:block_cinnabar>],
    <ore:scrapNaturalline> : [<gct_mobs:naturalline_scrap>],
    <ore:gemNaturalline> : [<gct_mobs:naturalline>],
    <ore:gemGlistenQuartz> : [<arcanearchives:raw_quartz>],
    <ore:gemGlistenQuartzProcessed> : [<arcanearchives:shaped_quartz>],
    <ore:blockGlistenQuartz> : [<arcanearchives:storage_raw_quartz>],
    <ore:blockGlistenQuartzProcessed> : [<arcanearchives:storage_shaped_quartz>],
    <ore:armorAurorianite> : [
        <theaurorian:aurorianitepickaxe>,
        <theaurorian:aurorianiteaxe>,
        <theaurorian:aurorianitesword>
    ],
    <ore:armorCrystalline> : [
        <theaurorian:crystallinepickaxe>,
        <theaurorian:crystallinesword>,
        <theaurorian:crystallineshield>
    ],
    <ore:armorUmbra> : [
        <theaurorian:umbrapickaxe>,
        <theaurorian:umbrasword>,
        <theaurorian:umbrashield>
    ],
    <ore:ingotEnderiron> : [<extendedcrafting:material:36>],
    <ore:nuggetEnderiron> : [<extendedcrafting:material:37>],
    <ore:blockEnderiron> : [<extendedcrafting:storage:5>],
    <ore:ingotEnderironex> : [<extendedcrafting:material:48>],
    <ore:nuggetEnderironex> : [<extendedcrafting:material:49>],
    <ore:blockEnderironex> : [<extendedcrafting:storage:7>],
    <ore:heartGaia> : [<gct_mobs:gaia_heart>],
    <ore:ingotRosium> : [<gct_mobs:rosium_ingot>],
    <ore:ingotChrysanthemium> : [<gct_mobs:chrysanthemium_ingot>],
    <ore:ingotDandelionium> : [<gct_mobs:dandelionium_ingot>],
    <ore:ingotMyosotisium> : [<gct_mobs:myosotisium_ingot>],
    <ore:ingotBegonium> : [<gct_mobs:begonium_ingot>],
    <ore:ingotCarnationium> : [<gct_mobs:carnationium_ingot>],
    <ore:ingotAuraIron> : [<naturesaura:infused_iron>],
    <ore:blockAuraIron> : [<naturesaura:infused_iron_block>],
    <ore:ingotSky> : [<naturesaura:sky_ingot>],
    <ore:gemFirestone> : [<journey:firestoneclump>],
    <ore:gemAquamarineStarlight> : [<astralsorcery:itemcraftingcomponent:4>],
    <ore:gemAkuamarin> : [<astralsorcery:itemcraftingcomponent:4>],
    <ore:gemRubyStarlight> : [<additions:resonating_ruby>],
    <ore:gemRubii> : [<additions:resonating_ruby>],
    <ore:dustObsidian> : [<endreborn:catalyst>],
    <ore:necronomiconOverworld> : [<abyssalcraft:necronomicon>],
    <ore:necronomiconWasteland> : [<abyssalcraft:necronomicon_cor>],
    <ore:necronomiconDreadland> : [<abyssalcraft:necronomicon_dre>],
    <ore:necronomiconOmothol> : [<abyssalcraft:necronomicon_omt>],
    <ore:necronomiconAbyss> : [<abyssalcraft:abyssalnomicon>],
    <ore:circuitCreative> : [<mekanism:controlcircuit:4>],
    <ore:gemCoalAlchemical> : [<projecte:item.pe_fuel>],
    <ore:gemCoalMobius> : [<projecte:item.pe_fuel:1>],
    <ore:gemCoalAeternalis> : [<projecte:item.pe_fuel:2>],
    <ore:blockCoalAlchemical> : [<projecte:fuel_block>],
    <ore:blockCoalMobius> : [<projecte:fuel_block:1>],
    <ore:blockCoalAeternalis> : [<projecte:fuel_block:2>],
    <ore:oreFalsite> : [<blue_skies:falsite_ore>],
    <ore:oreVentium> : [<blue_skies:ventium_ore>],
    <ore:eioGearIron> : [<enderio:item_material:11>],
    <ore:eioGearEnergeticAlloy> : [<enderio:item_material:12>],
    <ore:eioGearVibrantAlloy> : [<enderio:item_material:13>],
    <ore:eioGearDarkSteel> : [<enderio:item_material:73>],
    <ore:blockEnderBiotite> : [<quark:biotite_block>],
    <ore:blockEndBiotite> : [<quark:biotite_block>],
    <ore:blockFluix> : [<appliedenergistics2:fluix_block>],
    <ore:blockCertusQuartz> : [<appliedenergistics2:quartz_block>],
    <ore:blockHorizonite> : [<blue_skies:horizonite_block>],
    <ore:frameManasteel> : [<gct_ores:manasteel_machine_frame>],
    <ore:frameElementium> : [<gct_ores:elemetiumsteel_machine_frame>],
    <ore:frameElvenElementium> : [<gct_ores:elemetiumsteel_machine_frame>],
    <ore:frameTerrasteel> : [<gct_ores:terrasteel_machine_frame>],
    <ore:frameGaia> : [<gct_ores:gaia_spirit_machine_frame>],
    <ore:frameGaiasteel> : [<gct_ores:gaia_steel_machine_frame>],
    <ore:frameOrichalcos> : [<gct_ores:orichalcos_machine_frame>],
    <ore:ingotCthulhurite> : [<gct_mobs:cthulhurite_ingot>],
    <ore:ingotAluminium> : [<thermalfoundation:material:132>],
    <ore:blockAluminium> : [<thermalfoundation:storage:4>],
    <ore:nuggetAluminium> : [<thermalfoundation:material:196>],
    <ore:dustAluminium> : [<thermalfoundation:material:68>],
    <ore:blockApocalypsium> : [<gct_mobs:apocalypsium_block>],
    <ore:blockArlemite> : [<divinerpg:arlemite_block>],
    <ore:blockAzathothium> : [<gct_mobs:azathothium_block>],
    <ore:blockCelestium> : [<journey:celestiumblock>],
    <ore:blockCerulean> : [<theaurorian:ceruleanblock>],
    <ore:blockCobalt> : [<tconstruct:metal>],
    <ore:blockDensite> : [<gct_ores:densite_block>],
    <ore:blockDes> : [<journey:desblock>],
    <ore:blockDraconiumChaotic> : [<gct_ores:chaotic_draconium_block>],
    <ore:blockDraconiumRuled> : [<gct_ores:ruled_draconium_block>],
    <ore:blockEverite> : [<gct_ores:everite_block>],
    <ore:blockFireAlloy> : [<gct_ores:fire_alloy_block>],
    <ore:blockFlairium> : [<journey:flairiumblock>],
    <ore:blockGenite> : [<gct_ores:genite_block>],
    <ore:blockIceAlloy> : [<gct_ores:ice_alloy_block>],
    <ore:blockKorite> : [<journey:koriteblock>],
    <ore:blockLunium> : [<journey:luniumblock>],
    <ore:blockMana> : [<gct_mobs:mana_block>],
    <ore:blockManasteel> : [<botania:storage>],
    <ore:blockMekyum> : [<journey:mekyumblock>],
    <ore:blockMoonstone> : [<theaurorian:moonstoneblock>],
    <ore:blockNyarlathotepium> : [<gct_mobs:nyarlathotepium_block>],
    <ore:blockOrbadite> : [<journey:orbaditeblock>],
    <ore:blockOrderedMetal> : [<gct_ores:ordered_metal_block>],
    <ore:blockReditrite> : [<gct_ores:reditrite_block>],
    <ore:blockRealmite> : [<divinerpg:realmite_block>],
    <ore:blockRupee> : [<divinerpg:rupee_block>],
    <ore:blockShadium> : [<journey:shadiumblock>],
    <ore:blockShubniggurathium> : [<gct_mobs:shubniggurathium_block>],
    <ore:blockSkyAlloy> : [<gct_ores:sky_alloy_block>],
    <ore:blockStoron> : [<journey:storonblock>],
    <ore:blockValkyrie> : [<tinkersaether:valkyrie_block>],
    <ore:ingotValkyrie> : [<tinkersaether:valkyrie_ingot>],
    <ore:nuggetValkyrie> : [<tinkersaether:valkyrie_nugget>],
    <ore:blockWitheriumEquipment> : [<gct_ores:equipment_witherium_block>],
    <ore:blockWitheriumRelifed> : [<gct_ores:relifed_witherium_block>],
    <ore:blockWitheriumStormy> : [<gct_ores:stormy_witherium_block>],
    <ore:blockYogsothothium> : [<gct_mobs:yogsothothium_block>],
    <ore:blockCthulhurite> : [<gct_mobs:cthulhurite_block>],
    <ore:nuggetApocalypsium> : [<gct_mobs:apocalypsium_nugget>],
    <ore:nuggetArlemite> : [<divinerpg:arlemite_nugget>],
    <ore:nuggetCerulean> : [<theaurorian:ceruleannugget>],
    <ore:nuggetDensite> : [<gct_ores:densite_nugget>],
    <ore:nuggetDraconiumChaotic> : [<gct_ores:chaotic_draconium_nugget>],
    <ore:nuggetDraconiumRuled> : [<gct_ores:ruled_draconium_nugget>],
    <ore:nuggetEverite> : [<gct_ores:everite_nugget>],
    <ore:nuggetFireAlloy> : [<gct_ores:fire_alloy_nugget>],
    <ore:nuggetGenite> : [<gct_ores:genite_nugget>],
    <ore:nuggetIceAlloy> : [<gct_ores:ice_alloy_nugget>],
    <ore:nuggetMoonstone> : [<theaurorian:moonstonenugget>],
    <ore:nuggetOrderedMetal> : [<gct_ores:ordered_metal_nugget>],
    <ore:nuggetReditrite> : [<gct_ores:reditrite_nugget>],
    <ore:nuggetRealmite> : [<divinerpg:realmite_nugget>],
    <ore:nuggetRupee> : [<divinerpg:rupee_nugget>],
    <ore:nuggetSkyAlloy> : [<gct_ores:sky_alloy_nugget>],
    <ore:nuggetValkyrie> : [<tinkersaether:valkyrie_nugget>],
    <ore:nuggetWitheriumEquipment> : [<gct_ores:equipment_witherium_nugget>],
    <ore:nuggetWitheriumRelifed> : [<gct_ores:relifed_witherium_nugget>],
    <ore:nuggetWitheriumStormy> : [<gct_ores:stormy_witherium_nugget>],
    <ore:dustApocalypsium> : [<gct_mobs:apocalypsium_dust>],
    <ore:dustDensite> : [<gct_ores:densite_dust>],
    <ore:dustDraconiumChaotic> : [<gct_ores:chaotic_draconium_dust>],
    <ore:dustDraconiumRuled> : [<gct_ores:ruled_draconium_dust>],
    <ore:dustEverite> : [<gct_ores:everite_dust>],
    <ore:dustFireAlloy> : [<gct_ores:fire_alloy_dust>],
    <ore:dustGenite> : [<gct_ores:genite_dust>],
    <ore:dustIceAlloy> : [<gct_ores:ice_alloy_dust>],
    <ore:dustOrderedMetal> : [<gct_ores:ordered_metal_dust>],
    <ore:dustReditrite> : [<gct_ores:reditrite_dust>],
    <ore:dustSkyAlloy> : [<gct_ores:sky_alloy_dust>],
    <ore:dustWitheriumEquipment> : [<gct_ores:equipment_witherium_dust>],
    <ore:dustWitheriumRelifed> : [<gct_ores:relifed_witherium_dust>],
    <ore:dustWitheriumStormy> : [<gct_ores:stormy_witherium_dust>],
    <ore:gearApocalypsium> : [<gct_mobs:apocalypsium_gear>],
    <ore:gearDensite> : [<gct_ores:densite_gear>],
    <ore:gearDraconiumChaotic> : [<gct_ores:chaotic_draconium_gear>],
    <ore:gearDraconiumRuled> : [<gct_ores:ruled_draconium_gear>],
    <ore:gearEverite> : [<gct_ores:everite_gear>],
    <ore:gearFireAlloy> : [<gct_ores:fire_alloy_gear>],
    <ore:gearGenite> : [<gct_ores:genite_gear>],
    <ore:gearIceAlloy> : [<gct_ores:ice_alloy_gear>],
    <ore:gearOrderedMetal> : [<gct_ores:ordered_metal_gear>],
    <ore:gearReditrite> : [<gct_ores:reditrite_gear>],
    <ore:gearSkyAlloy> : [<gct_ores:sky_alloy_gear>],
    <ore:gearWitheriumEquipment> : [<gct_ores:equipment_witherium_gear>],
    <ore:gearWitheriumRelifed> : [<gct_ores:relifed_witherium_gear>],
    <ore:gearWitheriumStormy> : [<gct_ores:stormy_witherium_gear>],
    <ore:plateApocalypsium> : [<gct_mobs:apocalypsium_plate>],
    <ore:plateDensite> : [<gct_ores:densite_plate>],
    <ore:plateDraconiumChaotic> : [<gct_ores:chaotic_draconium_plate>],
    <ore:plateDraconiumRuled> : [<gct_ores:ruled_draconium_plate>],
    <ore:plateEverite> : [<gct_ores:everite_plate>],
    <ore:plateFireAlloy> : [<gct_ores:fire_alloy_plate>],
    <ore:plateGenite> : [<gct_ores:genite_plate>],
    <ore:plateIceAlloy> : [<gct_ores:ice_alloy_plate>],
    <ore:plateOrderedMetal> : [<gct_ores:ordered_metal_plate>],
    <ore:plateReditrite> : [<gct_ores:reditrite_plate>],
    <ore:plateSkyAlloy> : [<gct_ores:sky_alloy_plate>],
    <ore:plateWitheriumEquipment> : [<gct_ores:equipment_witherium_plate>],
    <ore:plateWitheriumRelifed> : [<gct_ores:relifed_witherium_plate>],
    <ore:plateWitheriumStormy> : [<gct_ores:stormy_witherium_plate>],
    <ore:blockAmbrosium> : [<aether_legacy:ambrosium_block>],
    <ore:blockScabyst> : [<thebetweenlands:scabyst_block>],
    <ore:blockManaQuartz> : [<botania:quartztypemana>],
    <ore:dustBloodcrust> : [<journey:hellstonedust>],
    <ore:dustCelestium> : [<journey:celestiumdust>],
    <ore:dustFlairium> : [<journey:flairiumdust>],
    <ore:dustCloudiaGem> : [<journey:sapphiredust>],
    <ore:gemCloudiaGem> : [<journey:sapphire>],
    <ore:blockCloudiaGem> : [<journey:sapphireblock>],
    <ore:dustEnderillium> : [<journey:enderilliumdust>],
    <ore:dustGorbite> : [<journey:gorbitedust>],
    <ore:dustOrbadite> : [<journey:orbaditedust>],
    <ore:dustDiamond> : [<journey:diamonddust>],
    <ore:dustGold> : [<journey:golddust>],
    <ore:dustIron> : [<journey:irondust>],
    <ore:dustBleedstone> : [<journey:bleedstonedust>],
    <ore:dustSmithstone> : [<journey:smithstonedust>],
    <ore:dustAshual> : [<journey:ash>],
    <ore:gemBlazium> : [<journey:blazium>],
    <ore:gemEnderillium> : [<journey:enderilliumshard>],
    <ore:gemGorbite> : [<journey:gorbitegem>],
    <ore:gemSoulstone> : [<journey:soulstone>],
    <ore:blockSoulstone> : [<journey:nethicgemstoneblock>],
    <ore:blockAmber> : [<betterendforge:amber_block>],
    <ore:scaleDragonFire> : [
        <iceandfire:dragonscales_red>,
        <iceandfire:dragonscales_green>,
        <iceandfire:dragonscales_bronze>,
        <iceandfire:dragonscales_gray>
    ],
    <ore:scaleDragonIce> : [
        <iceandfire:dragonscales_blue>,
        <iceandfire:dragonscales_white>,
        <iceandfire:dragonscales_sapphire>,
        <iceandfire:dragonscales_silver>
    ],
    <ore:scaleDragonLightning> : [
        <iceandfire:dragonscales_electric>,
        <iceandfire:dragonscales_black>,
        <iceandfire:dragonscales_sapphire>,
        <iceandfire:dragonscales_copper>
    ],
    <ore:button> : [<minecraft:stone_button>]
};

var removeMap as IIngredient[][IOreDictEntry] = {
    <ore:cobblestone> : [<quark:biome_cobblestone:1>]
};

for oredict in oredictMap {
    var ingredients as IIngredient[] = oredictMap[oredict];
    OredictUtil.addOredictIngredients(oredict, ingredients);
}

for oredict in removeMap {
    var ingredients as IIngredient[] = oredictMap[oredict];
    OredictUtil.removeOredictIngredients(oredict, ingredients);
}
