//新源质
mods.thaumcraft.aspect.aspectBuilder()
    .tag('abyss')
    .chatColor(0x2C2C2C)
    .component('exanimis')
    .component('vacuos')
    .image(resource('thaumcraft:textures/aspects/abyss.png'))
    .register()

mods.thaumcraft.aspect.aspectBuilder()
    .tag('cthulhu')
    .chatColor(0x294314)
    .image(resource('thaumcraft:textures/aspects/cthulhu.png'))
    .register()

mods.thaumcraft.aspect.aspectBuilder()
    .tag('tempestas')
    .chatColor(0x29659B)
    .component('aer')
    .component('aqua')
    .image(resource('thaumcraft:textures/aspects/tempestas.png'))
    .register()

mods.thaumcraft.aspect.aspectBuilder()
    .tag('pulvis')
    .chatColor(0x797979)
    .component('ignis')
    .component('terra')
    .image(resource('thaumcraft:textures/aspects/pulvis.png'))
    .register()

mods.thaumcraft.aspect.aspectBuilder()
    .tag('primitivus')
    .chatColor(0x2BA245)
    .component('terra')
    .component('perditio')
    .image(resource('thaumcraft:textures/aspects/primitivus.png'))
    .register()

mods.thaumcraft.aspect.aspectBuilder()
    .tag('vapor')
    .chatColor(0xFFFFFF)
    .component('aqua')
    .component('ignis')
    .image(resource('thaumcraft:textures/aspects/vapor.png'))
    .register()

mods.thaumcraft.aspect.aspectBuilder()
    .tag('structura')
    .chatColor(0xB3260E)
    .component('aqua')
    .component('ordo')
    .image(resource('thaumcraft:textures/aspects/structura.png'))
    .register()

