name = "GreedyCraft2"
author = "mc_Edwin"
version = "2.8.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15b6b128045d4ab2bdc720b3382ad2edc6a057f36844f12c2004fe1fad0668f4"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
quilt = "0.17.0"

[export.curseforge]
project-id = 0
