name = "GreedyCraft2"
author = "mc_Edwin"
version = "2.8.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5ac040c042fe66d2daf2de3445522c110308c0b444e36d598f9cb9bc20dfb8a"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
quilt = "0.17.0"

[export.curseforge]
project-id = 0
