mods.astralsorcery.constellation.constellationBuilder()
    .weak()
    .name('sanguiso')
    .color(0xEE0C2D)
    .connection(7,9,14,5)
    .connection(14,5,23,4)
    .connection(23,4,21,11)
    .connection(21,11,16,14)
    .connection(16,14,14,5)
    .connection(23,4,27,18)
    .connection(27,18,15,27)
    .register()
mods.astralsorcery.constellation.constellationMapEffectBuilder()
    .constellation(constellation('sanguiso'))
    .enchantmentEffect(enchantment('evilcraft:life_stealing'), 1, 4)
    .potionEffect(potion('potioncore:purity'), 1, 1)
    .register()