
inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('blackhole_alloy'),0.0f)
        .input(item('gct_aby:shadownuclear'))
        .input(item('additions:cosmilite_ingot'))
        .output(item('thebetweenlands:swamp_talisman:1'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('blackhole_alloy'),0.0f)
        .input(item('aether_legacy:dungeon_key:2'))
        .input(item('aether_legacy:dungeon_key:1'))
        .input(item('aether_legacy:dungeon_key'))
        .input(item('additions:cosmilite_ingot'))
        .output(item('thebetweenlands:swamp_talisman:2'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('blackhole_alloy'),0.0f)
        .input(item('gct_aby:ancientmud'))
        .input(item('additions:cosmilite_ingot'))
        .output(item('thebetweenlands:swamp_talisman:3'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('blackhole_alloy'),0.0f)
        .input(item('gct_aby:shoggothtancale'))
        .input(item('additions:cosmilite_ingot'))
        .output(item('thebetweenlands:swamp_talisman:4'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('endacid'))
        .input(item('endreborn:item_ingot_endorium')*6)
        .input(item('moretcon:gemenderal')*5)
        .input(item('tiths:ender_crevice_shard')*5)
        .input(item('gct_mobs:resonated_scrap'))
        .output(item('moretcon:repitem:2')*3)
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('darkest'))
        .input(item('abyssalcraft:shadowgem')*8)
        .input(item('thaumcraft:void_seed')*16)
        .input(item('gct_ores:stormy_witherium_ingot')*3)
        .input(item('additions:shadowium_ingot')*4)
        .output(item('moretcon:repitem:3')*3)
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('liquidgoldenamber'))
        .input(item('aether_legacy:aether_log')*16)
        .input(item('aether_legacy:golden_amber')*4)
        .input(item('additions:asgardium_ingot')*2)
        .input(item('extrabotany:material:8')*2)
        .output(item('moretcon:repitem:5')*3)
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('fierymetal'))
        .input(item('twilightforest:steeleaf_ingot')*4)
        .input(item('twilightforest:ironwood_raw')*6)
        .input(item('twilightforest:knightmetal_ingot')*2)
        .output(item('moretcon:repitem:6')*3)
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('cosmilite'),0.0f)
        .input(item('additions:greedycraft-rotiron_scrap')*9)
        .input(item('additions:greedycraft-bone_shard'))
        .output(item('moretcon:ingotrotiron'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('stagnant_water'),0.0f)
        .input(item('thebetweenlands:mire_scramble'))
        .input(item('thebetweenlands:items_misc:61'))
        .input(item('thebetweenlands:weeping_blue_petal_salad'))
        .input(item('thebetweenlands:sushi'))
        .output(item('thebetweenlands:bl_bucket_plant_tonic'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('burningsulfurflow'))
        .input(item('moretcon:gravitoniumsponge'))
        .output(item('moretcon:itemtrichromadentiumsponge:1'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('ichor'))
        .input(item('moretcon:itemtrichromadentiumsponge:1'))
        .output(item('moretcon:itemtrichromadentiumsponge:2'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('tamoltencerulean'))
        .input(item('moretcon:itemtrichromadentiumsponge:2'))
        .output(item('moretcon:itemtrichromadentiumsponge:3'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('moltenrefinedcoralium'))
        .input(item('moretcon:itemtrichromadentiumsponge:3'))
        .output(item('moretcon:itemtrichromadentiumsponge:4'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('balanced_matrix'),0.0f)
        .input(item('moretcon:itemtrichromadentiumsponge:4'))
        .output(item('moretcon:itemtrichromadentiumsponge:0'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('cosmilite'))
        .input(item('thebetweenlands:life_crystal'))
        .output(item('additions:greedycraft-gemundyingember'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('liquidember'))
        .input(item('moretcon:dustoctine'))
        .input(item('thebetweenlands:wisp'))
        .input(item('thebetweenlands:items_misc:46'))
        .input(item('thebetweenlands:items_crushed:21'))
        .output(item('thebetweenlands:shimmer_stone'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('rubber'))
        .input(item('thebetweenlands:items_misc:19')*16)
        .input(item('thebetweenlands:items_misc:39')*24)
        .input(item('thebetweenlands:sap_spit')*12)
        .input(item('additions:greedycraft-dirtshape'))
        .output(item('additions:greedycraft-valonitedruse')*2)
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('lava'))
        .input(item('additions:greedycraft-living_fire'))
        .output(item('additions:taigaddon-cthughate_ingot')*3)
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('lava'))
        .input(item('additions:botaniaddon-holium_ingot')*4)
        .input(item('additions:greedycraft-sun_crystal')*4)
        .input(item('aether_legacy:golden_amber'))
        .output(item('additions:greedycraft-apollonium_overheat_ingot'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('astralsorcery.liquidstarlight'))
        .input(item('astralsorcery:itemcraftingcomponent:4'))
        .input(item('additions:greedycraft-resonating_ruby'))
        .input(item('avaritia:block_resource:2'))
        .input(item('additions:greedycraft-nasalum_ingot'))
        .output(item('additions:greedycraft-brightine'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('unshapable_liquid'))
        .input(item('draconicevolution:chaos_shard'))
        .input(item('gct_ores:stormy_shard'))
        .input(item('thaumicaugmentation:material:5'))
        .input(item('additions:greedycraft-malevolence_core'))
        .output(item('additions:greedycraft-pruified_matter'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('lava_solid'),0.0f)
        .input(item('appliedenergistics2:sky_stone_block')*8)
        .input(item('astralsorcery:itemcraftingcomponent:1')*4)
        .output(item('additions:ignite_ingot'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('rottensludge'))
        .input(item('thebetweenlands:bl_bucket_plant_tonic'))
        .input(item('moretcon:ingotrunesteel'))
        .input(item('thebetweenlands:items_misc:11')*3)
        .input(item('thaumcraft:bottle_taint'))
        .output(item('additions:greedycraft-rotiron_scrap')*8)
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('betweensludge'),0.0f)
        .input(item('extendedcrafting:material')*2)
        .input(item('journey:storoningot')*8)
        .output(item('moretcon:ingotgravitonium')*5)
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('flux_goo'),0.0f)
        .input(item('thebetweenlands:chiromaw_barb'))
        .input(item('thebetweenlands:anadia_meat_smoked'))
        .input(item('thebetweenlands:pearled_pear'))
        .input(item('thebetweenlands:nibblestick'))
        .output(item('thebetweenlands:forbidden_fig')*16)
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('water'))
        .input(item('additions:greedycraft-soul_of_slider')*2)
        .input(item('aether_legacy:aercloud')*4)
        .input(item('aether_legacy:golden_amber'))
        .output(item('additions:greedycraft-slider_gem_unforked'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('cosmilite'))
        .input(item('thebetweenlands:mire_snail_egg'))
        .output(item('minecraft:spawn_egg').withNbt(['EntityTag': ['id': 'thebetweenlands:olm']]))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('betweensludge'))
        .input(item('additions:greedycraft-soul_of_slider')*2)
        .input(item('aether_legacy:aercloud')*4)
        .input(item('aether_legacy:golden_amber'))
        .output(item('additions:greedycraft-slider_gem_unforked'))
        .register()






inWorldCrafting.explosion.recipeBuilder()
    .input(item('biomesoplenty:crystal'))
    .output(item('moretcon:oreenderal'))
    .chance(0.1f)
    .register()
